
/* ================= Club VIP (#13), articles, concierge, notifications (#14) ================= */
const EVENTS={
 expo:{t:{fr:'Exposition Héritage',en:'Heritage Exhibition'},where:{fr:'Paris',en:'Paris'},date:'2026-12-12',w:'sh',d:{fr:'Une soirée réservée aux membres autour de l’histoire de la Superman, née en 1963, et des modèles actuels.',en:'A members-only evening on the history of the Superman, born in 1963, and today’s models.'},slots:[['s1',{fr:'Sam. 12 déc.',en:'Sat 12 Dec'},'18:30'],['s2',{fr:'Sam. 12 déc.',en:'Sat 12 Dec'},'20:30'],['s3',{fr:'Dim. 13 déc.',en:'Sun 13 Dec'},'11:00'],['s4',{fr:'Dim. 13 déc.',en:'Sun 13 Dec'},'15:00',1]]},
 cal:{t:{fr:'Rencontre calibre manufacture',en:'In-house calibre meet-up'},where:{fr:'Franche-Comté',en:'Franche-Comté'},date:'2027-01-23',w:'nmn',d:{fr:'Une matinée avec un horloger pour comprendre les calibres CMM. Huit places.',en:'A morning with a watchmaker to understand the CMM calibres. Eight seats.'},slots:[['c1',{fr:'Sam. 23 janv.',en:'Sat 23 Jan'},'09:30'],['c2',{fr:'Sam. 23 janv.',en:'Sat 23 Jan'},'14:00']]}
};
const ARTS={
 cmm:{k:{fr:'Savoir-faire',en:'Craft'},t:{fr:'CMM.10, CMM.20 : les calibres de la maison',en:'CMM.10, CMM.20: the house calibres'},m:2,w:'nmn',
  body:{fr:['Sur plusieurs modèles, YEMA équipe ses montres de calibres manufacture : le CMM.10 anime les Superman CMM.10, la Navygraf Marine Nationale et la Meteorite ; le CMM.20 la Wristmaster Slim et la Skin Diver.','« Une montre de collection se juge aussi à ce que l’on ne voit pas. »','Pour la Navygraf Marine Nationale, YEMA annonce des performances chronométriques et 70 heures de réserve de marche. Le fond saphir laisse voir le mouvement.'],en:['On several models YEMA fits in-house calibres: the CMM.10 powers the Superman CMM.10 watches, the Navygraf Marine Nationale and the Meteorite; the CMM.20 the Wristmaster Slim and the Skin Diver.','“A collector’s watch is also judged by what you cannot see.”','For the Navygraf Marine Nationale, YEMA announces chronometer-grade performance and a 70-hour power reserve. The sapphire caseback shows the movement.']}},
 sup:{k:{fr:'Héritage',en:'Heritage'},t:{fr:'Superman, la plongeuse de 1963',en:'Superman, the 1963 diver'},m:2,w:'sh',i:2,
  body:{fr:['Née en 1963, la Superman s’est fait connaître par son système de verrouillage de lunette, pensé pour les plongeurs.','« Un outil avant d’être un bijou. »','La Superman Heritage reprend ce vocabulaire : lunette graduée, cadran lisible et bracelet acier, en 39 ou 41 mm.'],en:['Born in 1963, the Superman became known for its bezel-locking system designed for divers.','“A tool before it is a jewel.”','The Superman Heritage keeps that vocabulary: graduated bezel, legible dial and steel bracelet, in 39 or 41 mm.']}}
};
SCR.club={large:1,title:()=>'Club VIP',right:()=>bellBtn(),
 render:p=>{p.seg=p.seg||'news';const bk=S.bookings.expo;
 const seg=`<div class="pills" role="tablist" style="margin-top:4px">${[['news',L('Actualités','News')],['events',L('Événements','Events')],['launch',L('Lancements','Launches')]].map(([k,l])=>`<button type="button" role="tab" aria-selected="${p.seg===k}" data-act="clubSeg" data-k="${k}">${l}</button>`).join('')}</div>`;
 const inv=`<div class="inv"><div class="bg">${roomArt('expo')}${pic(W('sh'),0,{alt:false})}</div><span class="bdg star">${ic('star')}${L('Invitation exclusive','Exclusive invitation')}</span><div class="ct"><h2 class="h1">${tx(EVENTS.expo.t)}</h2><div class="meta">${tx(EVENTS.expo.where)} · ${fdate(EVENTS.expo.date,{day:'numeric',month:'short',year:'numeric'})} · ${L('événement fictif','fictional event')}</div><div class="gl">${tx(EVENTS.expo.d)}${bk?`<div class="row" style="margin-top:10px;color:var(--gold3);font-weight:700">${ic('check')}${L('Réservé','Booked')} · ${bk.label}</div>`:''}<button class="btn ${bk?'line':'gold'}" type="button" data-act="book" data-e="expo">${bk?L('Modifier ma réservation','Change booking'):L('Réserver','Reserve')}</button></div></div></div>`;
 const pv=[['nme',L('150 exemplaires numérotés','150 numbered pieces')],['sbz',L('Première série de 50 par modèle','First batch of 50 per model')],['ral',L('Ouverte en précommande','Open for pre-order')]];
 const news=`${inv}<div class="sec"><div class="sech"><h2 class="h2">${L('Avant-premières','Previews')}</h2><button class="link" type="button" data-act="clubSeg" data-k="launch">${L('Tout voir','See all')}</button></div><div class="hscroll">${pv.map(([id,d])=>{const w=W(id);return `<div class="card pv">${pic(w,0,{alt:false})}<h3 class="h3">${esc(w.n)}</h3><p>${d}</p><button class="btn line sm" type="button" data-act="pdp" data-id="${id}" style="width:100%">${L('Voir la pièce','View piece')}</button></div>`;}).join('')}</div></div>
 <div class="sec pad"><div class="sech" style="margin:0 0 12px"><h2 class="h2">${L('Dans les coulisses','Behind the scenes')}</h2></div>${Object.keys(ARTS).map(k=>{const a=ARTS[k];return `<button class="card art" type="button" data-act="article" data-k="${k}"><div class="ah">${articleArt(k==='cmm'?'calibre':'archives')}<span class="bdg k">${tx(a.k)}</span></div><div class="bd"><h3 class="h3">${tx(a.t)}</h3><p>${tx(a.body)[0].slice(0,110)}…</p><span class="link">${a.m} min · ${L('Lire','Read')}${ic('arrow')}</span></div></button>`;}).join('')}
 <button class="card conc" type="button" data-act="concierge"><span class="av">CM</span><span><h3 class="h3">${L('Conciergerie VIP','VIP Concierge')}</h3><p>${L('Rendez-vous privé, conseil sur un modèle, suivi d’entretien.','Private appointment, advice on a model, service follow-up.')}</p><span class="link">${L('Écrire à Claire','Message Claire')}${ic('arrow')}</span></span></button></div>`;
 const evs=`<div class="pad" style="margin-top:16px">${Object.keys(EVENTS).map(k=>{const e=EVENTS[k],b=S.bookings[k],d=new Date(e.date);return `<div class="card ev"><div class="dt"><b>${d.getDate()}</b><small>${fdate(d,{month:'short'}).replace('.','')}</small></div><div class="sp"><h3 class="h3">${tx(e.t)}</h3><p>${tx(e.where)} · ${tx(e.d)}</p>${b?`<span class="bdg">${ic('check')}${L('Réservé','Booked')} · ${b.label}</span>`:`<button class="btn gold sm" type="button" data-act="book" data-e="${k}">${L('Réserver','Reserve')}</button>`}</div></div>`;}).join('')}<p class="small muted center">${L('Événements fictifs, créés pour le prototype.','Fictional events created for the prototype.')}</p></div>`;
 const launch=`<div class="pad" style="margin-top:16px">${pv.map(([id,d])=>{const w=W(id),on=!!S.alerts[id];return `<div class="card" style="padding:12px;margin-bottom:12px"><div class="row" style="align-items:flex-start"><button type="button" data-act="pdp" data-id="${id}" style="width:86px;flex:none">${pic(w,0,{alt:false})}</button><div class="sp"><span class="bdg">${esc(tagOf(w))}</span><h3 class="h3" style="margin-top:8px">${esc(w.n)}</h3><p class="small muted" style="margin:4px 0 0">${d} · ${eur(w.p)}</p></div></div><div class="row" style="justify-content:space-between;border-top:.5px solid rgba(255,255,255,.1);padding-top:10px;margin-top:10px"><span class="small" id="al-${id}">${L('M’alerter des nouveautés','Alert me about news')}</span><button class="tgl" type="button" role="switch" aria-checked="${on}" aria-labelledby="al-${id}" data-act="alertT" data-id="${id}"></button></div></div>`;}).join('')}</div>`;
 return seg+(p.seg==='news'?news:p.seg==='events'?evs:launch);},
 mount:(el,p)=>{if(p.open){const k=p.open;p.open=null;setTimeout(()=>openBooking(k),DUR+60);}}};
A.clubSeg=b=>{const e=top();e.params.seg=b.dataset.k;buzz(4);rerender();$('.sc',e.el).scrollTop=0;};
A.alertT=b=>{const id=b.dataset.id;S.alerts[id]=!S.alerts[id];save();b.setAttribute('aria-checked',S.alerts[id]);buzz(5);};
function bookHTML(k,d){const e=EVENTS[k];if(d.done)return sheetHTML(L('Réservation confirmée','Booking confirmed'),`<div class="center"><div class="okmark"><svg viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21l7 7 15-16"/></svg></div><h3 class="h2">${tx(e.t)}</h3><p class="p">${d.label} · ${d.guests===2?L('2 personnes','2 guests'):L('1 personne','1 guest')}<br>${tx(e.where)}</p></div>`,`<button class="btn ghost" type="button" data-act="ics" data-e="${k}" style="flex:1">${ic('cal')}${L('Calendrier','Calendar')}</button><button class="btn gold" type="button" data-act="closeSheet" style="flex:1">OK</button>`);
 return sheetHTML(L('Réserver','Reserve'),`<p class="p" style="margin-top:0"><b style="color:var(--ink)">${tx(e.t)}</b> · ${tx(e.where)}</p><div class="lbl" style="margin:16px 0 8px">${L('Créneau','Time slot')}</div><div class="slots">${e.slots.map(([id,day,h,full])=>`<button type="button" aria-pressed="${d.slot===id}" data-act="bSlot" data-k="${id}" ${full?'disabled':''}><b>${h}</b><small>${tx(day)}${full?' · '+L('complet','full'):''}</small></button>`).join('')}</div><div class="lbl" style="margin:18px 0 8px">${L('Participants','Guests')}</div><div class="chips"><button class="chip" type="button" aria-pressed="${d.guests===1}" data-act="bGuests" data-k="1">${L('Seul(e)','Just me')}</button><button class="chip" type="button" aria-pressed="${d.guests===2}" data-act="bGuests" data-k="2">${L('+1 invité','+1 guest')}</button></div>`,`<button class="btn gold" type="button" data-act="bConfirm" ${d.slot?'':'disabled'}>${L('Confirmer','Confirm')}</button>`);}
function openBooking(k){if(!needNet())return;const d={k,slot:(S.bookings[k]||{}).slot||null,guests:(S.bookings[k]||{}).guests||1};openSheet({label:L('Réservation','Booking'),data:d,html:bookHTML(k,d)});}
A.book=b=>openBooking(b.dataset.e);
A.bSlot=b=>{const o=topSheet();o.data.slot=b.dataset.k;setSheet(o,bookHTML(o.data.k,o.data));buzz(4);};
A.bGuests=b=>{const o=topSheet();o.data.guests=+b.dataset.k;setSheet(o,bookHTML(o.data.k,o.data));};
A.bConfirm=b=>{if(!needNet())return;const o=topSheet(),d=o.data;b.classList.add('loading');setTimeout(()=>{const s=EVENTS[d.k].slots.find(x=>x[0]===d.slot);d.label=`${tx(s[1])} · ${s[2]}`;S.bookings[d.k]={slot:d.slot,guests:d.guests,label:d.label};save();d.done=true;setSheet(o,bookHTML(d.k,d));buzz([12,40,24]);confetti(.5,.62);if(top().name==='club')rerender();},RM?80:700);};
A.ics=b=>{const e=EVENTS[b.dataset.e],bk=S.bookings[b.dataset.e];const s=e.slots.find(x=>x[0]===bk.slot);dl('yema-evenement.ics',`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Yema Watch Club demo//FR\r\nBEGIN:VEVENT\r\nUID:${Date.now()}@yema-demo\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').slice(0,15)}Z\r\nDTSTART:${e.date.replace(/-/g,'')}T${s[2].replace(':','')}00\r\nDURATION:PT2H\r\nSUMMARY:${tx(e.t)} (démo)\r\nLOCATION:${tx(e.where)}\r\nEND:VEVENT\r\nEND:VCALENDAR`,'text/calendar');toast(L('Ajouté au calendrier (.ics)','Added to calendar (.ics)'),{icon:'cal'});};
A.article=b=>go('article',{k:b.dataset.k});
SCR.article={tabs:false,hero:1,cls:'reader',title:p=>tx(ARTS[p.k].t),short:()=>L('Article','Article'),
 render:p=>{const a=ARTS[p.k];return `<div class="hero">${articleArt(p.k==='cmm'?'calibre':'archives')}</div><div class="body"><span class="lbl g">${tx(a.k)} · ${a.m} min</span><h1 class="h1" style="margin:8px 0 18px">${tx(a.t)}</h1>${tx(a.body).map(x=>x.startsWith('«')||x.startsWith('“')?`<blockquote>${esc(x)}</blockquote>`:`<p>${esc(x)}</p>`).join('')}<div style="width:60%;margin:8px auto 0">${pic(W(a.w),a.i||0,{alt:false})}</div><p class="small muted" style="font-family:var(--sans);font-size:12px">${L('Texte rédigé pour le prototype à partir des informations publiques de YEMA.','Text written for the prototype from public YEMA information.')}</p><button class="btn line" type="button" data-act="pdp" data-id="${a.w}" style="margin-top:10px">${L('Voir la montre','View the watch')}</button></div>`;},
 mount:el=>{el._th=200;}};

/* concierge (scripted chat) */
const CH={await:null};
function slotsNext(){const out=[],hs=['11:00','15:30','17:00'];let add=1;while(out.length<3){const x=new Date(Date.now()+add*D);if(x.getDay()!==0)out.push({id:'s'+out.length,d:iso(x),h:hs[out.length]});add++;}out.push({id:'v',visio:1,h:'18:00',d:iso(Date.now()+D)});return out;}
const slotLbl=s=>`${fdate(s.d,{weekday:'short',day:'numeric',month:'short'})} · ${s.h}${s.visio?' · '+L('visio','video'):''}`;
const lastInterest=()=>{if(LASTPDP)return W(LASTPDP);const x=S.cart[0]||S.wish[0];return x?W(x.wid):W('nme');};
function msgHTML(m){if(m.t==='appt'){const w=m.w?W(m.w):null;return `<div class="msg bot card"><div class="mc"><span class="bdg">${ic('cal')}${L('Rendez-vous confirmé','Appointment confirmed')}</span><h3 class="h3" style="margin:8px 0 4px">${m.visio?L('Rendez-vous en visio','Video appointment'):L('Salon privé · Paris','Private lounge · Paris')}</h3><div class="kv"><span>${L('Quand','When')}</span><b>${esc(m.label)}</b></div>${w?`<div class="kv"><span>${L('Pièce préparée','Piece prepared')}</span><b>${esc(w.n)}</b></div>`:''}</div></div>`;}
 if(m.t==='w'){const w=W(m.w);return `<div class="msg bot card"><button type="button" data-act="pdp" data-id="${w.id}" style="display:flex;gap:10px;align-items:center;padding:10px;text-align:left;width:100%"><span style="width:56px;flex:none">${pic(w,0,{alt:false})}</span><span><b style="display:block">${esc(w.n)}</b><small class="muted">${eur(w.p)} · ${L('voir la fiche','view product')}</small></span></button></div>`;}
 return `<div class="msg ${m.who==='me'?'me':'bot'}">${esc(tx(m.x))}</div>`;}
function chips(){if(CH.await==='slot')return slotsNext().map(s=>['slot:'+s.id,slotLbl(s)]);const c=[['rdv',S.appt?L('Changer mon rendez-vous','Change my appointment'):L('Rendez-vous privé','Private appointment')],['met',L('La Meteorite','The Meteorite')],['svc',L('Entretien de ma montre','Servicing my watch')]];if(S.orders.length)c.push(['ord',L('Ma commande','My order')]);return c;}
SCR.concierge={tabs:false,cls:'chat',solid:1,title:()=>'Claire Mercier',short:()=>L('Conciergerie','Concierge'),
 right:()=>`<button class="nbb" type="button" data-act="callAdv" aria-label="${L('Appeler','Call')}">${ic('phone')}</button>`,
 render:()=>`<div class="advh" style="padding:4px 16px 8px"><span class="av">CM</span><span><b>Claire Mercier</b><small>${OFF?L('Hors ligne','Offline'):L('Conseillère horlogère · en ligne','Watch advisor · online')} · ${L('personnage fictif','fictional character')}</small></span></div><div class="msgs" id="msgs" aria-live="polite">${S.chat.map(msgHTML).join('')}</div><div class="qr" id="qr">${chips().map(([k,l])=>`<button class="chip" type="button" data-act="chip" data-k="${k}">${esc(l)}</button>`).join('')}</div><form class="cin" id="cin"><input id="cmsg" placeholder="${L('Écrire à Claire…','Message Claire…')}" aria-label="${L('Message','Message')}" autocomplete="off"><button class="send" type="submit" aria-label="${L('Envoyer','Send')}">${ic('send')}</button></form>`,
 mount:(el,p,e)=>{const sc=$('.sc',el);setTimeout(()=>{sc.scrollTop=sc.scrollHeight;},20);$('#cin',el).addEventListener('submit',ev=>{ev.preventDefault();const i=$('#cmsg',el),v=i.value.trim();if(!v||!needNet())return;i.value='';say(v);route(v);});
  if(!S.chat.length){CH.await=null;const w=lastInterest();botSay([{fr:`Bonjour ${S.user.first}, je suis Claire, votre conseillère YEMA. Comment puis-je vous aider ?`,en:`Hello ${S.user.first}, I’m Claire, your YEMA advisor. How can I help?`},{fr:`Je vois que la ${w.n} vous intéresse. Souhaitez-vous la découvrir en salon privé ?`,en:`I see you’re interested in the ${w.n}. Would you like to see it in a private lounge?`}]);}}};
function refreshChat(){if(top().name!=='concierge')return;const el=top().el;$('#msgs',el).innerHTML=S.chat.map(msgHTML).join('');$('#qr',el).innerHTML=chips().map(([k,l])=>`<button class="chip" type="button" data-act="chip" data-k="${k}">${esc(l)}</button>`).join('');markImgs(el);const sc=$('.sc',el);requestAnimationFrame(()=>{sc.scrollTop=sc.scrollHeight;});top().ver=VER;}
function say(t){S.chat.push({who:'me',x:t});save();refreshChat();}
function botSay(list){let i=0;const nx=()=>{if(i>=list.length){refreshChat();return;}const m=list[i++];if(top().name==='concierge'){const ms=$('#msgs',top().el);const t=document.createElement('div');t.className='typing';t.innerHTML='<i></i><i></i><i></i>';ms.appendChild(t);const sc=$('.sc',top().el);sc.scrollTop=sc.scrollHeight;}setTimeout(()=>{S.chat.push(m.t?m:{who:'bot',x:m});save();refreshChat();nx();},RM?100:800);};nx();}
A.chip=b=>{if(!needNet())return;say(b.textContent);route(b.dataset.k);};
A.callAdv=()=>toast(L('Appel conciergerie (démo)','Concierge call (demo)'),{icon:'phone'});
function route(k){const low=String(k).toLowerCase();
 if(k.startsWith('slot:')){const s=slotsNext().find(x=>'slot:'+x.id===k);CH.await=null;const w=lastInterest();S.appt={label:slotLbl(s),visio:!!s.visio,w:w.id};S.notifs.unshift({id:'n'+Date.now(),k:'event',ts:Date.now(),read:false,to:['concierge',{}],t:{fr:'Rendez-vous confirmé',en:'Appointment confirmed'},b:{fr:`Salon privé avec Claire · ${slotLbl(s)}`,en:`Private lounge with Claire · ${slotLbl(s)}`}});save();step(4);
  botSay([{t:'appt',who:'bot',label:slotLbl(s),visio:!!s.visio,w:w.id},{fr:`C’est noté. Je préparerai la ${w.n} et d’autres bracelets pour comparer. Vous pouvez aussi la commander directement dans l’app.`,en:`Noted. I’ll prepare the ${w.n} and other straps to compare. You can also order it directly in the app.`}]);setTimeout(()=>{buzz([12,40,24]);confetti(.5,.4);},900);return;}
 if(k==='rdv'||/rdv|rendez|appoint|boutique|salon/.test(low)){CH.await='slot';botSay([{fr:'Avec plaisir. Voici mes prochaines disponibilités :',en:'With pleasure. Here are my next availabilities:'}]);return;}
 if(k==='met'||/meteor/.test(low)){botSay([{fr:'La Navygraf Meteorite CMM.10 est limitée à 150 exemplaires numérotés, chaque cadran taillé dans la météorite Muonionalusta.',en:'The Navygraf Meteorite CMM.10 is limited to 150 numbered pieces, each dial cut from the Muonionalusta meteorite.'},{t:'w',who:'bot',w:'nme'}]);return;}
 if(k==='svc'||/entretien|révision|service/.test(low)){botSay([{fr:'La garantie de votre Superman Heritage se termine bientôt : je peux organiser un contrôle avant son échéance.',en:'Your Superman Heritage warranty ends soon: I can arrange a check-up before it expires.'}]);return;}
 if(k==='ord'){const o=S.orders[0];botSay([{fr:`Votre commande ${o.no} est au statut « ${STAT(o)[o.status].t} ». Vous la suivez depuis Profil › Mes commandes.`,en:`Your order ${o.no} is “${STAT(o)[o.status].t}”. Track it from Profile › My orders.`}]);return;}
 botSay([{fr:'Merci pour votre message, je reviens vers vous rapidement. Souhaitez-vous un rendez-vous ?',en:'Thanks for your message, I’ll get back to you shortly. Would you like an appointment?'}]);}

/* notifications */
const NICON={launch:'crown',service:'wrench',event:'cal',club:'mega',order:'box',price:'trend'};
const NF={all:()=>true,unread:n=>!n.read,orders:n=>n.k==='order',events:n=>n.k==='event'||n.k==='launch'};
SCR.notifs={title:()=>'Notifications',large:1,short:()=>'Notifications',right:()=>`<button class="nbb" type="button" data-act="readAll" aria-label="${L('Tout marquer comme lu','Mark all as read')}" style="width:auto;padding:0 10px;color:var(--gold2);font-weight:700;font-size:14px">${L('Tout lire','Read all')}</button>`,
 render:p=>{p.f=p.f||'all';const list=p.empty?[]:S.notifs.filter(NF[p.f]);const u=unread();
 return `<div class="seg">${[['all',L('Tout','All')],['unread',L('Non lues','Unread')+(u?` · ${u}`:'')],['orders',L('Commandes','Orders')],['events',L('Événements','Events')]].map(([k,l])=>`<button type="button" aria-selected="${p.f===k}" data-act="nFilter" data-k="${k}">${l}</button>`).join('')}</div><div style="margin-top:14px">${list.length?list.map(n=>`<div class="nf ${n.read?'read':''}" data-id="${n.id}"><div class="under">${ic(n.read?'trash':'check')}${n.read?L('Supprimer','Delete'):L('Lu','Read')}</div><button class="body" type="button" data-act="nOpen" data-id="${n.id}"><span class="ni">${ic(NICON[n.k]||'bell')}</span><span class="sp" style="min-width:0"><span class="th"><span class="h3">${esc(tx(n.t))}</span><small class="tm">${ago(n.ts)}</small></span><p>${esc(tx(n.b))}</p></span>${n.read?'':'<span class="ud"></span>'}</button></div>`).join('')+`<p class="small muted center">${L('Glissez vers la gauche pour marquer comme lue.','Swipe left to mark as read.')}</p>`:`<div class="empty">${emptyArt('notif')}<h2 class="h2">${L('Aucune notification','No notifications')}</h2><p>${L('Lancements, commandes et rappels d’entretien apparaîtront ici.','Launches, orders and service reminders will appear here.')}</p></div>`}</div>`;},
 mount:el=>{$$('.nf',el).forEach(n=>{const b=$('.body',n);let x0=null,dx=0,mv=false;b.addEventListener('pointerdown',e=>{x0=e.clientX;dx=0;mv=false;});b.addEventListener('pointermove',e=>{if(x0==null)return;dx=Math.min(0,e.clientX-x0);if(dx<-8){mv=true;b.style.transition='none';b.style.transform=`translateX(${dx}px)`;}});const up=()=>{if(x0==null)return;x0=null;b.style.transition='';if(dx<-80){b.style.transform='translateX(-100%)';setTimeout(()=>swipeN(n.dataset.id),220);}else b.style.transform='';};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('click',e=>{if(mv){e.stopPropagation();e.preventDefault();mv=false;}},true);});}};
function swipeN(id){const n=S.notifs.find(x=>x.id===id);if(!n)return;if(!n.read){n.read=true;save();rerender();}else{const i=S.notifs.indexOf(n);S.notifs.splice(i,1);save();rerender();toast(L('Supprimée','Deleted'),{icon:'trash',act:{label:L('Annuler','Undo'),fn:()=>{S.notifs.splice(i,0,n);save();rerender();}}});}buzz(6);}
A.notifs=()=>go('notifs');
A.nFilter=b=>{const p=top().params;p.f=b.dataset.k;p.empty=false;rerender();};
A.readAll=()=>{S.notifs.forEach(n=>n.read=true);save();rerender();};
A.nOpen=b=>{const n=S.notifs.find(x=>x.id===b.dataset.id);if(!n)return;n.read=true;save();badges();if(n.id==='n1')step(0);const [s,pp]=n.to||[];if(s==='club'){switchTab('club',pp);return;}if(s==='watch'&&!S.owned.find(o=>o.oid===pp.oid)){toast(L('Montre introuvable','Watch not found'),{icon:'info'});return;}if(s)go(s,pp);};
