
/* ================= Profil (#15), security (#16), GDPR (#17), about ================= */
const li=(i,a,t,v,x)=>`<button class="li" type="button" data-act="${a}"${x||''}>${ic(i)}<span class="tx">${t}</span>${v?`<span class="v">${v}</span>`:''}${ic('chev','chev')}</button>`;
SCR.profile={large:1,title:()=>L('Profil','Profile'),
 render:()=>`<div class="prof"><div class="avatar"><div>${esc(S.user.first[0]+S.user.last[0])}</div></div><div style="min-width:0"><h2 class="h2">${esc(S.user.first+' '+S.user.last)}</h2><div class="muted small">${esc(S.user.email)}</div><span class="bdg vip">${ic('crown')}${L('Membre VIP Platine','Platinum VIP member')}</span></div></div>
 <div class="grp"><div class="list">${li('box','orders',L('Mes commandes','My orders'),S.orders.length||'')}${li('heart','toWish',L('Liste d’envies','Wishlist'),S.wish.length||'')}</div></div>
 <div class="grp"><span class="lbl">${L('Compte','Account')}</span><div class="list">${li('user','toInfo',L('Informations personnelles','Personal information'))}${li('pin','toAddr',L('Adresses','Addresses'))}${li('card','toPay',L('Moyens de paiement','Payment methods'))}</div></div>
 <div class="grp"><span class="lbl">${L('Préférences','Preferences')}</span><div class="list">${li('bell','toNP',L('Notifications','Notifications'))}${li('globe','langSheet',L('Langue','Language'),LANG==='fr'?'Français':'English')}${li('watch','editPrefs',L('Goûts & poignet','Taste & wrist'),S.prefs.cm+' cm')}${li('pin','stores',L('Boutiques','Boutiques'))}</div></div>
 <div class="grp"><span class="lbl">${L('Sécurité & confidentialité','Security & privacy')}</span><div class="list">${li('shield','toSec',L('Sécurité (A2F & Face ID)','Security (2FA & Face ID)'))}${li('file','toGdpr',L('Paramètres RGPD','GDPR settings'))}</div></div>
 <div class="grp"><div class="list">${li('info','toAbout',L('À propos du prototype','About this prototype'))}</div></div>
 <div class="grp"><button class="btn ghost" type="button" data-act="logout">${ic('logout')}${L('Se déconnecter','Sign out')}</button></div>`};
A.toWish=()=>switchTab('collection',{tab:'wish'});
A.toInfo=()=>go('info');A.toAddr=()=>go('addresses');A.toPay=()=>go('payments');A.toSec=()=>go('security');A.toGdpr=()=>go('gdpr');A.toNP=()=>go('notifprefs');A.toAbout=()=>go('about');
A.logout=async()=>{const ok=await confirmDlg({title:L('Se déconnecter ?','Sign out?'),text:L('Votre collection reste liée à votre compte.','Your collection stays linked to your account.'),ok:L('Se déconnecter','Sign out')});if(!ok)return;S.onboarded=false;save();stopCam();startFlow('welcome');};
A.langSheet=()=>openSheet({label:L('Langue','Language'),html:sheetHTML(L('Langue','Language'),`<div class="list">${[['fr','Français'],['en','English']].map(([k,n])=>`<button class="li" type="button" role="radio" aria-checked="${LANG===k}" data-act="setLang" data-k="${k}"><span class="tx">${n}</span>${LANG===k?`<span style="color:var(--gold2)">${ic('check')}</span>`:''}</button>`).join('')}</div>`)});
A.setLang=b=>{closeSheet();setLang(b.dataset.k);};
SCR.info={title:()=>L('Informations','Information'),short:()=>L('Infos','Info'),
 render:()=>`<form class="pad" id="pif" novalidate>${[['first',L('Prénom','First name'),'given-name'],['last',L('Nom','Last name'),'family-name'],['email','Email','email'],['phone',L('Téléphone','Phone'),'tel']].map(([k,l,a])=>`<label class="fld"><span>${l}</span><div class="inp" id="pi-${k}w"><input id="pi-${k}" value="${esc(S.user[k])}" autocomplete="${a}"></div><small class="ferr" id="pi-${k}e"></small></label>`).join('')}<button class="btn gold" type="submit" style="margin-top:22px">${L('Enregistrer','Save')}</button></form>`,
 mount:el=>{$('#pif',el).addEventListener('submit',e=>{e.preventDefault();let ok=true;['first','last','email'].forEach(k=>{const v=$('#pi-'+k,el).value.trim();const bad=!v||(k==='email'&&!/^\S+@\S+\.\S+$/.test(v));$('#pi-'+k+'w',el).classList.toggle('err',bad);$('#pi-'+k+'e',el).textContent=bad?(k==='email'&&v?L('Email invalide','Invalid email'):L('Champ requis','Required')):'';if(bad)ok=false;});if(!ok)return;['first','last','email','phone'].forEach(k=>S.user[k]=$('#pi-'+k,el).value.trim());save();toast(L('Informations mises à jour','Information updated'),{icon:'user'});back();});}};
SCR.addresses={title:()=>L('Adresses','Addresses'),
 render:()=>`<div class="pad">${S.addresses.map(a=>`<div class="card" style="padding:14px;margin-bottom:10px"><div class="row"><b class="sp">${esc(tx(a.n))}</b>${a.def?`<span class="bdg">${L('Par défaut','Default')}</span>`:`<button class="link" type="button" data-act="addrDef" data-id="${a.id}">${L('Par défaut','Set default')}</button>`}</div><p class="p">${esc(a.l)}<br>${esc(a.c)}</p></div>`).join('')}<button class="addc" type="button" data-act="addrAdd">${ic('plus')}${L('Ajouter une adresse','Add an address')}</button></div>`};
A.addrDef=b=>{S.addresses.forEach(a=>a.def=a.id===b.dataset.id);save();rerender();};
A.addrAdd=()=>openSheet({label:L('Adresse','Address'),html:sheetHTML(L('Nouvelle adresse','New address'),`<label class="fld"><span>${L('Libellé','Label')}</span><div class="inp"><input id="ad-n" placeholder="${L('Bureau','Office')}"></div></label><label class="fld"><span>${L('Adresse','Address')}</span><div class="inp"><input id="ad-l" autocomplete="street-address"></div></label><label class="fld"><span>${L('Code postal, ville','Postcode, city')}</span><div class="inp"><input id="ad-c"></div></label>`,`<button class="btn gold" type="button" data-act="addrSave">${L('Enregistrer','Save')}</button>`)});
A.addrSave=()=>{const l=$('#ad-l').value.trim();if(!l){toast(L('Saisissez une adresse','Enter an address'),{icon:'info'});return;}S.addresses.push({id:'a'+Date.now(),n:$('#ad-n').value.trim()||L('Adresse','Address'),l,c:$('#ad-c').value.trim()});save();closeSheet();rerender();};
SCR.payments={title:()=>L('Paiement','Payment'),
 render:()=>`<div class="paycard"><div class="row" style="justify-content:space-between"><span class="chipc"></span><span class="serif" style="font-size:20px;letter-spacing:.2em">YEMA</span></div><div style="font-size:18px;letter-spacing:.16em;font-weight:700">•••• •••• •••• 4242</div><div class="row" style="justify-content:space-between;font-size:12px;color:var(--ink2)"><span>${esc((S.user.first+' '+S.user.last).toUpperCase())}</span><span>09/29</span></div></div><div class="grp"><div class="list"><div class="li">${ic('apple')}<span class="tx">Apple Pay<small>${L('Simulé dans cette démo','Simulated in this demo')}</small></span></div></div><div class="simu" style="margin-top:14px">${ic('shield')}${L('Carte fictive : aucune saisie ni aucun débit possible dans le prototype.','Fictional card: no entry and no charge possible in the prototype.')}</div></div>`};
const NPK=[['launch','crown',{fr:'Lancements & éditions limitées',en:'Launches & limited editions'}],['order','box',{fr:'Suivi de commande',en:'Order tracking'}],['event','cal',{fr:'Événements du Club',en:'Club events'}],['service','wrench',{fr:'Entretien & garantie',en:'Service & warranty'}]];
SCR.notifprefs={title:()=>'Notifications',render:()=>{S.np=S.np||{launch:true,order:true,event:true,service:true};return `<div class="grp" style="margin-top:6px"><div class="list">${NPK.map(([k,i,t])=>`<div class="li">${ic(i)}<span class="tx" id="np-${k}">${tx(t)}</span><button class="tgl" type="button" role="switch" aria-checked="${!!S.np[k]}" aria-labelledby="np-${k}" data-act="npT" data-k="${k}"></button></div>`).join('')}</div></div>`;}};
A.npT=b=>{const k=b.dataset.k;S.np[k]=!S.np[k];save();b.setAttribute('aria-checked',S.np[k]);buzz(5);};
SCR.security={title:()=>L('Sécurité','Security'),
 render:()=>{const s=S.sec;return `<div class="grp" style="margin-top:6px"><div class="list"><div class="li">${ic('key')}<span class="tx" id="sc-2">${L('Double authentification','Two-factor authentication')}<small>${L('Code par SMS','SMS code')}</small></span><button class="tgl" type="button" role="switch" aria-checked="${s.twofa}" aria-labelledby="sc-2" data-act="secT" data-k="twofa"></button></div><div class="li">${ic('faceid')}<span class="tx" id="sc-f">Face ID<small>${L('Paiements et partages','Payments and sharing')}</small></span><button class="tgl" type="button" role="switch" aria-checked="${s.faceid}" aria-labelledby="sc-f" data-act="secT" data-k="faceid"></button></div><div class="li">${ic('lock')}<span class="tx" id="sc-b">${L('Face ID à l’ouverture','Face ID on launch')}<small>${L('Verrouille l’app à chaque ouverture','Locks the app on every launch')}</small></span><button class="tgl" type="button" role="switch" aria-checked="${s.bioOpen&&s.faceid}" aria-labelledby="sc-b" data-act="secT" data-k="bioOpen" ${s.faceid?'':'disabled'}></button></div></div><button class="btn line" type="button" data-act="testBio" style="margin-top:14px" ${s.faceid?'':'disabled'}>${ic('faceid')}${L('Tester Face ID','Test Face ID')}</button></div>
 <div class="grp"><span class="lbl">${L('Appareils connectés','Connected devices')}</span><div class="list"><div class="dev">${ic('device')}<div class="x"><b>iPhone</b><small>${L('Cet appareil','This device')}</small></div></div><div class="dev">${ic('tablet')}<div class="x"><b>iPad</b><small>${L('Il y a 3 jours','3 days ago')}</small></div><button class="btn ghost sm" type="button" data-act="devOut">${L('Déconnecter','Sign out')}</button></div></div></div>`;}};
A.secT=b=>{const k=b.dataset.k;S.sec[k]=!S.sec[k];if(k==='faceid'&&!S.sec.faceid)S.sec.bioOpen=false;save();rerender();buzz(5);if(k==='bioOpen'&&S.sec.bioOpen)setTimeout(()=>bioLock(L('Face ID activé à l’ouverture','Face ID on launch enabled')),250);};
A.testBio=()=>bioLock().then(()=>toast(L('Déverrouillé','Unlocked'),{icon:'faceid'}));
A.devOut=b=>{b.closest('.dev').remove();toast(L('Appareil déconnecté','Device signed out'),{icon:'device'});};
SCR.gdpr={title:()=>L('RGPD','GDPR'),short:()=>'RGPD',
 render:()=>{const c=S.consent||{};return `<div class="pad"><p class="p" style="margin-top:0">${L('Consentement granulaire, export et suppression à tout moment.','Granular consent, export and deletion at any time.')}</p><div class="card dk" style="padding:0 14px;margin-top:14px">${consentRows(c,'gTgl')}</div><div class="list" style="margin-top:16px"><button class="li" type="button" data-act="exportData">${ic('download')}<span class="tx">${L('Exporter mes données','Export my data')}<small>${L('Fichier JSON : compte, commandes, collection','JSON file: account, orders, collection')}</small></span>${ic('chev','chev')}</button><button class="li" type="button" data-act="deleteAcc" style="color:var(--err)">${ic('trash')}<span class="tx">${L('Supprimer mon compte','Delete my account')}</span>${ic('chev','chev')}</button></div><p class="small muted" style="margin-top:12px">${L('Dans cette démo, rien ne quitte votre navigateur.','In this demo, nothing leaves your browser.')}</p></div>`;}};
A.gTgl=b=>{S.consent=S.consent||{};const k=b.dataset.k;S.consent[k]=!S.consent[k];save();b.setAttribute('aria-checked',S.consent[k]);buzz(5);};
A.exportData=()=>{const data={exportedAt:new Date().toISOString(),notice:'Yema Watch Club — prototype étudiant, paiement simulé',user:S.user,consent:S.consent,preferences:S.prefs,language:LANG,orders:S.orders.map(o=>({no:o.no,total:o.total,status:STAT(o)[o.status].t,items:o.items.map(i=>({model:W(i.wid).n,options:optLine(W(i.wid),i.o),qty:i.qty}))})),collection:S.owned.map(o=>({model:W(o.wid).n,serial:o.serial,purchaseDate:o.date,warrantyEnd:o.wEnd,service:o.hist.map(h=>({type:tx(h.t),date:h.d}))})),wishlist:S.wish.map(x=>W(x.wid).n),bookings:S.bookings,appointment:S.appt};dl('yema-mes-donnees.json',JSON.stringify(data,null,2),'application/json');toast(L('Export JSON téléchargé','JSON export downloaded'),{icon:'download'});};
A.deleteAcc=async()=>{const ok=await confirmDlg({title:L('Supprimer votre compte ?','Delete your account?'),text:L('Collection, commandes et préférences seront effacées. Action irréversible.','Collection, orders and preferences will be erased. This cannot be undone.'),ok:L('Supprimer','Delete'),danger:true});if(!ok)return;const lg=LANG;stopCam();S=defState();S.lang=lg;save();renderSteps();startFlow('welcome');toast(L('Compte supprimé','Account deleted'),{icon:'trash'});};
SCR.about={title:()=>L('À propos','About'),
 render:()=>`<div class="pad"><div class="row" style="gap:14px;margin-bottom:14px"><img src="icons/icon-192.png" alt="" width="60" height="60" style="border-radius:14px"><div><b class="h3" style="display:block">Yema Watch Club</b><small class="muted">${L('Prototype · v2.0','Prototype · v2.0')}</small></div></div>
 <p class="p">${L('Travail final du cours Mobile Apps (MBA ESG Paris, 2026). El Mokhtar Berrada : Product Owner, UX/UI designer et chef de projet.','Final project for the Mobile Apps course (MBA ESG Paris, 2026). El Mokhtar Berrada: Product Owner, UX/UI designer and project manager.')}</p>
 <div class="list" style="margin-top:16px"><a class="li" href="${LANG==='en'?'../en/#projets':'../#projets'}" style="text-decoration:none">${ic('arrowl')}<span class="tx">${L('Retour au CV d’El Mokhtar','Back to El Mokhtar’s CV')}</span>${ic('chev','chev')}</a>${li('globe','langToggle',L('Language : English','Langue : Français'))}${li('sparkle','openPanel',L('Parcours guidé & index des écrans','Guided tour & screen index'))}${STANDALONE?'':li('download','installHelp',L('Installer l’app sur l’écran d’accueil','Install the app on your home screen'))}${li('reset','restartApp',L('Recommencer la démo','Restart the demo'))}</div>
 <p class="small muted" style="margin-top:16px">${L('Photos produits © YEMA, utilisées à titre illustratif. Projet étudiant non affilié à YEMA, paiement simulé. Événements, conseillère et adresses sont fictifs.','Product photos © YEMA, used for illustration. Student project not affiliated with YEMA, simulated payment. Events, advisor and addresses are fictional.')}</p></div>`};
A.langToggle=()=>setLang(LANG==='fr'?'en':'fr');
A.openPanel=()=>{const p=$('#panel');p.classList.add('open');setTimeout(()=>$('#pclose').focus(),60);};
A.restartApp=()=>restart();
/* install as an app (iOS: Share › Add to Home Screen; Android: native prompt) */
let DEFER=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();DEFER=e;});
const IOS=/iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
function installHTML(){return sheetHTML(L('Installer l’app','Install the app'),`<div class="row" style="gap:14px"><img src="icons/icon-192.png" alt="" width="58" height="58" style="border-radius:14px"><p class="p" style="margin:0">${L('Ajoutez Yema Club à votre écran d’accueil : plein écran, comme une vraie app.','Add Yema Club to your home screen: full screen, like a real app.')}</p></div>${DEFER?'':`<ol class="p" style="padding-left:20px;margin-top:14px"><li>${L('Touchez','Tap')} <b style="display:inline-flex;vertical-align:middle">${ic('share')}</b> ${L('Partager','Share')}</li><li>${L('Choisissez « Sur l’écran d’accueil »','Choose “Add to Home Screen”')}</li></ol>`}`,DEFER?`<button class="btn ghost" type="button" data-act="closeSheet" style="flex:0 0 36%">${L('Plus tard','Later')}</button><button class="btn gold" type="button" data-act="doInstall">${L('Installer','Install')}</button>`:`<button class="btn gold" type="button" data-act="closeSheet">${L('Compris','Got it')}</button>`);}
A.installHelp=()=>openSheet({label:L('Installer','Install'),html:installHTML()});
A.doInstall=async()=>{if(!DEFER)return;closeSheet();DEFER.prompt();try{await DEFER.userChoice;}catch(e){}DEFER=null;};
function maybeInstall(){if(STANDALONE||NOSAVE||!IS_PHONE()||lsGet('yema-install'))return;setTimeout(()=>{if(sheets.length||NAV.mode!=='tabs'||top().name!=='home'||lsGet('yema-install'))return;lsSet('yema-install','1');openSheet({label:L('Installer','Install'),html:installHTML()});},9000);}

/* offline simulation (#18) */
function setOffline(v){OFF=!!v;app.classList.toggle('offline',OFF);$('#offbar').innerHTML=`${ic('wifioff')}${L('Hors connexion · Ma Collection reste disponible · Réessayer','Offline · My Collection still available · Retry')}`;VER++;const e=top();if(e&&e.name!=='ar'&&e.name!=='camera')build(e);}
$('#offbar').addEventListener('click',()=>{setOffline(false);toast(L('De retour en ligne','Back online'),{icon:'check'});});
