
/* ================= AR: camera permission (#10), try-on (#9), customisation (#20) ================= */
function startAR(id,o){o=o||{};if(CAM.granted)go('ar',{id,live:true,cfg:o.cfg,custom:o.custom});else go('camera',{id,cfg:o.cfg,custom:o.custom,state:'ask'});}
function getCam(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)return Promise.reject({name:'NotSupportedError'});let late=false;const gp=navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});gp.then(s=>{if(late)s.getTracks().forEach(t=>t.stop());},()=>{});return Promise.race([gp,new Promise((_,rej)=>setTimeout(()=>{late=true;rej({name:'TimeoutError'});},20000))]);}
function stopCam(){if(CAM.stream){CAM.stream.getTracks().forEach(t=>t.stop());CAM.stream=null;}}
SCR.camera={tabs:false,modal:true,cls:'perm',title:()=>L('Accès caméra','Camera access'),
 render:p=>{const w=W(p.id);const hdr=`<div class="hdr" style="background:none"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t"><span class="rapill" style="background:rgba(255,255,255,.04)">${L('Essayage RA','AR Try-On')}</span></span><span class="spacer"></span></div>`;
 if(p.state==='denied'){const nf=p.err==='NotFoundError'||p.err==='OverconstrainedError';const ns=p.err==='NotSupportedError';
  return `${hdr}<div class="pc" role="alert"><div class="ico">${ic('camoff')}</div><h1 class="h2">${L('Accès refusé','Access Denied')}</h1><p>${nf?L('Aucune caméra n’a été détectée sur cet appareil. Le mode démo vous permet d’essayer la montre sur un poignet illustré.','No camera was found on this device. Demo mode lets you try the watch on an illustrated wrist.'):ns?L('Ce navigateur ne permet pas l’accès à la caméra. Essayez le mode démo.','This browser does not allow camera access. Try demo mode.'):L('Pour essayer nos montres en réalité augmentée, autorisez l’accès à la caméra dans les réglages de votre appareil.','To experience our watches in augmented reality, please allow camera access in your device settings.')}</p><button class="btn gold" type="button" data-act="openSettings">${ic('gear')}${L('Ouvrir les réglages','Open settings')}</button><button class="btn line" type="button" data-act="demoAR">${L('Essayer le mode démo','Try demo mode')}</button></div><button class="back" type="button" data-act="back">${ic('arrowl')}${L('Retour au produit','Back to product')}</button>`;}
 return `${hdr}<div class="pc"><div class="ico">${ic('camera')}</div><h1 class="h2">${L('Essayez-la à votre poignet','Try it on your wrist')}</h1><p>${L(`Yema Watch Club utilise votre caméra pour afficher la ${esc(tx(w.name))} en réalité augmentée.`,`Yema Watch Club uses your camera to show the ${esc(tx(w.name))} in augmented reality.`)}</p><ul><li>${ic('lock')}${L('L’image reste sur votre appareil, rien n’est enregistré sans votre accord.','The image stays on your device; nothing is saved without your consent.')}</li><li>${ic('ruler')}${L(`Taille calibrée sur votre profil de poignet (${esc(S.prefs.wrist||'16-18')} cm).`,`Size calibrated to your wrist profile (${esc(S.prefs.wrist||'16-18')} cm).`)}</li><li>${ic('hand')}${L('Glissez, pincez et faites pivoter la montre à l’écran.','Drag, pinch and rotate the watch on screen.')}</li></ul><button class="btn gold ${p.state==='wait'?'loading':''}" type="button" data-act="askCam" ${p.state==='wait'?'disabled':''}>${ic('camera')}${L('Autoriser la caméra','Allow camera')}</button><button class="btn line" type="button" data-act="demoAR">${L('Mode démo (sans caméra)','Demo mode (no camera)')}</button></div><button class="back" type="button" data-act="back">${ic('arrowl')}${L('Retour au produit','Back to product')}</button>`;}};
A.askCam=()=>{const p=curEntry.params,e=curEntry;p.state='wait';rerender();getCam().then(s=>{CAM.stream=s;CAM.granted=true;if(curEntry!==e){stopCam();return;}replace('ar',{id:p.id,live:true,cfg:p.cfg,custom:p.custom},'fade');}).catch(err=>{if(curEntry!==e)return;p.state='denied';p.err=err&&err.name;rerender();});};
A.openSettings=()=>toast(L('Sur téléphone : Réglages › Yema Watch Club › Caméra. Dans ce navigateur : icône cadenas de la barre d’adresse.','On a phone: Settings › Yema Watch Club › Camera. In this browser: the padlock icon in the address bar.'),{icon:'gear',ms:5200});
A.demoAR=()=>{const p=curEntry.params;replace('ar',{id:p.id,live:false,cfg:p.cfg,custom:p.custom},'fade');};

const AR={id:'sh',cfg:null,scale:1,rot:0,x:0,y:0};
SCR.ar={tabs:false,modal:true,clear:1,cls:'ar noscroll',title:()=>L('Essayage en réalité augmentée','AR try-on'),
 render:p=>{const w=W(p.id);return `<div class="arstage" style="position:absolute;inset:0;transition:transform .45s var(--ease)"><div class="bgl">${p.live?'<video playsinline muted autoplay></video>':wristScene()}</div><div class="frame"><span class="ring"></span><span class="scanl"></span><i></i><i></i><i></i><i></i></div><div class="guide" id="guide">${L('Aligner le poignet dans le cadre','Align your wrist in the frame')}</div><div class="wov hide" id="wov" role="img" aria-label="${esc(tx(w.name))}"></div></div>
 <div class="top"><button class="ibtn" type="button" data-act="back" aria-label="${L('Quitter l’essayage','Exit try-on')}">${ic('back')}</button><span class="rapill ${p.live?'live':''}"><i></i>${p.live?L('RA active','AR active'):L('RA · mode démo','AR · demo mode')}</span><button class="ibtn" type="button" data-act="arInfo" aria-label="${L('Aide','Help')}">${ic('info')}</button></div>
 <div class="rail"><button class="ibtn" type="button" data-act="arZoom" data-d="1" aria-label="${L('Agrandir','Enlarge')}">${ic('zin')}</button><button class="ibtn" type="button" data-act="arZoom" data-d="-1" aria-label="${L('Réduire','Reduce')}">${ic('zout')}</button><button class="ibtn" type="button" data-act="arRot" aria-label="${L('Faire pivoter','Rotate')}">${ic('rotate')}</button><button class="ibtn" type="button" data-act="arWrist" aria-label="${L('Mon poignet','My wrist')}">${ic('ruler')}</button><button class="ibtn" type="button" data-act="arModels" aria-label="${L('Changer de modèle','Change model')}">${ic('layers')}</button></div>
 <button class="custbtn" type="button" data-act="arCustom">${ic('sliders')}${L('Personnaliser en RA','Customize in AR')}</button>
 <div class="arbot"><button class="q" type="button" data-act="back">${L('Quitter','Exit')}</button><button class="shutter" type="button" data-act="snap" aria-label="${L('Prendre une capture','Take a snapshot')}"></button><button class="thumb" type="button" data-act="arModels" aria-label="${L('Modèle','Model')}" id="arthumb"></button></div><div class="flash" id="flash"></div>`;},
 mount:(el,p,e)=>{
  const w=W(p.id);AR.id=p.id;AR.cfg=Object.assign({dial:w.dial,case:w.case,strap:w.strap},p.cfg||{});AR.scale=1;AR.rot=0;AR.x=0;AR.y=0;
  arDraw(el);
  const v=$('video',el);
  if(p.live&&v){const attach=s=>{v.srcObject=s;const pl=v.play();if(pl&&pl.catch)pl.catch(()=>{});};if(CAM.stream)attach(CAM.stream);else getCam().then(s=>{if(curEntry!==e){s.getTracks().forEach(t=>t.stop());return;}CAM.stream=s;attach(s);}).catch(()=>{if(curEntry!==e)return;toast(L('Caméra indisponible : passage en mode démo','Camera unavailable: switching to demo mode'),{icon:'camoff'});e.params.live=false;rerender();});}
  const g=$('#guide',el),fr=$('.frame',el),wov=$('#wov',el);
  setTimeout(()=>{if(curEntry!==e)return;fr.classList.add('lock');g.classList.add('ok');g.textContent=L('Poignet détecté · montre ancrée','Wrist detected · watch anchored');wov.classList.remove('hide');wov.classList.add('show');buzz([12,40,24]);setTimeout(()=>{if(g)g.style.opacity='0';},2600);if(p.id==='sh')step(2);},RM?200:1400);
  // gestures
  const pts=new Map();let st=null;
  const snapshot=()=>{const a=[...pts.values()];if(a.length===1)return{x:a[0].x,y:a[0].y,ax:AR.x,ay:AR.y};const [p1,p2]=a;return{d:Math.hypot(p2.x-p1.x,p2.y-p1.y),an:Math.atan2(p2.y-p1.y,p2.x-p1.x),sc:AR.scale,rot:AR.rot,cx:(p1.x+p2.x)/2,cy:(p1.y+p2.y)/2,ax:AR.x,ay:AR.y};};
  wov.addEventListener('pointerdown',ev=>{wov.setPointerCapture(ev.pointerId);pts.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});st=snapshot();});
  wov.addEventListener('pointermove',ev=>{if(!pts.has(ev.pointerId))return;pts.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});const a=[...pts.values()];if(a.length===1&&st&&st.x!=null){AR.x=st.ax+a[0].x-st.x;AR.y=st.ay+a[0].y-st.y;}else if(a.length>=2&&st&&st.d){const d=Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y),an=Math.atan2(a[1].y-a[0].y,a[1].x-a[0].x);AR.scale=Math.min(1.8,Math.max(.6,st.sc*d/st.d));AR.rot=st.rot+(an-st.an)*180/Math.PI;}arPos(el);});
  const end=ev=>{pts.delete(ev.pointerId);st=pts.size?snapshot():null;};
  wov.addEventListener('pointerup',end);wov.addEventListener('pointercancel',end);
  wov.addEventListener('wheel',ev=>{ev.preventDefault();AR.scale=Math.min(1.8,Math.max(.6,AR.scale*(ev.deltaY<0?1.06:.94)));arPos(el);},{passive:false});
  if(p.custom)setTimeout(()=>{if(curEntry===e)openCustom();},RM?100:900);
 },
 unmount:()=>{stopCam();}};
function arPos(el){const wov=$('#wov',el||curEl);if(wov)wov.style.transform=`translate(calc(-50% + ${AR.x}px),calc(-50% + ${AR.y}px)) rotate(${AR.rot}deg) scale(${AR.scale})`;}
function arDraw(el){el=el||curEl;const w=W(AR.id);const wov=$('#wov',el);if(!wov)return;const base=arBase(w);wov.style.width=base+'px';wov.innerHTML=wsvg(w,AR.cfg,{wrap:true,memo:false});arPos(el);const th=$('#arthumb',el);if(th)th.innerHTML=wsvg(w,AR.cfg);}
A.arZoom=b=>{AR.scale=Math.min(1.8,Math.max(.6,AR.scale+(+b.dataset.d)*.08));arPos();buzz();};
A.arRot=()=>{AR.rot=(Math.round(AR.rot/15)*15+15);if(AR.rot>45)AR.rot=-45;arPos();buzz();};
A.arInfo=()=>openSheet({label:L('Aide','Help'),html:sheetHTML(L('Conseils d’essayage','Try-on tips'),`<div class="list">${[['move',L('Glissez la montre pour l’ajuster sur votre poignet.','Drag the watch to position it on your wrist.')],['zin',L('Pincez ou utilisez +/− pour régler la taille.','Pinch or use +/− to adjust the size.')],['rotate',L('Deux doigts pour pivoter, ou le bouton de rotation.','Two fingers to rotate, or the rotate button.')],['ruler',L(`Profil de poignet : ${S.prefs.wrist||'16-18'} cm (modifiable dans Profil).`,`Wrist profile: ${S.prefs.wrist||'16-18'} cm (editable in Profile).`)],['camera',curEntry&&curEntry.params.live?L('Caméra active : l’image n’est jamais envoyée.','Camera on: the image is never uploaded.'):L('Mode démo : poignet illustré, aucune caméra utilisée.','Demo mode: illustrated wrist, no camera used.')]].map(([i,t])=>`<div class="li">${ic(i)}<span class="tx" style="font-weight:500;font-size:13.5px">${t}</span></div>`).join('')}</div>`)});
A.arModels=()=>{openSheet({label:L('Modèles','Models'),html:sheetHTML(L('Changer de modèle','Change model'),`<div class="hscroll" style="padding:0 0 6px">${WATCHES.map(w=>`<button class="colc" type="button" aria-pressed="${w.id===AR.id}" data-act="arPick" data-id="${w.id}"><span class="ck">${ic('check')}</span><span class="wimg" style="display:grid">${lw(w)}</span><b style="text-transform:none;letter-spacing:0;font-size:12.5px">${esc(tx(w.name))}</b></button>`).join('')}</div>`)});};
A.arPick=b=>{const w=W(b.dataset.id);AR.id=w.id;AR.cfg={dial:w.dial,case:w.case,strap:w.strap};curEntry.params.id=w.id;curEntry.params.cfg=null;arDraw();closeSheet();toast(tx(w.name),{icon:'watch'});};
const CUSTD=['navy','anthracite','sage','black','glacier','cream'];
function custHTML(){const w=W(AR.id),c=AR.cfg;return `<div class="sh-h" style="flex-direction:column;align-items:stretch;padding-bottom:4px"><div class="row"><span class="spacer" style="width:34px"></span><div class="sp center"><h2 class="h2">${esc(tx(w.name))}</h2><div class="lbl" style="margin-top:4px">${L('Configurez votre style','Configure your style')}</div></div><button class="xbtn" type="button" data-act="closeSheet" aria-label="${L('Fermer','Close')}">${ic('close')}</button></div></div><div class="sh-b">
 <div class="cfgh"><h3 class="h3">${L('Couleur du cadran','Dial colour')}</h3><small>${tx(DIALS[c.dial])}</small></div><div class="swatches" role="radiogroup" aria-label="${L('Couleur du cadran','Dial colour')}">${CUSTD.map(k=>`<button class="sw" type="button" role="radio" aria-checked="${c.dial===k}" aria-pressed="${c.dial===k}" data-act="cSet" data-g="dial" data-k="${k}"><i style="background:radial-gradient(circle at 35% 30%,${DIALS[k].hi},${DIALS[k].c} 55%,${DIALS[k].c2})"></i>${tx(DIALS[k])}</button>`).join('')}</div>
 <div class="cfgh"><h3 class="h3">${L('Finition du boîtier','Case finish')}</h3><small>${tx(CASES[c.case])}</small></div><div class="optl">${Object.keys(CASES).map(k=>`<button type="button" aria-pressed="${c.case===k}" data-act="cSet" data-g="case" data-k="${k}"><span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:${CASES[k].sw};vertical-align:-1px;margin-right:8px"></span>${tx(CASES[k])}${CASES[k].p?` <small style="color:#9A8A6A">+${eur(CASES[k].p)}</small>`:''}</button>`).join('')}</div>
 <div class="cfgh"><h3 class="h3">${L('Bracelet','Strap')}</h3><small>${tx(STRAPS[c.strap])}</small></div><div class="optl">${Object.keys(STRAPS).map(k=>`<button type="button" aria-pressed="${c.strap===k}" data-act="cSet" data-g="strap" data-k="${k}">${tx(STRAPS[k])}</button>`).join('')}</div>
 <div class="row" style="justify-content:space-between;margin-top:20px;padding-top:14px;border-top:1px solid var(--ivline)"><span class="lbl">${L('Prix configuré','Configured price')}</span><b style="font-size:19px" id="cprice">${eur(priceOf(w,c))}</b></div></div>
 <div class="sh-f"><button class="btn line pill" type="button" data-act="cReset" style="flex:0 0 auto;width:auto;color:#9A7A3A;border-color:#E3D6BC">${L('Réinitialiser','Reset')}</button><button class="btn gold pill" type="button" data-act="cSave">${ic('heart')}${L('Ajouter aux souhaits','Add to wishlist')}</button></div>`;}
function openCustom(){const el=curEl;if(!el||curEntry.name!=='ar')return;el.classList.add('cust');el.querySelector('.arstage').style.transform='translateY(-17%)';$$('.custbtn,.rail,.arbot,.top .rapill',el).forEach(n=>n.style.opacity='0');openSheet({light:true,clear:true,max:'60%',label:L('Personnalisation','Customisation'),html:custHTML(),onClose:()=>{if(curEntry&&curEntry.name==='ar'&&curEl===el){el.classList.remove('cust');el.querySelector('.arstage').style.transform='';$$('.custbtn,.rail,.arbot,.top .rapill',el).forEach(n=>n.style.opacity='');}}});}
A.arCustom=()=>openCustom();
A.cSet=b=>{AR.cfg[b.dataset.g]=b.dataset.k;arDraw();setSheet(topSheet(),custHTML());buzz();if(AR.id==='sh'&&AR.cfg.dial==='navy'&&AR.cfg.strap==='leather')step(3);};
A.cReset=()=>{const w=W(AR.id);AR.cfg={dial:w.dial,case:w.case,strap:w.strap};arDraw();setSheet(topSheet(),custHTML());};
A.cSave=()=>{addWish(AR.id,AR.cfg);closeSheet();toast(L('Configuration enregistrée dans vos souhaits','Configuration saved to your wishlist'),{icon:'heartf',act:{label:L('Voir','View'),fn:()=>{switchTab('collection',{tab:'wish'});}}});if(AR.id==='sh'&&AR.cfg.dial==='navy'&&AR.cfg.strap==='leather')step(3);};
/* snapshot */
function svgImg(svg,w,h){return new Promise((res,rej)=>{const s=svg.replace('<svg ',`<svg width="${w}" height="${h}" `);const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s);});}
function cover(ctx,img,iw,ih,cw,ch){const s=Math.max(cw/iw,ch/ih);const w=iw*s,h=ih*s;ctx.drawImage(img,(cw-w)/2,(ch-h)/2,w,h);}
async function compose(el){const r=el.getBoundingClientRect();const dpr=Math.min(2,window.devicePixelRatio||1);const cw=Math.round(r.width*dpr),ch=Math.round(r.height*dpr);const cv=document.createElement('canvas');cv.width=cw;cv.height=ch;const ctx=cv.getContext('2d');
 const v=$('video',el);if(v&&v.videoWidth)cover(ctx,v,v.videoWidth,v.videoHeight,cw,ch);else{const bg=await svgImg(wristScene(),780,1400);cover(ctx,bg,780,1400,cw,ch);}
 const wov=$('#wov',el);const ww=wov.offsetWidth,wh=wov.offsetHeight;const im=await svgImg(wsvg(W(AR.id),AR.cfg,{wrap:true,memo:false}),ww*2,wh*2);
 ctx.save();ctx.translate((r.width/2+AR.x)*dpr,(r.height*.44+AR.y)*dpr);ctx.rotate(AR.rot*Math.PI/180);ctx.scale(AR.scale,AR.scale);ctx.shadowColor='rgba(0,0,0,.5)';ctx.shadowBlur=24*dpr;ctx.shadowOffsetY=14*dpr;ctx.drawImage(im,-ww/2*dpr,-wh/2*dpr,ww*dpr,wh*dpr);ctx.restore();
 const g=ctx.createLinearGradient(0,ch*.8,0,ch);g.addColorStop(0,'rgba(8,14,24,0)');g.addColorStop(1,'rgba(8,14,24,.85)');ctx.fillStyle=g;ctx.fillRect(0,ch*.8,cw,ch*.2);
 ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=`500 ${22*dpr}px "Playfair Display",Georgia,serif`;ctx.fillText('Y E M A',cw/2,ch-58*dpr);ctx.fillStyle='#D4B36F';ctx.font=`700 ${10*dpr}px Manrope,Arial,sans-serif`;ctx.fillText((tx(W(AR.id).name)+' · '+L('ESSAYAGE VIRTUEL','VIRTUAL TRY-ON')).toUpperCase(),cw/2,ch-36*dpr);
 return cv.toDataURL('image/jpeg',.9);}
A.snap=async()=>{const el=curEl;const f=$('#flash',el);f.classList.remove('go');void f.offsetWidth;f.classList.add('go');buzz();let url;try{url=await compose(el);}catch(e){toast(L('Capture impossible sur ce navigateur','Snapshot not supported in this browser'),{icon:'camoff'});return;}
 const w=W(AR.id),cfg=Object.assign({},AR.cfg),id=AR.id;
 openSheet({label:L('Capture','Snapshot'),html:sheetHTML(L('Votre essayage','Your try-on'),`<img src="${url}" alt="${L('Capture de l’essayage','Try-on snapshot')}" style="display:block;width:100%;height:52vh;max-height:470px;object-fit:contain;background:#0A1321;border-radius:14px;border:1px solid var(--line)"><p class="p small center" style="margin-top:10px">${esc(tx(w.name))} · ${esc(cfgLine(cfg))}</p>`,`<div style="display:flex;flex-wrap:wrap;gap:10px;width:100%"><button class="btn gold" type="button" data-act="snapWish" style="flex:1 1 100%">${ic('heart')}${L('Ajouter aux souhaits','Add to wishlist')}</button><button class="btn ghost sm" type="button" data-act="snapShare" style="flex:1">${ic('share')}${L('Partager','Share')}</button><button class="btn ghost sm" type="button" data-act="snapSave" style="flex:1">${ic('download')}${L('Enregistrer','Save')}</button></div>`),data:{url,id,cfg}});};
A.snapSave=()=>{const d=topSheet().data;const a=document.createElement('a');a.href=d.url;a.download=`yema-essayage-${d.id}.jpg`;document.body.appendChild(a);a.click();a.remove();toast(L('Image enregistrée','Image saved'),{icon:'download'});};
A.snapShare=async()=>{const d=topSheet().data;try{const blob=await (await fetch(d.url)).blob();const file=new File([blob],`yema-${d.id}.jpg`,{type:'image/jpeg'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'Yema Watch Club'});return;}}catch(e){if(e&&e.name==='AbortError')return;}A.snapSave();toast(L('Partage direct indisponible ici : image téléchargée','Direct sharing unavailable here: image downloaded'),{icon:'share'});};
A.snapWish=()=>{const d=topSheet().data;addWish(d.id,d.cfg);closeSheet();toast(L('Ajouté à vos souhaits avec cette configuration','Added to your wishlist with this configuration'),{icon:'heartf'});};

/* ================= collection (#11) ================= */
const warrantyOk=o=>new Date(o.wEnd)>new Date();
function yearsLeft(o){const m=Math.round((new Date(o.wEnd)-new Date())/(30.4*D));if(m<=0)return L('expirée','expired');if(m<12)return L(`${m} mois restants`,`${m} months left`);const y=Math.floor(m/12);return L(`${y} an${y>1?'s':''} restant${y>1?'s':''}`,`${y} year${y>1?'s':''} left`);}
function ownedCfg(o){return Object.assign({},o.cfg,o.bezel?{bezel:o.bezel}:{});}
SCR.collection={title:()=>L('Ma Collection','My Collection'),
 render:p=>{p.tab=p.tab||'owned';const q=(p.q||'').toLowerCase();const m=w=>!q||tx(w.name).toLowerCase().includes(q)||COLS[w.col].n.toLowerCase().includes(q);
 const own=S.owned.filter(o=>m(W(o.wid))),wish=p.emptyPreview?[]:S.wish.filter(x=>m(W(x.wid)));
 const body=p.tab==='owned'?(own.map((o,i)=>{const w=W(o.wid);return `<div class="card oc" style="animation:cardIn .45s ${i*60}ms var(--ease) both"><div class="tp"><button class="im" type="button" data-act="watch" data-oid="${o.oid}" aria-label="${esc(tx(w.name))}"><span class="wimg">${lw(w,ownedCfg(o),{view:'crop'})}</span><span class="live"></span></button><div class="sp"><button type="button" data-act="watch" data-oid="${o.oid}" style="text-align:left"><h2 class="h3">${esc(tx(w.name))}</h2><div class="ref">RÉF. ${o.ref}</div></button><div class="ln">${ic('cal')}${L('Acquise','Acquired')} : ${fmon(o.date)}</div><div class="ln ${warrantyOk(o)?'g':''}">${ic('shield')}${warrantyOk(o)?L('Garantie active','Warranty active'):L('Garantie expirée','Warranty expired')} (${yearsLeft(o)})</div></div></div><div class="ft"><button class="link" type="button" data-act="watchHist" data-oid="${o.oid}" style="color:var(--ink2)">${L('Voir l’historique','View history')}</button><button class="btn line sm pill" type="button" data-act="manage" data-oid="${o.oid}">${L('Gérer','Manage')}</button></div></div>`;}).join('')||`<div class="empty">${emptyArt('watch')}<h2 class="h2">${L('Aucune montre trouvée','No watch found')}</h2></div>`)+`<button class="addc" type="button" data-act="addWatch">${ic('plus')}${L('Enregistrer une montre','Register a watch')}</button>`
 :(wish.length?wish.map((x,i)=>{const w=W(x.wid);return `<div class="card wl" style="animation:cardIn .45s ${i*60}ms var(--ease) both"><button class="im" type="button" data-act="wishOpen" data-i="${S.wish.indexOf(x)}" aria-label="${esc(tx(w.name))}"><span class="wimg">${lw(w,x.cfg,{view:'crop'})}</span></button><div class="sp" style="min-width:0"><span class="lbl">${COLS[w.col].n}${x.cfg?' · '+L('Configurée','Configured'):''}</span><h2 class="h3" style="margin-top:3px">${esc(tx(w.name))}</h2><div class="cfg">${x.cfg?esc(cfgLine(x.cfg)):esc(tx(DIALS[w.dial])+' · '+w.size+' mm')}</div><div class="pr">${eur(x.cfg?priceOf(w,x.cfg):effPrice(w))}</div><div class="acts"><button class="btn line sm pill" type="button" data-act="wishAR" data-i="${S.wish.indexOf(x)}">${ic('ar')}${L('Essayer','Try on')}</button><button class="btn ghost sm pill net" type="button" data-act="concierge">${ic('chat')}</button><button class="btn ghost sm pill" type="button" data-act="wishDel" data-i="${S.wish.indexOf(x)}" aria-label="${L('Retirer','Remove')}">${ic('trash')}</button></div></div></div>`;}).join(''):`<div class="empty">${emptyArt('wish')}<h2 class="h2">${q?L('Aucun résultat','No results'):L('Votre liste est vide','Your wishlist is empty')}</h2><p>${L('Touchez le cœur d’une montre, ou enregistrez une configuration depuis l’essayage AR, pour la retrouver ici.','Tap the heart on a watch, or save a configuration from the AR try-on, to find it here.')}</p><button class="btn gold sm pill" type="button" data-act="goCat">${L('Explorer le catalogue','Explore the catalogue')}</button></div>`);
 return `<div class="hdr"><span class="spacer"></span><span class="t">${L('Ma Collection','My Collection')}</span><button class="ibtn nb ${p.search?'on':''}" type="button" data-act="collSearch" aria-label="${L('Rechercher','Search')}">${ic('search')}</button></div>
 <div class="seg" role="tablist" style="justify-content:center;gap:26px"><button type="button" role="tab" aria-selected="${p.tab==='owned'}" data-act="collTab" data-k="owned">${L('Possédées','Owned')} (${S.owned.length})</button><button type="button" role="tab" aria-selected="${p.tab==='wish'}" data-act="collTab" data-k="wish">${L('Liste de souhaits','Wishlist')} (${p.emptyPreview?0:S.wish.length})</button></div>
 ${p.search?`<div class="srch" style="margin-top:14px">${ic('search')}<input id="colq" type="search" value="${esc(p.q||'')}" placeholder="${L('Rechercher une montre','Search a watch')}" aria-label="${L('Rechercher dans ma collection','Search my collection')}" data-fk="colq"></div>`:''}
 ${OFF?`<p class="cache" style="margin-top:14px">${ic('lock')}${L('Disponible hors connexion · coffre chiffré sur l’appareil','Available offline · vault encrypted on device')}</p>`:''}
 <div class="pad" style="margin-top:16px" id="collbody">${body}</div>`;},
 mount:(el,p)=>{const i=$('#colq',el);if(i){if(!p.qf){p.qf=1;setTimeout(()=>i.focus(),100);}let t;i.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>{p.q=i.value;rerender();},250);});}}};
A.collTab=b=>{curEntry.params.tab=b.dataset.k;curEntry.params.emptyPreview=false;rerender();};
A.collSearch=()=>{const p=curEntry.params;p.search=!p.search;p.q='';p.qf=0;rerender();};
A.watch=b=>go('watch',{oid:b.dataset.oid});
A.watchHist=b=>go('watch',{oid:b.dataset.oid,anchor:'hist'});
A.goCat=()=>switchTab('catalog');
A.wishOpen=b=>{const x=S.wish[+b.dataset.i];if(x)go('pdp',{id:x.wid,cfg:x.cfg});};
A.wishAR=b=>{const x=S.wish[+b.dataset.i];if(x)startAR(x.wid,{cfg:x.cfg});};
A.wishDel=b=>{const i=+b.dataset.i;const x=S.wish[i];if(!x)return;S.wish.splice(i,1);save();rerender();toast(L('Retiré de vos souhaits','Removed from your wishlist'),{icon:'trash',act:{label:L('Annuler','Undo'),fn:()=>{S.wish.splice(i,0,x);save();rerender();}}});};
A.manage=b=>{const o=S.owned.find(x=>x.oid===b.dataset.oid);const w=W(o.wid);openSheet({label:L('Gérer','Manage'),data:{oid:o.oid},html:sheetHTML(esc(tx(w.name)),`<div class="list">${[['watch','watch',L('Voir la fiche détaillée','View full details')],['wrench','addServiceFromMgr',L('Ajouter un entretien','Add a service entry')],['qr','certFromMgr',L('Partager la preuve de propriété','Share proof of ownership')],['pin','stores',L('Trouver un service après-vente','Find an after-sales service')],['ar','arFromMgr',L('Essayer ce modèle en RA','Try this model in AR')]].map(([i,a,t])=>`<button class="li" type="button" data-act="${a}" data-oid="${o.oid}">${ic(i)}<span class="tx">${t}</span>${ic('chev','chev')}</button>`).join('')}</div>`,null,`RÉF. ${o.ref} · ${o.serial}`)});};
A.addServiceFromMgr=b=>{closeSheet();go('watch',{oid:b.dataset.oid,anchor:'hist'});setTimeout(()=>openService(b.dataset.oid),500);};
A.certFromMgr=b=>{closeSheet();openCert(b.dataset.oid);};
A.arFromMgr=b=>{const o=S.owned.find(x=>x.oid===b.dataset.oid);closeSheet();startAR(o.wid,{cfg:o.cfg});};

/* add a watch: scan / serial -> authenticity */
function addWatchHTML(d){
 if(d.step==='scan')return sheetHTML(L('Scanner la carte de garantie','Scan the warranty card'),`<div class="scanbox"><div class="card3"><b>YEMA</b><div style="margin-top:6px;letter-spacing:.14em">${L('CERTIFICAT DE GARANTIE','WARRANTY CERTIFICATE')}</div><div style="margin-top:14px;font-weight:800">${esc(d.serial)}</div></div><span class="beam"></span></div><p class="p center" style="margin-top:14px">${L('Placez la carte dans le cadre… lecture du QR code en cours.','Place the card in the frame… reading the QR code.')}</p>`);
 if(d.step==='verify'){const w=W(d.wid);const items=[L('Numéro de série reconnu','Serial number recognised')+` · ${esc(d.serial)}`,`${esc(tx(w.name))} · ${w.size} mm · ${MOVES[w.move].short}`,L('Registre de production Yema · Besançon','Yema production register · Besançon'),L('Garantie internationale activée · 3 ans','International warranty activated · 3 years')];
  return sheetHTML(d.done?L('Authenticité vérifiée','Authenticity verified'):L('Vérification…','Verifying…'),`<div class="verif"><div class="ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="54" fill="none" stroke="var(--line)" stroke-width="3"/><circle class="arc" cx="60" cy="60" r="54" fill="none" stroke="var(--gold)" stroke-width="3" stroke-linecap="round" transform="rotate(-90 60 60)"/><g transform="translate(24 16) scale(.36)">${renderWatch(wopts(w,d.cfg,{cls:''})).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'')}</g></svg></div><ol>${items.map((t,i)=>`<li class="${i<d.k?'on':''}"><i>${i<d.k?ic('check'):''}</i>${t}</li>`).join('')}</ol>${d.done?`<p class="p center" style="margin-top:14px">${L('Certificat numérique ajouté à votre coffre. Coffre prêt.','Digital certificate added to your vault. Vault ready.')}</p>`:''}</div>`,d.done?`<button class="btn gold" type="button" data-act="awDone">${L('Voir dans Ma Collection','View in My Collection')}</button>`:'');}
 return sheetHTML(L('Enregistrer une montre','Register a watch'),`<p class="p" style="margin-top:0">${L('Ajoutez un garde-temps Yema à votre collection : nous vérifions son authenticité auprès du registre de la maison.','Add a Yema timepiece to your collection: we verify its authenticity with the house register.')}</p>
 <button class="btn line net" type="button" data-act="awScan" style="margin-top:16px">${ic('scan')}${L('Scanner la carte de garantie','Scan the warranty card')}</button><div class="or" style="margin:18px 0 4px">${L('OU SAISIR','OR ENTER')}</div>
 <label class="fld"><span>${L('Modèle','Model')}</span><div class="inp dk"><select id="awm" aria-label="${L('Modèle','Model')}">${WATCHES.map(w=>`<option value="${w.id}" ${w.id===d.wid?'selected':''}>${esc(tx(w.name))}</option>`).join('')}</select></div></label>
 <label class="fld"><span>${L('Numéro de série','Serial number')}<button type="button" class="link" style="text-transform:none;letter-spacing:.02em;font-size:11px" data-act="awDemo">${L('Numéro de démo','Demo number')}</button></span><div class="inp dk" id="aws-w"><input id="aws" value="${esc(d.serial||'')}" placeholder="YM-1234-ABC" autocomplete="off" spellcheck="false" style="text-transform:uppercase"></div><small class="ferr" id="aws-e"></small><small class="muted small">${L('Gravé sur le fond du boîtier et imprimé sur la carte de garantie.','Engraved on the caseback and printed on the warranty card.')}</small></label>`,`<button class="btn gold net" type="button" data-act="awVerify">${ic('shield')}${L('Vérifier l’authenticité','Verify authenticity')}</button>`);}
const rndSerial=s=>'YM-'+(1000+Math.floor(Math.random()*8999))+'-'+(s||['XQA','RLG','SHN','FLY','NVG'][Math.floor(Math.random()*5)]);
function openAddWatch(o){o=o||{};const d={step:'form',wid:o.wid||'sh',cfg:o.cfg||null,serial:o.serial||'',purchase:!!o.purchase};openSheet({label:L('Enregistrer une montre','Register a watch'),html:addWatchHTML(d),data:d});}
A.addWatch=()=>openAddWatch();
A.awDemo=()=>{$('#aws').value=rndSerial();};
A.awScan=()=>{if(!needNet())return;const o=topSheet(),d=o.data;d.wid=$('#awm').value;d.serial=d.serial||rndSerial();d.step='scan';setSheet(o,addWatchHTML(d));setTimeout(()=>{if(!sheets.includes(o))return;runVerify(o);},RM?200:1900);};
A.awVerify=()=>{const o=topSheet(),d=o.data;const v=$('#aws').value.trim().toUpperCase();d.wid=$('#awm').value;if(!/^YM-\d{4}-[A-Z]{3}$/.test(v)){$('#aws-w').classList.add('err');$('#aws-e').textContent=L('Format attendu : YM-1234-ABC','Expected format: YM-1234-ABC');buzz();return;}if(!needNet())return;d.serial=v;runVerify(o);};
function runVerify(o){const d=o.data;d.step='verify';d.k=0;d.done=false;setSheet(o,addWatchHTML(d));const tick=()=>{if(!sheets.includes(o))return;d.k++;if(d.k>=4){d.done=true;buzz([12,40,24]);setTimeout(()=>confetti(.5,.32),120);}setSheet(o,addWatchHTML(d));if(!d.done)setTimeout(tick,RM?80:420);};setTimeout(tick,RM?80:500);}
A.awDone=()=>{const d=topSheet().data;const w=W(d.wid);const today=new Date();const iso=today.toISOString().slice(0,10);const end=new Date(today);end.setFullYear(end.getFullYear()+3);
 const oid='o'+Date.now();S.owned.unshift({oid,wid:w.id,cfg:Object.assign({dial:w.dial,case:w.case,strap:w.strap},d.cfg||{}),ref:w.ref,serial:d.serial,date:iso,dealer:{fr:'Boutique Yema Paris',en:'Yema Boutique Paris'},wEnd:end.toISOString().slice(0,10),price:d.cfg?priceOf(w,d.cfg):effPrice(w),hist:[{t:{fr:'Achat initial',en:'Initial purchase'},d:iso,x:{fr:'Authenticité vérifiée auprès du registre Yema. Garantie internationale de 3 ans activée.',en:'Authenticity verified with the Yema register. 3-year international warranty activated.'},by:{fr:'Registre Yema',en:'Yema register'}}],notes:'',fresh:true});
 if(S.purchase&&S.purchase.serial===d.serial)S.purchase.registered=true;save();closeSheet();step(5);switchTab('collection',{tab:'owned'});toast(L('Montre ajoutée · authenticité vérifiée','Watch added · authenticity verified'),{icon:'shield'});};

/* ================= watch details (#12) ================= */
SCR.watch={title:()=>L('Détails de la montre','Watch details'),
 render:p=>{const o=S.owned.find(x=>x.oid===p.oid)||S.owned[0];p.oid=o.oid;const w=W(o.wid);const ph=PHOTOS[o.oid]||[];
 return `<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Détails de la montre','Watch details')}</span><button class="ibtn" type="button" data-act="wMenu" aria-label="${L('Plus d’options','More options')}">${ic('dots')}</button></div>
 <div class="dhero"><span class="auth"><i></i>${L('Authenticité vérifiée','Authenticity verified')}</span>${wsvg(w,ownedCfg(o))}<h1 class="h2" style="margin-top:6px">${esc(tx(w.name))}</h1><div class="lbl" style="margin-top:4px">RÉF. ${o.ref}</div></div>
 <div class="pad"><div class="card" style="margin-top:14px;padding:16px"><h2 class="h3" style="margin-bottom:10px">${L('Informations de propriété','Ownership information')}</h2><div class="kv"><span class="lbl">${L('Numéro de série','Serial number')}</span><b>${o.serial}</b></div><div class="kv"><span class="lbl">${L('Date d’achat','Purchase date')}</span><b>${fdate(o.date)}</b></div><div class="kv"><span class="lbl">${L('Revendeur','Dealer')}</span><b>${esc(tx(o.dealer))}</b></div><div class="kv"><span class="lbl">${L('Statut garantie','Warranty status')}</span><b style="color:${warrantyOk(o)?'var(--ok)':'var(--err)'}">● ${warrantyOk(o)?L('Active jusqu’en','Active until')+' '+fmon(o.wEnd):L('Expirée','Expired')}</b></div></div>
 <div class="sech sec" id="hist"><h2 class="h2">${L('Historique d’entretien','Service history')}</h2><button class="link" type="button" data-act="addService">${ic('plus')}${L('Ajouter','Add')}</button></div>
 <div class="tl">${o.hist.map((h,i)=>`<div class="card tli ${i===0?'first':''}"><div class="th"><b>${esc(tx(h.t))}</b><small>${fmon(h.d)}</small></div><p>${esc(tx(h.x))}</p>${h.by?`<span class="by">${esc(tx(h.by))}</span>`:''}</div>`).join('')}</div>
 <div class="sech sec"><h2 class="h2">${L('Coffre & Notes','Vault & Notes')}</h2></div>
 <div class="vault"><button type="button" data-act="invoice">${ic('file')}${L('Facture numérique','Digital invoice')}</button><button type="button" data-act="addPhoto">${ic('camera')}${L('Ajouter photos','Add photos')}</button></div><input type="file" id="phin" accept="image/*" multiple hidden>
 ${ph.length?`<div class="photos">${ph.map((u,i)=>`<img src="${u}" alt="${L('Photo','Photo')} ${i+1}">`).join('')}</div>`:''}
 <div class="card notes"><div class="nh"><span class="lbl">${L('Notes personnelles','Personal notes')}</span><button class="ibtn nb" style="width:30px;height:30px" type="button" data-act="editNotes" aria-label="${L('Modifier les notes','Edit notes')}">${ic('edit')}</button></div>${p.editN?`<div class="inp dk" style="font-style:normal"><textarea id="notes" data-fk="notes" aria-label="${L('Notes personnelles','Personal notes')}">${esc(tx(o.notes))}</textarea></div><div class="row" style="margin-top:10px;justify-content:flex-end"><button class="btn ghost sm" type="button" data-act="editNotes">${L('Annuler','Cancel')}</button><button class="btn gold sm" type="button" data-act="saveNotes">${L('Enregistrer','Save')}</button></div>`:(tx(o.notes)?esc(tx(o.notes)):`<span class="muted">${L('Ajoutez une note : bracelet porté, occasion, souvenir…','Add a note: strap worn, occasion, memory…')}</span>`)}</div>
 <button class="btn line pill" type="button" data-act="cert" style="margin-top:22px">${ic('share')}${L('Partager preuve de propriété','Share proof of ownership')}</button></div>`;},
 mount:(el,p)=>{if(p.anchor==='hist'){p.anchor=null;setTimeout(()=>{const h=$('#hist',el);if(h)el.scrollTo({top:h.offsetTop-70,behavior:RM?'auto':'smooth'});},350);}
  const fi=$('#phin',el);fi.addEventListener('change',()=>{const arr=PHOTOS[p.oid]=PHOTOS[p.oid]||[];[...fi.files].slice(0,8).forEach(f=>arr.push(URL.createObjectURL(f)));toast(L(`${fi.files.length} photo(s) ajoutée(s) au coffre`,`${fi.files.length} photo(s) added to the vault`),{icon:'image'});rerender();});
  const o=S.owned.find(x=>x.oid===p.oid);if(o&&o.fresh){o.fresh=false;save();}}};
A.addPhoto=()=>$('#phin',curEl).click();
A.editNotes=()=>{const p=curEntry.params;p.editN=!p.editN;rerender();if(p.editN)setTimeout(()=>{const t=$('#notes',curEl);if(t)t.focus();},50);};
A.saveNotes=()=>{const o=S.owned.find(x=>x.oid===curEntry.params.oid);o.notes=$('#notes',curEl).value;save();curEntry.params.editN=false;rerender();toast(L('Notes enregistrées','Notes saved'),{icon:'edit'});};
A.wMenu=()=>{const oid=curEntry.params.oid;openSheet({label:'Options',html:sheetHTML(L('Options','Options'),`<div class="list"><button class="li" type="button" data-act="exportSheet">${ic('download')}<span class="tx">${L('Exporter la fiche (JSON)','Export record (JSON)')}</span></button><button class="li" type="button" data-act="removeWatch" data-oid="${oid}" style="color:var(--err)">${ic('trash')}<span class="tx">${L('Retirer de la collection','Remove from collection')}</span></button></div>`)});};
A.exportSheet=()=>{const o=S.owned.find(x=>x.oid===curEntry.params.oid);dl(`yema-${o.serial}.json`,JSON.stringify(o,null,2),'application/json');closeSheet();toast(L('Fiche exportée','Record exported'),{icon:'download'});};
A.removeWatch=async b=>{closeSheet();const ok=await confirmDlg({title:L('Retirer cette montre ?','Remove this watch?'),text:L('Elle disparaîtra de votre collection et de votre coffre. Le certificat reste enregistré chez Yema.','It will disappear from your collection and vault. The certificate stays registered with Yema.'),ok:L('Retirer','Remove'),danger:true});if(!ok)return;S.owned=S.owned.filter(x=>x.oid!==b.dataset.oid);save();back();toast(L('Montre retirée','Watch removed'),{icon:'trash'});};
function openService(oid){const today=new Date().toISOString().slice(0,10);openSheet({label:L('Ajouter un entretien','Add a service'),data:{oid},html:sheetHTML(L('Ajouter un entretien','Add a service entry'),`<label class="fld"><span>${L('Type','Type')}</span><div class="inp dk"><select id="svt">${[L('Révision complète','Full service'),L('Entretien de routine','Routine service'),L('Remplacement du bracelet','Strap replacement'),L('Test d’étanchéité','Water-resistance test'),L('Polissage du boîtier','Case polishing')].map(t=>`<option>${t}</option>`).join('')}</select></div></label><label class="fld"><span>Date</span><div class="inp dk"><input id="svd" type="date" value="${today}" max="${today}"></div></label><label class="fld"><span>${L('Atelier','Workshop')}</span><div class="inp dk"><input id="svb" value="${L('Service officiel Yema','Official Yema service')}"></div></label><label class="fld"><span>${L('Détails','Details')}</span><div class="inp dk"><textarea id="svx" placeholder="${L('Ex. : réglage, joints changés…','E.g. regulation, gaskets replaced…')}"></textarea></div></label>`,`<button class="btn gold" type="button" data-act="saveService">${L('Ajouter à l’historique','Add to history')}</button>`)});}
A.addService=()=>openService(curEntry.params.oid);
A.saveService=()=>{const oid=topSheet().data.oid;const o=S.owned.find(x=>x.oid===oid);const t=$('#svt').value,d=$('#svd').value||new Date().toISOString().slice(0,10),by=$('#svb').value,x=$('#svx').value||L('Entretien ajouté par le propriétaire.','Service added by the owner.');o.hist.unshift({t,d,x,by});o.hist.sort((a,b)=>b.d.localeCompare(a.d));save();closeSheet();rerender();toast(L('Entretien ajouté à l’historique','Service added to history'),{icon:'wrench'});};
function invoiceHTML(o){const w=W(o.wid);const ttc=o.price||effPrice(w);const ht=Math.round(ttc/1.2);return `<div class="inv-doc"><div class="row" style="justify-content:space-between;align-items:flex-start"><div><h4>YEMA</h4><div style="font-size:10px;letter-spacing:.14em;color:#7A7F8A">${L('BOUTIQUE PARIS · ILLUSTRATIF','PARIS BOUTIQUE · ILLUSTRATIVE')}</div></div><div style="text-align:right;font-size:11px"><b>${L('Facture','Invoice')} FA-${o.date.replace(/-/g,'').slice(0,6)}-${o.serial.slice(3,7)}</b><br>${fdate(o.date)}</div></div><div style="margin-top:14px;font-size:11.5px"><b>${esc(S.user.first)} ${esc(S.user.last)}</b><br>${esc(S.user.email)}</div><table><tr><td>${esc(tx(w.name))}<br><span style="color:#7A7F8A;font-size:10.5px">RÉF. ${o.ref} · N° ${o.serial}</span></td><td>${eur(ht)}</td></tr><tr><td>${L('TVA 20 %','VAT 20%')}</td><td>${eur(ttc-ht)}</td></tr><tr class="tot"><td>${L('Total TTC','Total incl. VAT')}</td><td>${eur(ttc)}</td></tr></table><div style="margin-top:10px;font-size:10.5px;color:#7A7F8A">${L('Garantie internationale 3 ans · réglée par carte','3-year international warranty · paid by card')}</div><span class="stamp">${L('Document illustratif · démo','Illustrative document · demo')}</span></div>`;}
A.invoice=()=>{const o=S.owned.find(x=>x.oid===curEntry.params.oid);openSheet({label:L('Facture','Invoice'),html:sheetHTML(L('Facture numérique','Digital invoice'),invoiceHTML(o),`<button class="btn ghost" type="button" data-act="dlInvoice">${ic('download')}${L('Télécharger','Download')}</button>`),data:{oid:o.oid}});};
A.dlInvoice=()=>{const o=S.owned.find(x=>x.oid===topSheet().data.oid);dl(`facture-yema-${o.serial}.html`,`<!doctype html><meta charset="utf-8"><title>Facture Yema (illustrative)</title><body style="font-family:Arial,sans-serif;max-width:560px;margin:40px auto">${invoiceHTML(o)}</body>`,'text/html');toast(L('Facture téléchargée','Invoice downloaded'),{icon:'download'});};
function certSvg(o){const w=W(o.wid);const q=qrSvg(certURL(o.serial),150).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');const qn=(qrMatrix(certURL(o.serial))||[]).length||29;return `<svg viewBox="0 0 600 780" xmlns="http://www.w3.org/2000/svg"><rect width="600" height="780" fill="#F7F2E8"/><rect x="18" y="18" width="564" height="744" fill="none" stroke="#C9A96A" stroke-width="2"/><rect x="28" y="28" width="544" height="724" fill="none" stroke="#C9A96A" stroke-opacity=".4"/><text x="300" y="96" text-anchor="middle" font-family="Playfair Display,Georgia,serif" font-size="46" letter-spacing="14" fill="#13223A">YEMA</text><text x="300" y="128" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="12" font-weight="700" letter-spacing="5" fill="#9A7A3A">${L('CERTIFICAT DE PROPRIÉTÉ','CERTIFICATE OF OWNERSHIP')}</text><g transform="translate(222 150) scale(.78)">${renderWatch(wopts(w,ownedCfg(o),{cls:''})).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'')}</g><text x="300" y="430" text-anchor="middle" font-family="Playfair Display,Georgia,serif" font-size="30" fill="#13223A">${esc(tx(w.name))}</text>${[[L('Référence','Reference'),o.ref],[L('Numéro de série','Serial number'),o.serial],[L('Propriétaire','Owner'),S.user.first+' '+S.user.last],[L('Date d’acquisition','Acquired'),fdate(o.date)]].map(([k,v],i)=>`<text x="70" y="${478+i*34}" font-family="Manrope,Arial,sans-serif" font-size="12" font-weight="700" letter-spacing="2" fill="#7A7F8A">${esc(k.toUpperCase())}</text><text x="${(i<2?330:330)}" y="${478+i*34}" font-family="Manrope,Arial,sans-serif" font-size="15" font-weight="700" fill="#13223A" text-anchor="start">${esc(v)}</text>`).join('')}<g transform="translate(64 604)"><g transform="scale(${136/(qn+8)})"><g transform="translate(4 4)">${q}</g></g></g><text x="210" y="650" font-family="Manrope,Arial,sans-serif" font-size="13" font-weight="700" fill="#13223A">${L('Authenticité vérifiée','Authenticity verified')}</text><text x="210" y="672" font-family="Manrope,Arial,sans-serif" font-size="11" fill="#7A7F8A">${L('Scannez pour vérifier ce certificat','Scan to verify this certificate')}</text><text x="210" y="692" font-family="Manrope,Arial,sans-serif" font-size="11" fill="#7A7F8A">${L('QR réel · lien vers la démo (prototype)','Real QR · links to the demo (prototype)')}</text></svg>`;}
function openCert(oid){const o=S.owned.find(x=>x.oid===oid);openSheet({label:L('Preuve de propriété','Proof of ownership'),data:{oid},html:sheetHTML(L('Preuve de propriété','Proof of ownership'),`<div class="cert">${certSvg(o)}</div><p class="p small center" style="margin-top:10px">${L('Partagez ce certificat lors d’une revente ou d’une assurance. Le code se vérifie auprès de Yema.','Share this certificate for resale or insurance. The code is verified by Yema.')}</p>`,`<button class="btn ghost" type="button" data-act="certShare" style="flex:1">${ic('share')}${L('Partager','Share')}</button><button class="btn gold" type="button" data-act="certDl" style="flex:1">${ic('download')}PNG</button>`)});}
A.cert=()=>openCert(curEntry.params.oid);
async function certPng(oid){const o=S.owned.find(x=>x.oid===oid);const im=await svgImg(certSvg(o),1200,1560);const c=document.createElement('canvas');c.width=1200;c.height=1560;c.getContext('2d').drawImage(im,0,0,1200,1560);return c.toDataURL('image/png');}
A.certDl=async()=>{const oid=topSheet().data.oid;try{const u=await certPng(oid);const a=document.createElement('a');a.href=u;a.download='yema-certificat.png';document.body.appendChild(a);a.click();a.remove();toast(L('Certificat téléchargé','Certificate downloaded'),{icon:'download'});}catch(e){toast(L('Téléchargement impossible ici','Download unavailable here'),{icon:'info'});}};
A.certShare=async()=>{if(!needNet())return;const oid=topSheet().data.oid;try{const u=await certPng(oid);const b=await (await fetch(u)).blob();const f=new File([b],'yema-certificat.png',{type:'image/png'});if(navigator.canShare&&navigator.canShare({files:[f]})){await navigator.share({files:[f],title:L('Preuve de propriété Yema','Yema proof of ownership')});return;}}catch(e){if(e&&e.name==='AbortError')return;}A.certDl();};
function dl(name,content,type){const b=new Blob([content],{type});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);}

/* wrist calibration: a bigger wrist makes the same case look smaller on the (fixed) illustrated arm */
const wristCm=()=>S.prefs.cm||{'<16':15,'16-18':17,'>18':19}[S.prefs.wrist]||17;
const arBase=w=>118*(17/wristCm())*(w.size/39);
const coverage=w=>Math.round(w.size/(wristCm()*10/3.1)*100);
const covText=w=>L(`Boîtier ${w.size} mm ≈ <b style="color:var(--gold2)">${coverage(w)} %</b> de la largeur de votre poignet`,`${w.size} mm case ≈ <b style="color:var(--gold2)">${coverage(w)}%</b> of your wrist width`);
const cmTxt=()=>wristCm().toFixed(1).replace('.',LANG==='fr'?',':'.');
function wristHTML(){const w=W(AR.id),cm=wristCm();return sheetHTML(L('Mon poignet','My wrist'),`<p class="p" style="margin-top:0">${L('Mesurez votre tour de poignet avec un mètre ruban : la montre est redimensionnée en direct.','Measure your wrist with a tape: the watch resizes live.')}</p><div class="wrv"><b id="wcm">${cmTxt()}</b> cm</div><input class="wrr" id="wrr" type="range" min="14" max="21" step="0.5" value="${cm}" aria-label="${L('Tour de poignet en centimètres','Wrist circumference in cm')}"><div class="scale"><span>14 cm</span><span>21 cm</span></div><p class="p center" id="wcov" style="margin-top:14px">${covText(w)}</p>`,`<button class="btn gold" type="button" data-act="closeSheet">${L('Valider','Done')}</button>`);}
A.arWrist=()=>{const el=curEl,stg=$('.arstage',el);stg.style.transform='translateY(-13%)';el.classList.add('cust');const o=openSheet({label:L('Mon poignet','My wrist'),clear:true,max:'48%',html:wristHTML(),onClose:()=>{stg.style.transform='';el.classList.remove('cust');save();toast(L(`Poignet calibré : ${cmTxt()} cm`,`Wrist calibrated: ${cmTxt()} cm`),{icon:'ruler'});}});const r=$('#wrr',o.sh);r.addEventListener('input',()=>{S.prefs.cm=+r.value;S.prefs.wrist=S.prefs.cm<16?'<16':S.prefs.cm>18?'>18':'16-18';arDraw();$('#wcm',o.sh).textContent=cmTxt();$('#wcov',o.sh).innerHTML=covText(W(AR.id));});};
