
/* ================= Club VIP (#13) ================= */
const EVENTS={
 expo:{t:{fr:'Exposition Héritage Yema',en:'Yema Heritage Exhibition'},where:{fr:'Paris, France',en:'Paris, France'},date:'2026-12-12',d:{fr:'Rejoignez-nous pour une soirée exclusive célébrant l’horlogerie française. Découvrez en avant-première les modèles inédits et rencontrez nos maîtres horlogers.',en:'Join us for an exclusive evening celebrating French watchmaking. Preview unreleased models and meet our master watchmakers.'},slots:[['sat18',{fr:'Sam. 12 déc.',en:'Sat 12 Dec'},'18:30'],['sat20',{fr:'Sam. 12 déc.',en:'Sat 12 Dec'},'20:30'],['sun11',{fr:'Dim. 13 déc.',en:'Sun 13 Dec'},'11:00'],['sun15',{fr:'Dim. 13 déc.',en:'Sun 13 Dec'},'15:00',1]]},
 atelier:{t:{fr:'Atelier démontage d’un calibre',en:'Calibre disassembly workshop'},where:{fr:'Manufacture · Morteau',en:'Manufacture · Morteau'},date:'2027-01-23',d:{fr:'Une matinée à l’établi avec un horloger : démontage et remontage d’un calibre YEMA3000. Huit places.',en:'A morning at the bench with a watchmaker: take apart and reassemble a YEMA3000 calibre. Eight seats.'},slots:[['a1',{fr:'Sam. 23 janv.',en:'Sat 23 Jan'},'09:30'],['a2',{fr:'Sam. 23 janv.',en:'Sat 23 Jan'},'14:00']]},
 mans:{t:{fr:'Le Mans Classic · paddock Yema',en:'Le Mans Classic · Yema paddock'},where:{fr:'Le Mans',en:'Le Mans'},date:'2027-07-03',d:{fr:'Accès au paddock, chronométrage d’une manche avec un Rallygraf et dîner des collectionneurs.',en:'Paddock access, timing a race with a Rallygraf and a collectors’ dinner.'},slots:[['m1',{fr:'Sam. 3 juil.',en:'Sat 3 Jul'},'10:00'],['m2',{fr:'Dim. 4 juil.',en:'Sun 4 Jul'},'10:00']]}
};
const ARTS={
 calibre:{k:{fr:'Savoir-faire',en:'Craft'},t:{fr:'La fabrication du calibre maison YEMA3000',en:'Making the in-house YEMA3000 calibre'},m:5,ex:{fr:'Entrez dans nos ateliers, là où nos maîtres horlogers assemblent la dernière génération.',en:'Step into our workshops, where our master watchmakers assemble the latest generation.'},
  body:{fr:['Dans l’atelier, le silence n’est rompu que par le cliquetis discret des brucelles. Chaque calibre YEMA3000 passe entre les mains de trois horlogers avant de rejoindre son boîtier.','La platine est décorée de Côtes de Genève, le rotor ajouré porte le nom de la maison. Rien n’est visible une fois la montre fermée ; tout se voit à travers le fond saphir.','« Un mouvement se règle comme on accorde un instrument : à l’oreille autant qu’à l’œil. »','Après assemblage, chaque mouvement est contrôlé pendant sept jours, dans six positions et à trois températures. Seuls ceux qui restent dans une tolérance de −4/+6 secondes par jour sont emboîtés.','C’est ce calibre qui anime la Superman Heritage 1/500 : 42 heures de réserve de marche, 28 800 alternances par heure et une garantie internationale de trois ans.'],en:['In the workshop, the only sound is the quiet click of tweezers. Every YEMA3000 calibre passes through the hands of three watchmakers before it meets its case.','The mainplate is decorated with Côtes de Genève, the openworked rotor carries the house name. None of it shows once the watch is closed; all of it shows through the sapphire caseback.','“You regulate a movement the way you tune an instrument: by ear as much as by eye.”','After assembly, each movement is tested for seven days, in six positions and at three temperatures. Only those within −4/+6 seconds a day are cased.','This is the calibre that drives the Superman Heritage 1/500: 42 hours of power reserve, 28,800 vibrations per hour and a three-year international warranty.']}},
 archives:{k:{fr:'Héritage',en:'Heritage'},t:{fr:'Découverte des archives Superman de 1963',en:'Uncovering the 1963 Superman archives'},m:3,ex:{fr:'Nous avons récemment découvert des plans originaux du premier modèle Superman.',en:'We recently uncovered original drawings of the very first Superman.'},
  body:{fr:['Dans un carton oublié, au fond d’un entrepôt de Besançon, dormaient quarante planches à dessin. Toutes datées de 1962 et 1963.','On y lit la naissance d’une idée simple : une lunette que l’on ne peut pas tourner par accident sous l’eau. Le fameux verrou de lunette de la Superman était né.','« Les plongeurs de l’époque voulaient un outil, pas un bijou. Nous avons gardé cette exigence. »','Ces plans ont servi de référence pour la Superman Heritage : mêmes proportions de 39 mm, même aiguille des heures en flèche, même index triangulaire à midi.'],en:['In a forgotten box at the back of a Besançon warehouse lay forty drawing boards, all dated 1962 and 1963.','They show the birth of a simple idea: a bezel that cannot be turned by accident underwater. The famous Superman bezel lock was born.','“Divers back then wanted a tool, not a jewel. We kept that standard.”','These drawings were the reference for the Superman Heritage: the same 39 mm proportions, the same arrow hour hand, the same triangle at twelve.']}}
};
function daysTo(iso){return Math.max(0,(new Date(iso)-new Date())/D);}
SCR.club={title:()=>'Club VIP',
 render:p=>{p.seg=p.seg||'news';const bk=S.bookings.expo;
 const seg=`<div class="pills" role="tablist" style="margin-top:4px">${[['news',L('Actualités','News')],['events',L('Événements','Events')],['launch',L('Lancements','Launches')]].map(([k,l])=>`<button type="button" role="tab" aria-selected="${p.seg===k}" data-act="clubSeg" data-k="${k}">${l}</button>`).join('')}</div>`;
 const inv=`<div class="inv"><div class="bg">${roomArt('expo')}</div><span class="star">${ic('star')}${L('Invitation exclusive','Exclusive invitation')}</span><div class="ct"><h2 class="h1">${tx(EVENTS.expo.t)}</h2><div class="meta">${tx(EVENTS.expo.where)} · ${fdate(EVENTS.expo.date,{day:'numeric',month:'short',year:'numeric'})}</div><div class="glass">${tx(EVENTS.expo.d)}${bk?`<div class="row" style="margin-top:12px;color:var(--gold3);font-weight:700">${ic('check')}${L('Réservé','Booked')} · ${bk.label}</div><button class="btn line net" type="button" data-act="book" data-e="expo">${L('Modifier ma réservation','Change my booking')}</button>`:`<button class="btn gold net" type="button" data-act="book" data-e="expo">${L('Réserver','Reserve')}</button>`}</div></div></div>`;
 const pv=[{id:'nmn',tag:L('Édition limitée 1/500','Limited edition 1/500'),d:L('Disponible pour les VIP 48 h en avance','Available to VIPs 48 h early'),btn:S.preorders.nmn?L('Précommandée','Pre-ordered'):L('Précommander','Pre-order'),act:'preorder'},{id:'rrp',tag:'Concept',name:L('Rallygraf Concept 60','Rallygraf Concept 60'),d:L('Votez pour le cadran du 60e anniversaire','Vote for the 60th-anniversary dial'),btn:S.votes.r60?L('Vote enregistré','Vote recorded'):L('Voter','Vote'),act:'vote',cfg:{dial:S.votes.r60||'cream'}},{id:'sh',tag:L('Accès anticipé','Early access'),d:L(`Superman Heritage 1/500 · ${S.left} pièces restantes`,`Superman Heritage 1/500 · ${S.left} pieces left`),btn:L('Voir la pièce','View piece'),act:'pdp'}];
 const news=`${inv}<div class="sec"><div class="sech pad"><h2 class="h2">${L('Avant-premières membres','Members’ previews')}</h2><button class="link" type="button" data-act="clubSeg" data-k="launch">${L('Voir tout','See all')}</button></div><div class="hscroll">${pv.map(x=>{const w=W(x.id);return `<div class="card pv"><span class="wimg" style="display:grid">${x.cfg?lw(w,{dial:x.cfg.dial}):lw(w)}</span><span class="bdg" style="margin-top:10px">${x.tag}</span><h3 class="h3">${esc(x.name||tx(w.name))}</h3><p>${x.d}</p><button class="btn line sm pill net" type="button" data-act="${x.act}" data-id="${x.id}" style="width:100%">${x.btn}</button></div>`;}).join('')}</div></div>
 <div class="sec pad"><div class="sech"><h2 class="h2">${L('Dans les coulisses de Yema','Behind the scenes at Yema')}</h2></div>${Object.keys(ARTS).map(k=>{const a=ARTS[k];return `<button class="card art" type="button" data-act="article" data-k="${k}"><div class="ph">${articleArt(k)}<span class="k">${tx(a.k)}</span></div><div class="bd"><h3 class="h3">${tx(a.t)}</h3><p>${tx(a.ex)}</p><span class="rt">${a.m} ${L('min de lecture','min read')} · <b>${L('Lire l’article','Read article')} →</b></span></div></button>`;}).join('')}
 <button class="card conc" type="button" data-act="concierge"><span class="av">${ic('crown')}</span><span><h3 class="h3">${L('Conciergerie VIP','VIP Concierge')}</h3><p>${L('Votre conseillère horlogère personnelle est disponible pour des rendez-vous privés, la recherche de modèles rares et un service prioritaire.','Your personal watch advisor is available for private appointments, rare-model sourcing and priority service.')}</p><span class="link">${L('Démarrer une conversation','Start a conversation')}${ic('arrow')}</span></span></button></div>`;
 const evs=`<div class="pad" style="margin-top:18px">${Object.keys(EVENTS).map(k=>{const e=EVENTS[k],b=S.bookings[k],d=new Date(e.date);return `<div class="card ev"><div class="dt"><b>${d.getDate()}</b><small>${fdate(d,{month:'short'}).replace('.','')}</small></div><div class="sp"><h3 class="h3">${tx(e.t)}</h3><p>${tx(e.where)} · ${tx(e.d).slice(0,90)}…</p>${b?`<span class="bdg">${ic('check')}${L('Réservé','Booked')} · ${b.label}</span>`:`<button class="btn gold sm pill net" type="button" data-act="book" data-e="${k}">${L('Réserver','Reserve')}</button>`}</div></div>`;}).join('')}<p class="small muted center">${L('Événements réservés aux membres du Club. Lieux et dates fictifs.','Events reserved for Club members. Fictional venues and dates.')}</p></div>`;
 const lau=[{id:'sh',t:L('Superman Heritage 1/500','Superman Heritage 1/500'),open:1},{id:'rrp',t:L('Rallygraf 60e anniversaire','Rallygraf 60th anniversary'),date:'2026-11-15T10:00:00'},{id:'fpilot',t:L('Flygraf Titane','Flygraf Titanium'),date:'2027-02-01T10:00:00',cfg:{dial:'anthracite',case:'polished'}}];
 const launch=`<div class="pad" style="margin-top:18px">${lau.map(x=>{const w=W(x.id);if(x.open)return `<div class="card" style="padding:16px;margin-bottom:12px"><div class="row"><span class="wimg" style="width:86px;height:96px;border-radius:10px;flex:none">${lw(w)}</span><div class="sp"><span class="bdg">${ic('crown')}${L('Accès anticipé ouvert','Early access open')}</span><h3 class="h3" style="margin-top:8px">${x.t}</h3><div style="height:4px;border-radius:4px;background:var(--line);margin:12px 0 6px"><div data-leftbar style="width:${((500-S.left)/5).toFixed(1)}%;height:100%;border-radius:4px;background:var(--gold);transition:width .6s"></div></div><small class="muted">${L(`<b data-sold>${500-S.left}</b> / 500 réservées · <b data-left>${S.left}</b> restantes`,`<b data-sold>${500-S.left}</b> / 500 reserved · <b data-left>${S.left}</b> left`)}</small></div></div><button class="btn gold sm" type="button" data-act="pdp" data-id="sh" style="width:100%;margin-top:14px">${L('Voir la pièce','View the piece')}</button></div>`;
  const dd=daysTo(x.date);const dj=Math.floor(dd),hh=Math.floor((dd-dj)*24);const on=!!S.alerts[x.id];return `<div class="card" style="padding:16px;margin-bottom:12px"><div class="row"><span class="wimg" style="width:86px;height:96px;border-radius:10px;flex:none;filter:brightness(.55) blur(.6px)">${lw(w,x.cfg)}</span><div class="sp"><span class="lbl">${L('Bientôt','Coming soon')}</span><h3 class="h3" style="margin-top:4px">${x.t}</h3><div class="cd"><div><b>${dj}</b><small>${L('jours','days')}</small></div><div><b>${hh}</b><small>${L('heures','hours')}</small></div></div></div></div><div class="row" style="justify-content:space-between;border-top:1px solid var(--line);padding-top:12px"><span class="small" id="al-${x.id}">${L('M’alerter au lancement','Alert me at launch')}</span><button class="tgl" type="button" role="switch" aria-checked="${on}" aria-labelledby="al-${x.id}" data-act="alertT" data-id="${x.id}"></button></div></div>`;}).join('')}</div>`;
 return `<div class="hdr"><span class="spacer"></span><span class="t caps">Club VIP</span><button class="ibtn" type="button" data-act="notifs" aria-label="Notifications">${ic('bell')}<span class="badge" data-badge="notif"></span></button></div>${seg}${p.seg==='news'?news:p.seg==='events'?evs:launch}`;},
 mount:(el,p)=>{if(p.open){const k=p.open;p.open=null;setTimeout(()=>openBooking(k),450);}}};
A.clubSeg=b=>{curEntry.params.seg=b.dataset.k;curEntry.scroll=0;rerender();curEl.scrollTop=0;};
A.alertT=b=>{const id=b.dataset.id;S.alerts[id]=!S.alerts[id];save();b.setAttribute('aria-checked',S.alerts[id]);toast(S.alerts[id]?L('Vous serez alerté au lancement','You’ll be alerted at launch'):L('Alerte désactivée','Alert turned off'),{icon:'bell'});};
function bookingHTML(k,d){const e=EVENTS[k];if(d.done)return sheetHTML(L('Réservation confirmée','Booking confirmed'),`<div class="center"><div class="okmark"><svg viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21l7 7 15-16"/></svg></div><h3 class="h2">${tx(e.t)}</h3><p class="p">${d.label} · ${d.guests===2?L('2 personnes','2 guests'):L('1 personne','1 guest')}<br>${tx(e.where)}</p><p class="p small">${L('Votre invitation nominative est disponible dans l’app (QR code à l’entrée).','Your personal invitation is in the app (QR code at the door).')}</p></div>`,`<button class="btn ghost" type="button" data-act="ics" data-e="${k}" style="flex:1">${ic('cal')}${L('Calendrier','Calendar')}</button><button class="btn gold" type="button" data-act="closeSheet" style="flex:1">${L('Terminé','Done')}</button>`);
 return sheetHTML(L('Réserver','Reserve'),`<p class="p" style="margin-top:0"><b style="color:var(--ink)">${tx(e.t)}</b> · ${tx(e.where)}</p><div class="lbl" style="margin:18px 0 10px">${L('Choisissez un créneau','Choose a time slot')}</div><div class="slots">${e.slots.map(([id,day,h,full])=>`<button type="button" aria-pressed="${d.slot===id}" data-act="bSlot" data-k="${id}" ${full?'disabled':''}><b>${h}</b><small>${tx(day)}${full?' · '+L('complet','full'):''}</small></button>`).join('')}</div><div class="lbl" style="margin:20px 0 10px">${L('Participants','Guests')}</div><div class="chips"><button class="chip" type="button" aria-pressed="${d.guests===1}" data-act="bGuests" data-k="1">${L('Seul(e)','Just me')}</button><button class="chip" type="button" aria-pressed="${d.guests===2}" data-act="bGuests" data-k="2">${L('+1 invité','+1 guest')}</button></div>`,`<button class="btn gold net" type="button" data-act="bConfirm" ${d.slot?'':'disabled'}>${L('Confirmer la réservation','Confirm booking')}</button>`,tx(EVENTS[k].where));}
function openBooking(k){if(!needNet())return;const d={k,slot:(S.bookings[k]||{}).slot||null,guests:(S.bookings[k]||{}).guests||1};openSheet({label:L('Réservation','Booking'),data:d,html:bookingHTML(k,d)});}
A.book=b=>openBooking(b.dataset.e);
A.bSlot=b=>{const o=topSheet();o.data.slot=b.dataset.k;setSheet(o,bookingHTML(o.data.k,o.data));};
A.bGuests=b=>{const o=topSheet();o.data.guests=+b.dataset.k;setSheet(o,bookingHTML(o.data.k,o.data));};
A.bConfirm=b=>{if(!needNet())return;const o=topSheet(),d=o.data;b.classList.add('loading');setTimeout(()=>{const s=EVENTS[d.k].slots.find(x=>x[0]===d.slot);d.label=`${tx(s[1])} · ${s[2]}`;S.bookings[d.k]={slot:d.slot,guests:d.guests,label:d.label};save();d.done=true;setSheet(o,bookingHTML(d.k,d));buzz([12,40,24]);setTimeout(()=>confetti(.5,.62),200);if(curEntry&&curEntry.name==='club'){const sc=curEl.scrollTop;rerender();curEl.scrollTop=sc;}},RM?100:900);};
A.ics=b=>{const e=EVENTS[b.dataset.e],bk=S.bookings[b.dataset.e];const s=e.slots.find(x=>x[0]===bk.slot);const dt=e.date.replace(/-/g,'')+(bk.slot.startsWith('sun')?'':'');const hm=s[2].replace(':','')+'00';dl('yema-evenement.ics',`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Yema Watch Club demo//FR\r\nBEGIN:VEVENT\r\nUID:${Date.now()}@yema-demo\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').slice(0,15)}Z\r\nDTSTART:${dt}T${hm}\r\nDURATION:PT2H\r\nSUMMARY:${tx(e.t)} (démo)\r\nLOCATION:${tx(e.where)}\r\nEND:VEVENT\r\nEND:VCALENDAR`,'text/calendar');toast(L('Ajouté au calendrier (.ics)','Added to calendar (.ics)'),{icon:'cal'});};
A.preorder=b=>{if(S.preorders.nmn){toast(L('Précommande déjà enregistrée','Pre-order already recorded'),{icon:'check'});return;}if(!needNet())return;const w=W('nmn');openSheet({label:L('Précommande','Pre-order'),html:sheetHTML(L('Précommander','Pre-order'),`<div class="row"><span class="wimg" style="width:90px;height:100px;border-radius:10px;flex:none">${wsvg(w)}</span><div><h3 class="h3">${tx(w.name)}</h3><p class="p small">${L('Édition limitée 1/500 · livraison prévue en mars 2027','Limited edition 1/500 · expected delivery March 2027')}</p><b style="color:var(--gold2)">${eur(w.price)}</b></div></div><div class="card" style="padding:14px;margin-top:16px;font-size:12.5px;color:var(--ink2)">${L('Aucun paiement aujourd’hui : un acompte de 10 % sera demandé à l’expédition. Annulable sans frais jusqu’à la livraison. (Démo : aucun paiement réel.)','No payment today: a 10% deposit is taken at shipping. Free cancellation until delivery. (Demo: no real payment.)')}</div>`,`<button class="btn gold" type="button" data-act="preConfirm">${L('Confirmer la précommande','Confirm pre-order')}</button>`)});};
A.preConfirm=b=>{b.classList.add('loading');setTimeout(()=>{S.preorders.nmn=Date.now();save();closeSheet();toast(L('Précommande confirmée · pièce réservée','Pre-order confirmed · piece reserved'),{icon:'check'});rerender();},RM?100:800);};
A.vote=()=>{if(!needNet())return;const w=W('rrp');const opts=['cream','sage','glacier'];const html=()=>sheetHTML(L('Rallygraf Concept 60','Rallygraf Concept 60'),`<p class="p" style="margin-top:0">${L('Quel cadran pour l’édition du 60e anniversaire ? Résultats le 15 novembre.','Which dial for the 60th-anniversary edition? Results on 15 November.')}</p><div class="hscroll" style="padding:14px 0 4px">${opts.map(k=>`<button class="colc" type="button" aria-pressed="${S.votes.r60===k}" data-act="voteFor" data-k="${k}"><span class="ck">${ic('check')}</span><span class="wimg" style="display:grid">${lw(w,{dial:k,sub:'black'})}</span><b style="text-transform:none;letter-spacing:0;font-size:12.5px">${tx(DIALS[k])}</b></button>`).join('')}</div>`);openSheet({label:L('Vote','Vote'),html:html(),data:{html}});};
A.voteFor=b=>{S.votes.r60=b.dataset.k;save();const o=topSheet();setSheet(o,o.data.html());toast(L('Merci, vote enregistré','Thanks, vote recorded'),{icon:'check'});if(curEntry.name==='club')setTimeout(()=>{closeSheet();rerender();},700);};
A.article=b=>go('article',{k:b.dataset.k});

SCR.article={tabs:false,clear:1,cls:'reader',title:p=>tx(ARTS[p.k].t),
 render:p=>{const a=ARTS[p.k];const bd=tx(a.body);return `<div class="rbar" id="rbar"></div><div class="hero">${articleArt(p.k)}<div class="hdr" style="position:absolute;top:0;left:0;right:0;background:none"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}" style="background:rgba(10,16,26,.5)">${ic('back')}</button><span class="sp"></span><button class="ibtn" type="button" data-act="shareArt" aria-label="${L('Partager','Share')}" style="background:rgba(10,16,26,.5)">${ic('share')}</button></div></div><div class="body"><span class="lbl g">${tx(a.k)} · ${a.m} ${L('min de lecture','min read')}</span><h1 class="h1" style="margin:10px 0 22px;font-size:28px">${tx(a.t)}</h1>${bd.map((x,i)=>x.startsWith('«')||x.startsWith('“')?`<blockquote>${esc(x)}</blockquote>`:`<p>${esc(x)}</p>`).join('')}<p style="font-family:var(--sans);font-size:12px;color:var(--mut)">${L('Contenu éditorial rédigé pour le prototype.','Editorial content written for the prototype.')}</p><button class="btn line" type="button" data-act="back" style="margin-top:14px">${L('Retour au Club','Back to the Club')}</button></div>`;},
 mount:el=>{const bar=$('#rbar',el);el.addEventListener('scroll',()=>{const m=el.scrollHeight-el.clientHeight;bar.style.width=(m>0?el.scrollTop/m*100:0)+'%';bar.style.top=el.scrollTop+'px';});}};
A.shareArt=async()=>{const a=ARTS[curEntry.params.k];try{if(navigator.share){await navigator.share({title:tx(a.t),url:location.href.split('#')[0]});return;}}catch(e){if(e&&e.name==='AbortError')return;}toast(L('Lien de l’article copié (démo)','Article link copied (demo)'),{icon:'share'});};

/* ================= Conciergerie (chat) ================= */
const CH={await:null};
function wishSH(){return S.wish.find(x=>x.wid==='sh'&&x.cfg);}
function slotsNext(){const out=[];const d=new Date();let add=1;const hs=['11:00','15:30','17:00'];while(out.length<3){const x=new Date(d.getTime()+add*D);if(x.getDay()!==0){out.push({id:'s'+out.length,d:x.toISOString().slice(0,10),h:hs[out.length]});}add++;}out.push({id:'visio',visio:1,h:'18:00',d:new Date(d.getTime()+D).toISOString().slice(0,10)});return out;}
const slotLabel=s=>`${fdate(s.d,{weekday:'short',day:'numeric',month:'short'})} · ${s.h}${s.visio?' · '+L('visio','video'):''}`;
function msgHTML(m){if(m.t==='appt')return `<div class="msg bot card"><div class="mc"><span class="bdg">${ic('cal')}${L('Rendez-vous confirmé','Appointment confirmed')}</span><h3 class="h3" style="margin:10px 0 6px">${m.visio?L('Rendez-vous en visio','Video appointment'):L('Salon privé · Boutique Yema Paris','Private lounge · Yema Boutique Paris')}</h3><div class="kv"><span>${L('Quand','When')}</span><b>${esc(m.label)}</b></div><div class="kv"><span>${L('Conseillère','Advisor')}</span><b>Claire Mercier</b></div>${m.cfg?`<div class="kv"><span>${L('Pièce préparée','Piece prepared')}</span><b>Superman Heritage · ${esc(cfgLine(m.cfg))}</b></div>`:''}</div></div>`;
 if(m.t==='pay'){const w=W(m.wid);return `<div class="msg bot card"><div class="wimg" style="height:130px">${wsvg(w,m.cfg)}</div><div class="mc"><span class="lbl">${L('Lien de paiement sécurisé','Secure payment link')}</span><h3 class="h3" style="margin:6px 0">${esc(tx(w.name))} · 1/500</h3><div class="small muted">${esc(cfgLine(m.cfg))}</div><div class="kv" style="margin-top:8px"><span>Total</span><b>${eur(m.price)}</b></div>${m.paid?`<div class="row" style="color:var(--ok);font-weight:700;margin-top:8px">${ic('check')}${L('Payé','Paid')}</div>`:`<button class="btn gold sm net" type="button" data-act="chatPay" style="width:100%;margin-top:10px">${ic('lock')}${L('Confirmer l’achat (démo)','Confirm purchase (demo)')}</button>`}</div></div>`;}
 return `<div class="msg ${m.who==='me'?'me':'bot'}">${esc(tx(m.x))}</div>`;}
function chips(){if(CH.await==='slot')return slotsNext().map(s=>[`slot:${s.id}`,slotLabel(s)]);const c=[];if(S.purchase&&!S.purchase.registered)c.push(['reg',L('Enregistrer dans Ma Collection','Register in My Collection')]);c.push(['rdv',S.appt?L('Modifier mon rendez-vous','Change my appointment'):L('Rendez-vous privé','Private appointment')]);if(!S.purchase)c.push(['ltd',L('Superman Heritage 1/500','Superman Heritage 1/500')],['buy',L('Finaliser un achat','Complete a purchase')]);c.push(['svc',L('Entretien de ma montre','Servicing my watch')]);return c;}
SCR.concierge={tabs:false,cls:'chat',title:()=>L('Conciergerie VIP','VIP Concierge'),
 render:()=>`<div class="hdr" style="border-bottom:1px solid var(--line)"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><div class="advh"><span class="av">CM</span><span><b>Claire Mercier</b><small>${OFF?L('Hors ligne · réponse à la reconnexion','Offline · reply when back online'):L('Conseillère horlogère · en ligne','Watch advisor · online')}</small></span></div><button class="ibtn" type="button" data-act="callAdv" aria-label="${L('Appeler','Call')}">${ic('phone')}</button></div><div class="msgs" id="msgs" aria-live="polite">${S.chat.map(msgHTML).join('')}</div><div class="qr" id="qr">${chips().map(([k,l])=>`<button class="chip net" type="button" data-act="chip" data-k="${k}">${esc(l)}</button>`).join('')}</div><form class="cin" id="cin"><input id="cmsg" placeholder="${L('Écrire à Claire…','Message Claire…')}" aria-label="${L('Votre message','Your message')}" autocomplete="off" data-fk="cmsg"><button class="send net" type="submit" aria-label="${L('Envoyer','Send')}">${ic('send')}</button></form>`,
 mount:(el,p,e)=>{const sc=()=>{el.scrollTop=el.scrollHeight;};setTimeout(sc,30);$('#cin',el).addEventListener('submit',ev=>{ev.preventDefault();const i=$('#cmsg',el);const v=i.value.trim();if(!v)return;if(!needNet())return;i.value='';userSay(v);route(v);});
  const runAuto=()=>{if(!p.auto||curEntry!==e)return;const a=p.auto;p.auto=null;const c=chips().find(x=>x[0]===a);setTimeout(()=>{userSay(c?c[1]:a);route(a);},400);};
  if(!S.chat.length){CH.await=null;botSay([{fr:`Bonjour ${S.user.first}, je suis Claire Mercier, votre conseillère horlogère Yema. Comment puis-je vous aider aujourd’hui ?`,en:`Hello ${S.user.first}, I’m Claire Mercier, your Yema watch advisor. How can I help you today?`}].concat(wishSH()?[{fr:`J’ai bien reçu votre configuration Superman Heritage (${cfgLine(wishSH().cfg)}). Souhaitez-vous la découvrir en salon privé ?`,en:`I’ve received your Superman Heritage configuration (${cfgLine(wishSH().cfg)}). Would you like to see it in a private lounge?`}]:[]),e,runAuto);}
  else runAuto();}};
function refreshChat(){if(!curEntry||curEntry.name!=='concierge')return;const el=curEl;$('#msgs',el).innerHTML=S.chat.map(msgHTML).join('');$('#qr',el).innerHTML=chips().map(([k,l])=>`<button class="chip net" type="button" data-act="chip" data-k="${k}">${esc(l)}</button>`).join('');requestAnimationFrame(()=>{el.scrollTop=el.scrollHeight;});}
function userSay(t){S.chat.push({who:'me',x:t});save();refreshChat();}
function botSay(list,e,done){let i=0;const nx=()=>{if(i>=list.length){refreshChat();if(done)done();return;}const m=list[i++];if(curEntry&&curEntry.name==='concierge'){const ms=$('#msgs',curEl);const t=document.createElement('div');t.className='typing';t.innerHTML='<i></i><i></i><i></i>';ms.appendChild(t);curEl.scrollTo({top:curEl.scrollHeight,behavior:RM?'auto':'smooth'});}setTimeout(()=>{const mm=typeof m==='function'?m():(m.t?m:{who:'bot',x:m});if(mm)S.chat.push(mm);save();refreshChat();nx();},RM?150:900);};nx();}
A.chip=b=>{if(!needNet())return;const k=b.dataset.k;userSay(b.textContent);route(k);};
A.callAdv=()=>toast(L('Appel de la conciergerie : +33 1 00 00 00 00 (fictif)','Concierge call: +33 1 00 00 00 00 (fictional)'),{icon:'phone'});
function route(k){const low=k.toLowerCase();
 if(k.startsWith('slot:')){const s=slotsNext().find(x=>'slot:'+x.id===k);CH.await=null;const label=slotLabel(s);const cfg=wishSH()?wishSH().cfg:null;S.appt={label,visio:!!s.visio,cfg,at:Date.now()};save();
  botSay([{t:'appt',who:'bot',label,visio:!!s.visio,cfg},{fr:cfg?'C’est noté. Je préparerai votre Superman Heritage configurée pour l’essayage, avec le cuir vintage et le bracelet acier pour comparer. Un rappel vous sera envoyé la veille.':'C’est noté. Un rappel vous sera envoyé la veille ; dites-moi si vous souhaitez que je prépare des pièces en particulier.',en:cfg?'Noted. I’ll prepare your configured Superman Heritage for the fitting, with the vintage leather and the steel bracelet to compare. You’ll get a reminder the day before.':'Noted. You’ll get a reminder the day before; tell me if you’d like me to prepare specific pieces.'}]);
  buzz([12,40,24]);setTimeout(()=>confetti(.5,.4),1000);S.notifs.unshift({id:'n'+Date.now(),k:'event',ts:Date.now(),read:false,to:{s:'concierge',p:{}},t:{fr:'Rendez-vous confirmé',en:'Appointment confirmed'},b:{fr:`Salon privé avec Claire Mercier · ${label}.`,en:`Private lounge with Claire Mercier · ${label}.`}});save();syncChrome();step(4);return;}
 if(k==='rdv'||/rdv|rendez|appoint|boutique|essayer|visite/.test(low)){CH.await='slot';botSay([{fr:'Avec plaisir. Voici mes prochaines disponibilités en salon privé, à la Boutique Yema Paris :',en:'With pleasure. Here are my next availabilities in the private lounge at the Yema Boutique Paris:'}]);return;}
 if(k==='ltd'||/1\/500|limit|édition|edition/.test(low)){botSay([{fr:`La Superman Heritage 1/500 est ouverte en accès anticipé aux membres VIP pendant 72 h. Il reste ${S.left} pièces. Je peux vous en réserver une, à votre configuration.`,en:`The Superman Heritage 1/500 is open to VIP members for 72 hours. ${S.left} pieces are left. I can reserve one for you, in your configuration.`}]);return;}
 if(k==='buy'||/achat|acheter|buy|purchase|payer|pay|réserver ma/.test(low)){const cfg=wishSH()?wishSH().cfg:{dial:'navy',case:'brushed',strap:'leather'};botSay([{fr:'Je vous envoie un lien de paiement sécurisé pour votre pièce numérotée :',en:'Here is a secure payment link for your numbered piece:'},{t:'pay',who:'bot',wid:'sh',cfg,price:priceOf(W('sh'),cfg)}]);return;}
 if(k==='svc'||/entretien|révision|revision|service|réparation/.test(low)){botSay([{fr:'Nous recommandons une révision complète tous les 4 à 5 ans. Votre Rallygraf Panda approche de sa première révision : je peux organiser un enlèvement sécurisé à domicile ou un dépôt en boutique.',en:'We recommend a full service every 4 to 5 years. Your Rallygraf Panda is due for its first one: I can arrange a secure home pick-up or a boutique drop-off.'}]);return;}
 if(k==='reg'){if(S.purchase)openAddWatch({wid:S.purchase.wid,cfg:S.purchase.cfg,serial:S.purchase.serial,purchase:true});return;}
 botSay([{fr:'Merci pour votre message. Je vérifie auprès de l’atelier et je reviens vers vous sous deux heures ouvrées. En attendant, puis-je vous proposer un rendez-vous ?',en:'Thank you for your message. I’ll check with the workshop and get back to you within two business hours. Meanwhile, may I offer you an appointment?'}]);}
A.chatPay=b=>{if(!needNet())return;b.classList.add('loading');const m=[...S.chat].reverse().find(x=>x.t==='pay'&&!x.paid);setTimeout(()=>{if(!m)return;m.paid=true;const serial=rndSerial('SHL');const no=501-S.left;S.left=Math.max(1,S.left-1);S.purchase={wid:m.wid,cfg:m.cfg,serial,price:m.price,no,at:Date.now()};save();refreshChat();buzz([12,40,24]);confetti(.5,.45);updLive();botSay([{fr:`Paiement confirmé. Votre Superman Heritage n° ${S.purchase.no}/500 est réservée à votre nom (série ${serial}). Elle vous attend en boutique sous 5 jours ; vous pouvez déjà l’enregistrer dans Ma Collection.`,en:`Payment confirmed. Your Superman Heritage no. ${S.purchase.no}/500 is reserved in your name (serial ${serial}). It will be ready in the boutique within 5 days; you can already register it in My Collection.`}]);},RM?150:1300);};

/* ================= notifications (#14) ================= */
const NICON={price:'trend',stock:'box',event:'cal',service:'wrench',club:'mega',launch:'crown'};
const NF={all:()=>true,unread:n=>!n.read,price:n=>n.k==='price'||n.k==='stock',event:n=>n.k==='event'||n.k==='launch'};
SCR.notifs={title:()=>'Notifications',
 render:p=>{p.f=p.f||'all';const list=p.emptyPreview?[]:S.notifs.filter(NF[p.f]);const u=unread();
 return `<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t caps">Notifications</span><button class="tbtn" type="button" data-act="readAll" style="border:0;color:var(--gold)" ${u?'':'disabled'}>${L('Tout lire','Read all')}</button></div>
 <div class="chips" style="padding:4px 18px 16px;flex-wrap:nowrap;overflow-x:auto">${[['all',L('Tout','All')],['unread',L('Non lus','Unread')+(u?` · ${u}`:'')],['price',L('Prix','Price')],['event',L('Événements','Events')]].map(([k,l])=>`<button class="chip caps" style="flex:none" type="button" aria-pressed="${p.f===k}" data-act="nFilter" data-k="${k}">${l}</button>`).join('')}</div>
 <div class="pad" id="nlist">${list.length?list.map(n=>`<div class="nf ${n.read?'read':''}" data-id="${n.id}"><div class="under">${ic(n.read?'trash':'check')}${n.read?L('Supprimer','Delete'):L('Marquer lu','Mark read')}</div><button class="body" type="button" data-act="nOpen" data-id="${n.id}"><span class="ni">${ic(NICON[n.k]||'bell')}</span><span class="sp" style="min-width:0"><span class="th"><span class="h3">${esc(tx(n.t))}</span><small class="tm">${ago(n.ts)}</small></span><p>${esc(tx(n.b))}</p>${n.cta?`<span class="cta">${esc(tx(n.cta))}${ic('chev')}</span>`:''}</span>${n.read?'':'<span class="ud" aria-label="non lu"></span>'}</button></div>`).join('')+`<p class="small muted center" style="margin-top:6px">${L('Glissez une notification vers la gauche pour la marquer comme lue.','Swipe a notification left to mark it as read.')}</p><button class="tbtn" type="button" data-act="clearAll" style="display:block;margin:14px auto 0">${L('Effacer tout','Clear all')}</button>`:`<div class="empty">${emptyArt('notif')}<h2 class="h2">${p.f==='all'?L('Aucune notification','No notifications'):L('Rien de ce côté','Nothing here')}</h2><p>${L('Baisses de prix, invitations et rappels d’entretien apparaîtront ici.','Price drops, invitations and service reminders will appear here.')}</p><button class="btn line sm pill" type="button" data-act="nPrefs">${L('Gérer mes alertes','Manage my alerts')}</button></div>`}</div>`;},
 mount:el=>{$$('.nf',el).forEach(n=>{const b=$('.body',n);let x0=null,dx=0,moved=false;b.addEventListener('pointerdown',e=>{x0=e.clientX;dx=0;moved=false;});b.addEventListener('pointermove',e=>{if(x0==null)return;dx=Math.min(0,e.clientX-x0);if(dx<-8){moved=true;b.style.transition='none';b.style.transform=`translateX(${dx}px)`;}});const up=()=>{if(x0==null)return;x0=null;b.style.transition='';if(dx<-80){b.style.transform='translateX(-100%)';setTimeout(()=>swipeN(n.dataset.id),220);}else b.style.transform='';};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('click',e=>{if(moved){e.stopPropagation();e.preventDefault();moved=false;}},true);});}};
function swipeN(id){const n=S.notifs.find(x=>x.id===id);if(!n)return;if(!n.read){n.read=true;save();rerender();toast(L('Marquée comme lue','Marked as read'));}else{const i=S.notifs.indexOf(n);S.notifs.splice(i,1);save();rerender();toast(L('Notification supprimée','Notification deleted'),{icon:'trash',act:{label:L('Annuler','Undo'),fn:()=>{S.notifs.splice(i,0,n);save();rerender();}}});}}
A.nFilter=b=>{curEntry.params.f=b.dataset.k;curEntry.params.emptyPreview=false;rerender();};
A.readAll=()=>{S.notifs.forEach(n=>n.read=true);save();rerender();toast(L('Toutes les notifications sont lues','All notifications read'));};
A.clearAll=async()=>{const ok=await confirmDlg({title:L('Effacer les notifications ?','Clear notifications?'),text:L('Toutes les notifications seront supprimées de cet appareil.','All notifications will be removed from this device.'),ok:L('Effacer','Clear'),danger:true});if(!ok)return;const old=S.notifs.slice();S.notifs=[];save();rerender();toast(L('Notifications effacées','Notifications cleared'),{icon:'trash',act:{label:L('Annuler','Undo'),fn:()=>{S.notifs=old;save();rerender();}}});};
A.nOpen=b=>{const n=S.notifs.find(x=>x.id===b.dataset.id);if(!n)return;n.read=true;save();syncChrome();if(n.id==='n0')step(0);const t=n.to||{};if(t.s==='club'){switchTab('club',t.p);return;}if(t.s==='watch'&&!S.owned.find(o=>o.oid===t.p.oid)){toast(L('Montre introuvable dans votre collection','Watch not found in your collection'),{icon:'info'});rerender();return;}if(t.s)go(t.s,t.p);};
A.nPrefs=()=>go('notifprefs');

/* ================= profile (#15) & settings ================= */
SCR.profile={title:()=>L('Profil','Profile'),
 render:()=>{const li=(i,a,t,v)=>`<button class="li" type="button" data-act="${a}">${ic(i)}<span class="tx">${t}</span>${v?`<span class="v">${v}</span>`:''}${ic('chev','chev')}</button>`;
 return `<div class="hdr"><span class="spacer"></span><span class="t caps">${L('Profil','Profile')}</span><button class="ibtn" type="button" data-act="toSecurity" aria-label="${L('Paramètres','Settings')}">${ic('gear')}</button></div>
 <div class="prof"><div class="avatar"><div>${S.guest?'Y':esc(S.user.first[0]+S.user.last[0])}</div><span class="cr">${ic('crown')}</span></div><div style="min-width:0"><h1 class="h2">${S.guest?L('Invité','Guest'):esc(S.user.first+' '+S.user.last)}</h1><div class="em">${S.guest?L('Connectez-vous pour synchroniser votre collection','Sign in to sync your collection'):esc(S.user.email)}</div>${S.guest?`<button class="btn gold sm" type="button" data-act="signIn" style="margin-top:10px">${L('Se connecter','Sign in')}</button>`:`<span class="vip">${L('Membre VIP Platine','Platinum VIP member')}</span>`}</div></div>
 <div class="grp"><span class="lbl">${L('Compte','Account')}</span><div class="list">${li('user','toInfo',L('Informations personnelles','Personal information'))}${li('pin','toAddr',L('Adresses','Addresses'))}${li('card','toPay',L('Moyens de paiement','Payment methods'))}</div></div>
 <div class="grp"><span class="lbl">${L('Préférences','Preferences')}</span><div class="list">${li('bell','nPrefs',L('Préférences de notification','Notification preferences'))}${li('globe','langSheet',L('Langue','Language'),LANG==='fr'?'Français (FR)':'English (EN)')}${li('watch','editPrefsP',L('Mes préférences horlogères','My watch preferences'),S.prefs.wrist?S.prefs.wrist+' cm':'')}${li('pin','stores',L('Trouver une boutique','Find a boutique'))}</div></div>
 <div class="grp"><span class="lbl">${L('Sécurité & confidentialité','Security & privacy')}</span><div class="list">${li('shield','toSecurity',L('Sécurité (A2F & biométrie)','Security (2FA & biometrics)'))}${li('file','toGdpr',L('Paramètres RGPD','GDPR settings'))}</div></div>
 <div class="grp"><span class="lbl">${L('Démo','Demo')}</span><div class="list"><div class="li">${ic('wifioff')}<span class="tx" id="offl">${L('Simuler le mode hors-ligne','Simulate offline mode')}<small>${L('Ma Collection reste disponible, le reste passe en cache','My Collection stays available, the rest is cached')}</small></span><button class="tgl" type="button" role="switch" aria-checked="${OFF}" aria-labelledby="offl" data-act="offT"></button></div></div></div>
 <button class="logout" type="button" data-act="logout">${ic('logout')}${L('Se déconnecter','Sign out')}</button><p class="ver">Yema Watch Club · v1.0.0 · ${L('prototype étudiant','student prototype')}</p>`;}};
A.signIn=()=>startFlow('login');
A.toInfo=()=>go('info');A.toAddr=()=>go('addresses');A.toPay=()=>go('payments');A.toSecurity=()=>go('security');A.toGdpr=()=>go('gdpr');
A.editPrefsP=()=>go('prefs',{from:'profile'});
A.offT=()=>setOffline(!OFF);
A.logout=async()=>{const ok=await confirmDlg({title:L('Se déconnecter ?','Sign out?'),text:L('Votre collection reste enregistrée sur votre compte.','Your collection stays saved on your account.'),ok:L('Se déconnecter','Sign out')});if(!ok)return;S.onboarded=false;S.guest=false;save();stopCam();startFlow('welcome');};
A.langSheet=()=>openSheet({label:L('Langue','Language'),html:sheetHTML(L('Langue','Language'),`<div class="list">${[['fr','Français','FR'],['en','English','EN']].map(([k,n,c])=>`<button class="li" type="button" role="radio" aria-checked="${LANG===k}" data-act="setLang" data-k="${k}"><span class="tx">${n}<small>${c}</small></span>${LANG===k?`<span style="color:var(--gold)">${ic('check')}</span>`:''}</button>`).join('')}</div><p class="small muted" style="margin-top:12px">${L('Toute l’interface bascule immédiatement, contenus éditoriaux compris.','The whole interface switches instantly, editorial content included.')}</p>`)});
A.setLang=b=>{closeSheet();setLang(b.dataset.k);toast(b.dataset.k==='fr'?'Langue : Français':'Language: English',{icon:'globe'});};

SCR.info={title:()=>L('Informations personnelles','Personal information'),
 render:()=>`<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Informations','Information')}</span><span class="spacer"></span></div><form class="pad" id="pif" novalidate>${[['first',L('Prénom','First name'),'given-name'],['last',L('Nom','Last name'),'family-name'],['email','Email','email'],['phone',L('Téléphone','Phone'),'tel']].map(([k,l,a])=>`<label class="fld"><span>${l}</span><div class="inp dk" id="pi-${k}w"><input id="pi-${k}" value="${esc(S.user[k])}" autocomplete="${a}" ${k==='email'?'type="email"':''}></div><small class="ferr" id="pi-${k}e"></small></label>`).join('')}<label class="fld"><span>${L('Tour de poignet','Wrist size')}</span><div class="inp dk"><select id="pi-wrist">${['<16','16-18','>18'].map(k=>`<option value="${k}" ${S.prefs.wrist===k?'selected':''}>${k} cm</option>`).join('')}</select></div></label><button class="btn gold net" type="submit" style="margin-top:24px">${L('Enregistrer','Save')}</button></form>`,
 mount:el=>{$('#pif',el).addEventListener('submit',e=>{e.preventDefault();let ok=true;['first','last','email'].forEach(k=>{const v=$('#pi-'+k,el).value.trim();const bad=!v||(k==='email'&&!/^\S+@\S+\.\S+$/.test(v));$('#pi-'+k+'w',el).classList.toggle('err',bad);$('#pi-'+k+'e',el).textContent=bad?(k==='email'&&v?L('Email invalide','Invalid email'):L('Champ requis','Required field')):'';if(bad)ok=false;});if(!ok)return;if(!needNet())return;['first','last','email','phone'].forEach(k=>S.user[k]=$('#pi-'+k,el).value.trim());S.prefs.wrist=S.user.wrist=$('#pi-wrist',el).value;S.guest=false;save();toast(L('Informations mises à jour','Information updated'),{icon:'user'});back();});}};
SCR.addresses={title:()=>L('Adresses','Addresses'),
 render:()=>`<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Adresses','Addresses')}</span><span class="spacer"></span></div><div class="pad">${S.addresses.map(a=>`<div class="card" style="padding:16px;margin-bottom:12px"><div class="row"><b class="sp">${esc(tx(a.n))}</b>${a.def?`<span class="bdg">${L('Par défaut','Default')}</span>`:`<button class="link" type="button" data-act="addrDef" data-id="${a.id}">${L('Définir par défaut','Set default')}</button>`}</div><p class="p">${esc(a.l)}<br>${esc(a.c)}</p></div>`).join('')}<button class="addc" type="button" data-act="addrAdd">${ic('plus')}${L('Ajouter une adresse','Add an address')}</button><p class="small muted" style="margin-top:12px">${L('Adresses illustratives.','Illustrative addresses.')}</p></div>`};
A.addrDef=b=>{S.addresses.forEach(a=>a.def=a.id===b.dataset.id);save();rerender();};
A.addrAdd=()=>openSheet({label:L('Nouvelle adresse','New address'),html:sheetHTML(L('Nouvelle adresse','New address'),`<label class="fld"><span>${L('Libellé','Label')}</span><div class="inp dk"><input id="ad-n" placeholder="${L('Maison de campagne','Country house')}"></div></label><label class="fld"><span>${L('Adresse','Address')}</span><div class="inp dk"><input id="ad-l" autocomplete="street-address"></div></label><label class="fld"><span>${L('Code postal et ville','Postcode and city')}</span><div class="inp dk"><input id="ad-c"></div></label>`,`<button class="btn gold" type="button" data-act="addrSave">${L('Enregistrer','Save')}</button>`)});
A.addrSave=()=>{const n=$('#ad-n').value.trim()||L('Adresse','Address'),l=$('#ad-l').value.trim(),c=$('#ad-c').value.trim();if(!l){toast(L('Saisissez une adresse','Enter an address'),{icon:'info'});return;}S.addresses.push({id:'a'+Date.now(),n,l,c});save();closeSheet();rerender();toast(L('Adresse ajoutée','Address added'),{icon:'pin'});};
SCR.payments={title:()=>L('Moyens de paiement','Payment methods'),
 render:()=>`<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Paiement','Payment')}</span><span class="spacer"></span></div><div class="paycard"><div class="row" style="justify-content:space-between"><span class="chipc"></span><span class="serif" style="font-size:20px;letter-spacing:.2em">YEMA</span></div><div class="num">•••• •••• •••• 4242</div><div class="row" style="justify-content:space-between;font-size:12px;color:var(--ink2)"><span>${esc((S.user.first+' '+S.user.last).toUpperCase())}</span><span>09/29</span></div></div><div class="grp"><div class="list"><div class="li">${ic('apple')}<span class="tx">Apple Pay<small>${L('Activé sur cet appareil','Enabled on this device')}</small></span><span class="bdg">${L('Actif','On')}</span></div><button class="li" type="button" data-act="addCard">${ic('plus')}<span class="tx">${L('Ajouter une carte','Add a card')}</span>${ic('chev','chev')}</button></div><p class="small muted" style="margin:12px 4px 0">${L('Démo : carte fictive, aucun paiement réel n’est possible.','Demo: fictional card, no real payment is possible.')}</p></div>`};
A.addCard=()=>toast(L('Démo : l’ajout de carte est désactivé','Demo: adding cards is disabled'),{icon:'lock'});
SCR.notifprefs={title:()=>L('Notifications','Notifications'),
 render:()=>`<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Alertes','Alerts')}</span><span class="spacer"></span></div><div class="grp" style="margin-top:6px"><div class="list">${[['price','trend',L('Baisses de prix','Price drops'),L('Sur les montres de votre liste de souhaits','On watches in your wishlist')],['stock','box',L('Retours en stock','Back in stock'),L('Pièces rares et éditions limitées','Rare pieces and limited editions')],['event','cal',L('Événements & invitations','Events & invitations'),L('Soirées, ateliers, avant-premières','Evenings, workshops, previews')],['service','wrench',L('Rappels d’entretien','Service reminders'),L('Révisions et fin de garantie','Services and warranty expiry')],['club','mega',L('Actualités du Club','Club news'),L('Nouveaux privilèges VIP','New VIP perks')],['launch','crown',L('Lancements exclusifs','Exclusive launches'),L('Accès anticipé 1/500','1/500 early access')]].map(([k,i,t,s])=>`<div class="li">${ic(i)}<span class="tx" id="np-${k}">${t}<small>${s}</small></span><button class="tgl" type="button" role="switch" aria-checked="${!!S.notifPrefs[k]}" aria-labelledby="np-${k}" data-act="npT" data-k="${k}"></button></div>`).join('')}</div></div>`};
A.npT=b=>{const k=b.dataset.k;S.notifPrefs[k]=!S.notifPrefs[k];save();b.setAttribute('aria-checked',S.notifPrefs[k]);buzz();};

SCR.security={title:()=>L('Sécurité','Security'),
 render:()=>{const s=S.sec;return `<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Sécurité','Security')}</span><span class="spacer"></span></div>
 <div class="grp" style="margin-top:6px"><span class="lbl">${L('Authentification','Authentication')}</span><div class="list"><div class="li">${ic('key')}<span class="tx" id="sc-2">${L('Double authentification (A2F)','Two-factor authentication (2FA)')}<small>${s.twofa?L('Code par SMS au +33 6 •• •• •• 42','Code by SMS to +33 6 •• •• •• 42'):L('Recommandé pour protéger votre coffre','Recommended to protect your vault')}</small></span><button class="tgl" type="button" role="switch" aria-checked="${s.twofa}" aria-labelledby="sc-2" data-act="secT" data-k="twofa"></button></div><div class="li">${ic('faceid')}<span class="tx" id="sc-f">Face ID<small>${L('Pour valider paiements et partages','To approve payments and sharing')}</small></span><button class="tgl" type="button" role="switch" aria-checked="${s.faceid}" aria-labelledby="sc-f" data-act="secT" data-k="faceid"></button></div><div class="li">${ic('lock')}<span class="tx" id="sc-b">${L('Exiger la biométrie à l’ouverture','Require biometrics on launch')}<small>${s.faceid?L('Verrouille l’app à chaque ouverture','Locks the app at every launch'):L('Activez d’abord Face ID','Turn on Face ID first')}</small></span><button class="tgl" type="button" role="switch" aria-checked="${s.bioOpen&&s.faceid}" aria-labelledby="sc-b" data-act="secT" data-k="bioOpen" ${s.faceid?'':'disabled'}></button></div></div>
 <button class="btn line" type="button" data-act="testBio" style="margin-top:14px" ${s.faceid?'':'disabled'}>${ic('faceid')}${L('Tester le déverrouillage','Test unlocking')}</button></div>
 <div class="grp"><span class="lbl">${L('Mot de passe','Password')}</span><div class="list"><button class="li" type="button" data-act="chPw">${ic('key')}<span class="tx">${L('Changer le mot de passe','Change password')}<small>${L('Modifié il y a 4 mois','Changed 4 months ago')}</small></span>${ic('chev','chev')}</button></div></div>
 <div class="grp"><span class="lbl">${L('Appareils connectés','Connected devices')}</span><div class="list">${S.devices.map(d=>`<div class="dev">${ic(d.i)}<div class="x"><b>${esc(d.n)}</b><small>${esc(tx(d.w))}</small></div>${d.cur?`<span class="bdg">${L('Cet appareil','This device')}</span>`:`<button class="btn ghost sm" type="button" data-act="devOut" data-id="${d.id}">${L('Déconnecter','Sign out')}</button>`}</div>`).join('')}</div></div>`;}};
A.secT=b=>{const k=b.dataset.k;S.sec[k]=!S.sec[k];if(k==='faceid'&&!S.sec.faceid)S.sec.bioOpen=false;save();rerender();toast(k==='twofa'?(S.sec.twofa?L('A2F activée','2FA on'):L('A2F désactivée','2FA off')):k==='faceid'?(S.sec.faceid?L('Face ID activé','Face ID on'):L('Face ID désactivé','Face ID off')):(S.sec.bioOpen?L('Biométrie exigée à l’ouverture','Biometrics required on launch'):L('Biométrie à l’ouverture désactivée','Launch biometrics off')),{icon:k==='twofa'?'key':'faceid'});if(k==='bioOpen'&&S.sec.bioOpen)setTimeout(()=>bioLock(L('Face ID configuré pour l’ouverture','Face ID set up for launch')),300);};
A.testBio=()=>bioLock().then(()=>toast(L('Déverrouillage réussi','Unlocked successfully'),{icon:'faceid'}));
A.chPw=()=>openSheet({label:L('Mot de passe','Password'),html:sheetHTML(L('Changer le mot de passe','Change password'),`<label class="fld"><span>${L('Actuel','Current')}</span><div class="inp dk"><input type="password" id="pw0" autocomplete="current-password"></div></label><label class="fld"><span>${L('Nouveau (8 caractères min.)','New (8+ characters)')}</span><div class="inp dk" id="pw1w"><input type="password" id="pw1" autocomplete="new-password"></div><small class="ferr" id="pw1e"></small></label>`,`<button class="btn gold net" type="button" data-act="pwSave">${L('Mettre à jour','Update')}</button>`)});
A.pwSave=()=>{const v=$('#pw1').value;if(v.length<8){$('#pw1w').classList.add('err');$('#pw1e').textContent=L('8 caractères minimum','8 characters minimum');return;}if(!needNet())return;closeSheet();toast(L('Mot de passe mis à jour','Password updated'),{icon:'key'});};
A.devOut=async b=>{const d=S.devices.find(x=>x.id===b.dataset.id);const ok=await confirmDlg({title:L('Déconnecter cet appareil ?','Sign out this device?'),text:esc(d.n),ok:L('Déconnecter','Sign out'),danger:true});if(!ok)return;S.devices=S.devices.filter(x=>x!==d);save();rerender();toast(L('Appareil déconnecté','Device signed out'),{icon:'device'});};

SCR.gdpr={title:()=>L('Paramètres RGPD','GDPR settings'),
 render:()=>{const c=S.consent||{analytics:false,perso:false,marketing:false};return `<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Paramètres RGPD','GDPR settings')}</span><span class="spacer"></span></div><div class="pad"><p class="p" style="margin-top:0">${L('Vous gardez la main sur vos données : consentement granulaire, export et suppression à tout moment.','You stay in control of your data: granular consent, export and deletion at any time.')}</p><div class="card dark-rows" style="padding:0 16px;margin-top:16px">${consentRows(c,'gTgl')}</div>
 <div class="list" style="margin-top:18px"><button class="li" type="button" data-act="exportData">${ic('download')}<span class="tx">${L('Exporter mes données','Export my data')}<small>${L('Fichier JSON de votre compte, collection et préférences','JSON file of your account, collection and preferences')}</small></span>${ic('chev','chev')}</button><button class="li" type="button" data-act="deleteAcc" style="color:var(--err)">${ic('trash')}<span class="tx">${L('Supprimer mon compte','Delete my account')}<small>${L('Irréversible · données effacées sous 30 jours','Irreversible · data erased within 30 days')}</small></span>${ic('chev','chev')}</button></div><p class="small muted" style="margin-top:14px">${L('Responsable de traitement fictif pour ce prototype. Dans cette démo, rien ne quitte votre navigateur.','Fictional data controller for this prototype. In this demo, nothing leaves your browser.')}</p></div>`;}};
A.gTgl=b=>{S.consent=S.consent||{analytics:false,perso:false,marketing:false};const k=b.dataset.k;S.consent[k]=!S.consent[k];save();b.setAttribute('aria-checked',S.consent[k]);toast(L('Consentement mis à jour','Consent updated'),{icon:'shield'});};
A.exportData=()=>{const data={exportedAt:new Date().toISOString(),notice:'Yema Watch Club — prototype étudiant, données fictives',user:S.user,consent:S.consent,preferences:S.prefs,language:LANG,security:{twoFactor:S.sec.twofa,faceId:S.sec.faceid,biometricsOnLaunch:S.sec.bioOpen},collection:S.owned.map(o=>({model:tx(W(o.wid).name),ref:o.ref,serial:o.serial,purchaseDate:o.date,warrantyEnd:o.wEnd,configuration:o.cfg,serviceHistory:o.hist.map(h=>({type:tx(h.t),date:h.d,details:tx(h.x)})),notes:tx(o.notes)})),wishlist:S.wish.map(x=>({model:tx(W(x.wid).name),configuration:x.cfg,savedAt:new Date(x.at).toISOString()})),bookings:S.bookings,appointment:S.appt,notifications:S.notifs.map(n=>({title:tx(n.t),read:n.read,date:new Date(n.ts).toISOString()})),addresses:S.addresses.map(a=>({label:tx(a.n),line:a.l,city:a.c}))};dl('yema-mes-donnees.json',JSON.stringify(data,null,2),'application/json');toast(L('Export JSON téléchargé','JSON export downloaded'),{icon:'download'});};
A.deleteAcc=async()=>{const ok=await confirmDlg({title:L('Supprimer votre compte ?','Delete your account?'),text:L('Votre collection, vos certificats et vos préférences seront définitivement effacés. Cette action est irréversible.','Your collection, certificates and preferences will be permanently erased. This cannot be undone.'),ok:L('Supprimer définitivement','Delete permanently'),danger:true});if(!ok)return;const lang=LANG;stopCam();S=defState();S.lang=lang;save();renderSteps();startFlow('welcome');toast(L('Compte supprimé','Account deleted'),{icon:'trash'});};

/* ================= stores / geolocation ================= */
const STORES=[{id:'b1',n:{fr:'Boutique Yema Paris',en:'Yema Boutique Paris'},t:{fr:'Boutique · conciergerie',en:'Boutique · concierge'},a:'12 rue du Faubourg-Saint-Honoré, 75008',h:'10:30–19:00',x:36,y:36},{id:'b2',n:{fr:'Horlogerie du Marais',en:'Horlogerie du Marais'},t:{fr:'Revendeur agréé',en:'Authorised dealer'},a:'5 rue des Archives, 75004',h:'11:00–19:30',x:66,y:57},{id:'b3',n:{fr:'Galeries Haussmann · corner Yema',en:'Galeries Haussmann · Yema corner'},t:{fr:'Corner',en:'Corner'},a:'40 boulevard Haussmann, 75009',h:'10:00–20:30',x:52,y:30},{id:'b4',n:{fr:'Saint-Germain Horloger',en:'Saint-Germain Horloger'},t:{fr:'Revendeur agréé',en:'Authorised dealer'},a:'18 rue du Bac, 75007',h:'10:30–19:00',x:40,y:63},{id:'b5',n:{fr:'Service après-vente Yema',en:'Yema after-sales service'},t:{fr:'Atelier SAV',en:'Service workshop'},a:'3 rue de Rivoli, 75001',h:'09:30–18:00',x:54,y:52}];
const ME={x:55,y:38};const km=s=>Math.hypot(s.x-ME.x,(s.y-ME.y)*.7)*.09;
SCR.stores={title:()=>L('Trouver une boutique','Find a boutique'),
 render:p=>{const hdr=`<div class="hdr"><button class="ibtn" type="button" data-act="back" aria-label="${L('Retour','Back')}">${ic('back')}</button><span class="t">${L('Boutiques & revendeurs','Boutiques & dealers')}</span><span class="spacer"></span></div>`;
 if(S.geo===null)return `${hdr}<div class="pad"><div class="card" style="padding:24px 20px;text-align:center;background:var(--ivory);color:var(--navy);border:0;border-radius:22px;margin-top:10px"><div class="okmark" style="background:#EFE7D7;border:0;color:var(--gold)">${ic('pin')}</div><h1 class="h2">${L('Autoriser « Yema Watch Club » à utiliser votre position ?','Allow “Yema Watch Club” to use your location?')}</h1><p class="p" style="color:#59606E;margin:10px 0 20px">${L('Votre position sert uniquement à trier les boutiques par distance. Elle n’est ni conservée ni partagée.','Your location is only used to sort boutiques by distance. It is neither stored nor shared.')}</p><button class="btn gold" type="button" data-act="geo" data-k="while">${L('Pendant l’utilisation de l’app','While using the app')}</button><button class="btn" type="button" data-act="geo" data-k="once" style="margin-top:10px;color:var(--navy);border:1px solid var(--ivline)">${L('Une seule fois','Allow once')}</button><button class="btn" type="button" data-act="geo" data-k="no" style="margin-top:10px;color:#8A8F99">${L('Ne pas autoriser','Don’t allow')}</button></div></div>`;
 const on=S.geo!=='no';const list=STORES.slice().sort((a,b)=>on?km(a)-km(b):tx(a.n).localeCompare(tx(b.n)));p.sel=p.sel||list[0].id;
 return `${hdr}<div class="map"><svg viewBox="0 0 100 70" preserveAspectRatio="none" aria-hidden="true"><rect width="100" height="70" fill="#15253E"/>${Array.from({length:12},(_,i)=>`<path d="M${i*9-4} 0 L${i*9+8} 70" stroke="#1F3252" stroke-width=".5"/><path d="M0 ${i*6} L100 ${i*6+4}" stroke="#1F3252" stroke-width=".5"/>`).join('')}<path d="M0 44 C 18 40, 28 50, 42 46 S 62 36, 74 42 S 92 52, 100 48" stroke="#2C5A86" stroke-width="3.2" fill="none"/><ellipse cx="22" cy="20" rx="9" ry="5" fill="#1D3B33"/><ellipse cx="44" cy="58" rx="5" ry="3.5" fill="#1D3B33"/><path d="M8 30 L92 26 M50 0 L54 70 M20 62 L80 10" stroke="#2A3E60" stroke-width="1.1"/></svg>${on?`<span class="me-dot" style="left:${ME.x}%;top:${ME.y/0.7}%"></span>`:''}${list.map((s,i)=>`<button class="pin ${p.sel===s.id?'on':''}" type="button" style="left:${s.x}%;top:${s.y/0.7}%" data-act="storeSel" data-id="${s.id}" aria-label="${esc(tx(s.n))}"><span>${i+1}</span></button>`).join('')}</div><span class="illus">${on?L('Position simulée : Paris 9e · ','Simulated position: Paris 9th · '):L('Localisation désactivée · tri alphabétique · ','Location off · sorted A–Z · ')}${L('adresses illustratives','illustrative addresses')}</span>
 <div class="pad" style="margin-top:14px">${list.map((s,i)=>`<div class="card store ${p.sel===s.id?'on':''}" id="st-${s.id}"><div class="th"><div><span class="lbl">${i+1} · ${tx(s.t)}</span><h3 class="h3" style="margin-top:4px">${esc(tx(s.n))}</h3><small>${esc(s.a)} · ${s.h}</small></div>${on?`<span class="d">${km(s).toFixed(1).replace('.',LANG==='fr'?',':'.')} km</span>`:''}</div><div class="acts"><button class="btn ghost sm" type="button" data-act="route">${ic('nav')}${L('Itinéraire','Directions')}</button><button class="btn ghost sm" type="button" data-act="callAdv">${ic('phone')}</button><button class="btn line sm net" type="button" data-act="concierge">${ic('cal')}${L('Rendez-vous','Book')}</button></div></div>`).join('')}${on?'':`<button class="btn line sm pill" type="button" data-act="geoReset" style="width:100%">${L('Réactiver la localisation','Turn location back on')}</button>`}</div>`;}};
A.geo=b=>{S.geo=b.dataset.k;save();rerender();if(S.geo!=='no')toast(L('Position trouvée','Location found'),{icon:'pin'});};
A.geoReset=()=>{S.geo=null;save();rerender();};
A.storeSel=b=>{curEntry.params.sel=b.dataset.id;rerender();const c=$('#st-'+b.dataset.id,curEl);if(c)c.scrollIntoView({block:'center',behavior:RM?'auto':'smooth'});};
A.route=()=>toast(L('Ouverture de Plans avec l’itinéraire (démo)','Opening Maps with directions (demo)'),{icon:'nav'});
