
/* ================= onboarding ================= */
SCR.splash={raw:1,tabs:false,cls:'splash',title:()=>'YEMA',
 render:()=>`<svg class="appi" viewBox="0 0 100 100" aria-hidden="true"><rect width="100" height="100" rx="23" fill="#0F1B2D" stroke="rgba(201,169,106,.35)"/><text x="50" y="70" text-anchor="middle" font-family="Playfair Display,Georgia,serif" font-weight="600" font-size="62">Y</text><path d="M36 80h28" stroke="#D4B36F" stroke-width="1.4"/></svg><div class="wm">YEMA</div><small>${L('CLUB HORLOGER · DEPUIS 1948','WATCH CLUB · SINCE 1948')}</small>`,
 mount:(el,p,e)=>{let done=false;const nx=()=>{if(done||top()!==e)return;done=true;afterSplash();};setTimeout(nx,RM?300:1250);el.addEventListener('click',nx);}};
function afterSplash(){const sp=top()&&top().el;if(sp&&!RM)sp.animate([{transform:'none',opacity:1},{transform:'scale(1.35)',opacity:0}],{duration:320,easing:'ease-in',fill:'forwards'});setTimeout(afterSplash2,RM?0:260);}
function afterSplash2(){if(S.onboarded){(S.sec.bioOpen&&S.sec.faceid?bioLock():Promise.resolve()).then(()=>enterTabs('home'));}else replace('welcome');}
SCR.welcome={raw:1,tabs:false,cls:'wel hero',title:()=>L('Bienvenue','Welcome'),
 render:()=>`<div class="sc"><div class="hero">${pic(W('nme'),0,{full:true,eager:true,fp:true})}<div class="ar">AR<sup>+</sup></div><div class="sr">SHOWROOM<br>${L('DIGITAL','DIGITAL')}<br>${L('EXCLUSIF','EXCLUSIVE')}</div></div>
 <div class="ws"><h1 class="h1">${L('L’Expérience Horlogère Intemporelle','The Timeless Watchmaking Experience')}</h1><p>${L('Les collections YEMA, l’essai en réalité augmentée et votre collection certifiée, dans une seule app.','YEMA collections, augmented-reality try-on and your certified collection, in one app.')}</p>
 <button class="btn navy" type="button" data-act="explore" style="justify-content:space-between">${L('Explorer directement','Explore now')}${ic('arrow')}</button>
 <div class="alt"><button class="tbtn" type="button" data-act="toLogin">${L('Se connecter','Sign in')}</button><button class="tbtn g" type="button" data-act="toLogin">${L('Créer un compte','Create account')}</button></div></div></div>`};
A.explore=()=>{if(!S.consent)S.consent={analytics:false,perso:true,marketing:false};S.onboarded=true;save();buzz([10,30,10]);enterTabs('home');};
A.toLogin=()=>go('login');
SCR.login={tabs:false,title:()=>L('Connexion','Sign in'),short:()=>L('Connexion','Sign in'),
 render:()=>`<div class="pad"><div class="serif center" style="font-size:22px;letter-spacing:.3em;margin:6px 0 26px">YEMA</div><h1 class="h1" style="font-size:30px">${L('Bon retour','Welcome back')}</h1><p class="p">${L('Identifiez-vous pour retrouver votre collection et vos commandes.','Sign in to find your collection and your orders.')}</p>
 <form id="lf" novalidate><label class="fld"><span>${L('Email ou téléphone','Email or phone')}</span><div class="inp" id="i-em"><input id="em" type="text" inputmode="email" autocomplete="username" value="alexandre.d@example.com"></div><small class="ferr" id="e-em"></small></label>
 <label class="fld"><span>${L('Mot de passe','Password')}<button type="button" class="link" style="font-size:12px" data-act="forgot">${L('Oublié ?','Forgot?')}</button></span><div class="inp" id="i-pw"><input id="pw" type="password" autocomplete="current-password" value="yema1948"><button type="button" class="nbb" style="width:32px;height:32px;color:var(--mut)" data-act="togglePw" aria-label="${L('Afficher le mot de passe','Show password')}">${ic('eye')}</button></div><small class="ferr" id="e-pw"></small></label>
 <p class="hint">${ic('user')}${L('Compte démo prérempli : touchez « Se connecter ».','Demo account prefilled: just tap “Sign in”.')}</p>
 <button class="btn gold" type="submit" id="lbtn" style="margin-top:18px">${L('Se connecter','Sign in')}</button></form>
 <div class="or">${L('OU','OR')}</div><button class="sso" type="button" data-act="sso" data-p="Apple">${ic('apple')}${L('Continuer avec Apple','Continue with Apple')}</button><button class="sso" type="button" data-act="sso" data-p="Google">${ic('google')}${L('Continuer avec Google','Continue with Google')}</button>
 <p class="center muted small" style="margin-top:22px;display:flex;gap:6px;align-items:center;justify-content:center">${ic('lock')}${L('Authentification sécurisée','Secure authentication')}</p></div>`,
 mount:el=>{$('#lf',el).addEventListener('submit',ev=>{ev.preventDefault();const em=$('#em',el).value.trim(),pw=$('#pw',el).value;let ok=true;[['em',em,L('Saisissez votre email ou téléphone.','Enter your email or phone.')],['pw',pw,L('Saisissez votre mot de passe.','Enter your password.')]].forEach(([k,v,m])=>{$('#i-'+k,el).classList.toggle('err',!v);$('#e-'+k,el).textContent=v?'':m;if(!v)ok=false;});if(!ok){buzz([20,40,20]);return;}if(!needNet())return;const b=$('#lbtn',el);b.classList.add('loading');setTimeout(()=>{if(em.includes('@'))S.user.email=em;save();loginNext();},RM?100:800);});
}};
A.forgot=()=>toast(L('Lien de réinitialisation envoyé (démo)','Reset link sent (demo)'),{icon:'mail'});
A.togglePw=b=>{const i=$('#pw',top().el);const s=i.type==='password';i.type=s?'text':'password';b.innerHTML=ic(s?'eyeoff':'eye');};
A.sso=b=>{if(!needNet())return;b.style.opacity=.5;setTimeout(()=>{save();loginNext();},RM?100:700);};
function loginNext(){if(!S.consent)go('rgpd');else finishOnb();}
function finishOnb(){S.onboarded=true;save();enterTabs('home');}
const CONS=[['analytics',{fr:'Analytiques',en:'Analytics'},{fr:'Nous aide à comprendre l’usage de l’app.',en:'Helps us understand how the app is used.'}],['perso',{fr:'Personnalisation',en:'Personalisation'},{fr:'Mémorise vos préférences et recommandations.',en:'Remembers your preferences and recommendations.'}],['marketing',{fr:'Marketing',en:'Marketing'},{fr:'Publicités plus pertinentes.',en:'More relevant advertising.'}]];
function consentRows(c,act){return `<div class="crow"><div class="x"><b>${L('Strictement nécessaire','Strictly necessary')}</b><small>${L('Requis pour le fonctionnement de l’app.','Required for the app to work.')}</small></div><span class="always">${L('Toujours actif','Always on')}</span></div>`+CONS.map(([k,t,d])=>`<div class="crow"><div class="x"><b id="cl-${k}">${tx(t)}</b><small>${tx(d)}</small></div><button class="tgl" type="button" role="switch" aria-checked="${!!c[k]}" aria-labelledby="cl-${k}" data-act="${act}" data-k="${k}"></button></div>`).join('');}
SCR.rgpd={tabs:false,cls:'rg',title:()=>L('Confidentialité','Privacy'),
 render:p=>{p.c=p.c||Object.assign({analytics:false,perso:true,marketing:false},S.consent||{});return `<div class="ivs"><h1 class="h2 center" style="font-size:24px">${L('Préférences de confidentialité','Privacy preferences')}</h1><p class="center" style="margin:10px 6px 16px;color:#59606E;font-size:13.5px;line-height:1.55">${L('Choisissez ce que YEMA peut utiliser pour améliorer votre showroom numérique.','Choose what YEMA may use to improve your digital showroom.')}</p>${consentRows(p.c,'cTgl')}<button class="btn gold" type="button" data-act="cAccept" style="margin-top:18px">${L('Accepter la sélection','Accept selection')}</button><button class="btn" type="button" data-act="cAll" style="margin-top:8px;color:var(--navy);background:rgba(19,34,58,.06)">${L('Tout accepter','Accept all')}</button></div>`;}};
A.cTgl=b=>{const p=top().params,k=b.dataset.k;p.c[k]=!p.c[k];b.setAttribute('aria-checked',p.c[k]);buzz(5);};
A.cAccept=()=>{S.consent=Object.assign({},top().params.c);save();go('prefs');};
A.cAll=()=>{S.consent={analytics:true,perso:true,marketing:true};save();go('prefs');};
SCR.prefs={tabs:false,title:()=>L('Préférences','Preferences'),
 render:p=>{const q=p.q=p.q||JSON.parse(JSON.stringify(S.prefs));const colW=c=>WATCHES.find(w=>w.col===c);
 return `<div class="pad"><h1 class="h1 center">${L('Personnalisez votre expérience','Personalise your experience')}</h1><p class="p center">${L('Vos goûts orientent la sélection de l’accueil et l’essai virtuel.','Your taste shapes the home selection and the virtual try-on.')}</p>
 <div class="sech" style="margin:24px 0 10px"><h2 class="h3">${L('Profil de poignet','Wrist profile')}</h2><span class="lbl g">${L('Calibre la RA','Calibrates AR')}</span></div>
 <div class="opt3">${[[15,'< 16 cm',L('Fin','Slim')],[17,'16–18 cm',L('Moyen','Medium')],[19,'> 18 cm',L('Large','Large')]].map(([k,a,c])=>`<button class="opt" type="button" aria-pressed="${q.cm===k}" data-act="pWrist" data-k="${k}"><b>${a}</b><small>${c}</small></button>`).join('')}</div>
 <div class="sech" style="margin:24px 0 10px"><h2 class="h3">${L('Collections favorites','Favourite collections')}</h2></div></div>
 <div class="hscroll">${COLS.map(c=>`<button class="colc" type="button" aria-pressed="${q.cols.includes(c)}" data-act="pCol" data-k="${c}"><span class="ck">${ic('check')}</span>${pic(colW(c),0,{cls:'zoom',alt:false})}<b>${c}</b></button>`).join('')}</div>
 <div class="pad"><div class="sech" style="margin:24px 0 4px"><h2 class="h3">${L('Budget','Budget')}</h2><b style="color:var(--gold2)" id="bud">${L('jusqu’à','up to')} ${eur(q.budget[1])}</b></div><input class="rng" type="range" min="500" max="4000" step="100" value="${q.budget[1]}" id="rb" aria-label="Budget"><div class="scale"><span>${eur(500)}</span><span>${eur(4000)}</span></div>
 <div class="sech" style="margin:22px 0 10px"><h2 class="h3">${L('Styles','Styles')}</h2></div><div class="chips">${STYLES.map(([k,l])=>`<button class="chip" type="button" aria-pressed="${q.styles.includes(k)}" data-act="pStyle" data-k="${k}">${tx(l)}</button>`).join('')}</div>
 <button class="btn gold" type="button" data-act="pSave" style="margin-top:26px">${p.from?L('Enregistrer','Save'):L('Sauvegarder & continuer','Save & continue')}</button>${p.from?'':`<button class="tbtn" type="button" data-act="pSkip" style="display:block;margin:14px auto 0;color:var(--mut)">${L('Passer','Skip')}</button>`}</div>`;},
 mount:(el,p)=>{const r=$('#rb',el);r.addEventListener('input',()=>{p.q.budget=[0,+r.value];$('#bud',el).textContent=`${L('jusqu’à','up to')} ${eur(+r.value)}`;});}};
A.pWrist=b=>{top().params.q.cm=+b.dataset.k;$$('.opt',top().el).forEach(o=>o.setAttribute('aria-pressed',o===b));buzz(5);};
A.pCol=b=>{const q=top().params.q,k=b.dataset.k;q.cols=q.cols.includes(k)?q.cols.filter(x=>x!==k):q.cols.concat(k);b.setAttribute('aria-pressed',q.cols.includes(k));buzz(5);};
A.pStyle=b=>{const q=top().params.q,k=b.dataset.k;q.styles=q.styles.includes(k)?q.styles.filter(x=>x!==k):q.styles.concat(k);b.setAttribute('aria-pressed',q.styles.includes(k));};
A.pSave=()=>{const p=top().params;S.prefs=p.q;save();if(p.from){toast(L('Préférences mises à jour','Preferences updated'));back();}else finishOnb();};
A.pSkip=()=>finishOnb();

/* ================= watch card ================= */
function wcard(w,o){o=o||{};const on=S.wish.some(x=>x.wid===w.id);const t=tagOf(w);
 return `<div class="wc">${t?`<span class="tag ${w.ltd||w.pre?'':'o'}">${esc(t)}</span>`:''}<button class="heart" type="button" data-act="heart" data-id="${w.id}" aria-pressed="${on}" aria-label="${esc(L('Liste d’envies','Wishlist')+' · '+w.n)}">${ic(on?'heartf':'heart')}</button><button class="main" type="button" data-act="pdp" data-id="${w.id}">${pic(w,o.i||0,{alt:false})}<span class="meta"><span class="lbl">${esc(w.col)}</span><span class="nm">${esc(w.n)}</span>${o.why?`<span class="lbl g" style="display:block;margin-top:3px;letter-spacing:.04em;text-transform:none;font-size:11px">${esc(o.why)}</span>`:''}<span class="pr">${eur(w.p)}</span></span></button></div>`;}
function toggleWish(id,b){const on=S.wish.some(x=>x.wid===id);if(on){const old=S.wish;S.wish=S.wish.filter(x=>x.wid!==id);save();toast(L('Retiré de vos envies','Removed from wishlist'),{icon:'heart',act:{label:L('Annuler','Undo'),fn:()=>{S.wish=old;save();refreshHearts(id);}}});}else{S.wish.unshift({wid:id,o:(b&&b.o)||defO(W(id)),at:Date.now()});save();toast(L('Ajouté à vos envies','Added to wishlist'),{icon:'heartf'});}buzz(on?6:[8,30,8]);refreshHearts(id);}
function refreshHearts(id){const on=S.wish.some(x=>x.wid===id);$$(`[data-act="heart"][data-id="${id}"],[data-act="pdpHeart"]`,app).forEach(h=>{if(h.dataset.act==='pdpHeart'&&top().params.id!==id)return;h.setAttribute('aria-pressed',on);h.innerHTML=ic(on?'heartf':'heart');h.classList.remove('pop');void h.offsetWidth;h.classList.add('pop');});}
A.heart=b=>toggleWish(b.dataset.id);
A.pdp=b=>go('pdp',{id:b.dataset.id});

/* ================= home ================= */
SCR.home={lt:1,title:()=>'Yema Watch Club',short:()=>L('Accueil','Home'),right:()=>bagBtn()+bellBtn(),
 ptr:()=>{rerender();toast(L('Sélection mise à jour','Selection updated'),{icon:'sparkle'});},
 render:()=>{const rec=recos().slice(0,6),m=W('nme'),act=S.orders.find(o=>!o.done);
 return `<div class="hhead"><div><span class="lbl">${greet()}</span><h1 class="lt-h" style="margin:4px 0 0">${esc(S.user.first)}</h1></div></div>
 ${storiesRow()}
 <div class="pad"><button class="drop" type="button" data-act="pdp" data-id="nme">${pic(m,0,{alt:false,eager:true})}<span class="dx"><span class="lbl g">${L('Édition limitée · 150 ex. numérotés','Limited · 150 numbered pieces')}</span><b class="h3">Navygraf Meteorite CMM.10</b><span class="small muted">${L('Cadran en météorite Muonionalusta','Muonionalusta meteorite dial')}</span><span class="pr">${eur(m.p)}</span></span></button>
 <div class="tiles">${act?`<button class="tile wide" type="button" data-act="order" data-no="${act.no}">${pic(W(act.items[0].wid),frontI(W(act.items[0].wid),act.items[0].o),{cls:'sq',alt:false}).replace('class="ph sq','style="width:44px;border-radius:10px;flex:none" class="ph sq')}<span style="flex:1"><span class="lbl g">${L('Commande en cours','Order in progress')}</span><b style="display:block;font-size:14px;margin-top:2px">${esc(STAT()[act.status].t)} · ${act.no}</b></span>${ic('chev','chev')}</button>`:''}
 <button class="tile" type="button" data-act="toColl" data-t="owned"><span class="t">${ic('watch')}${L('Ma Collection','My Collection')}</span><div class="n"><b>${S.owned.length}</b>${L('garde-temps','timepieces')}</div></button><button class="tile" type="button" data-act="toColl" data-t="wish"><span class="t">${ic('heart')}${L('Liste d’envies','Wishlist')}</span><div class="n"><b>${S.wish.length}</b>${L('sauvegardés','saved')}</div></button></div>
 <button class="essai" type="button" data-act="essai">${pic(rec[0].w,0,{alt:false})}<span class="ib">${ic('ar')}</span><span class="h2">${L('Essai virtuel','Virtual try-on')}</span><p>${L(`La ${esc(rec[0].w.n)} à votre poignet, en réalité augmentée.`,`The ${esc(rec[0].w.n)} on your wrist, in augmented reality.`)}</p><span class="link">${L('Essayer','Try it')}${ic('arrow')}</span></button></div>
 <div class="sec"><div class="sech"><h2 class="h2">${L('Pour vous','For you')}</h2><button class="link" type="button" data-act="editPrefs">${L('Modifier','Edit')}</button></div><div class="hscroll">${rec.map(x=>wcard(x.w,{why:x.r.slice(0,2).join(' · ')})).join('')}</div></div>
 <div class="sec"><div class="cercle"><div class="bg">${roomArt('cercle')}</div><span class="bdg" style="align-self:flex-start">${L('Exclusif','Exclusive')}</span><h2 class="h1">${L('Le Cercle des Collectionneurs','The Collectors’ Circle')}</h2><p>${L('Événements privés, lancements en avant-première et conciergerie horlogère.','Private events, early launches and a watch concierge.')}</p><button class="btn line" type="button" data-act="toClub">${L('Découvrir le Club','Discover the Club')}</button></div></div>
 <div class="sec"><div class="sech"><h2 class="h2">${L('Collections','Collections')}</h2><button class="link" type="button" data-act="toCol" data-k="">${L('Tout voir','See all')}</button></div><div class="hscroll">${COLS.map(c=>`<button class="emb" type="button" data-act="toCol" data-k="${c}">${pic(WATCHES.find(w=>w.col===c),0,{alt:false})}<b>${c}</b></button>`).join('')}</div></div>`;},
 mount:(el,p,e)=>{if(!S.pushed)setTimeout(()=>{if(top()!==e||sheets.length||S.pushed||NOSAVE)return;meteoritePush();},RM?600:2200);prewarm();}};
/* warm fonts, code paths and layout of the product page once, while idle */
let WARM=false;function prewarm(){if(WARM)return;WARM=true;(window.requestIdleCallback||(f=>setTimeout(f,1200)))(()=>{const d=document.createElement('section');d.className='scr off';d.innerHTML=`<div class="sc">${SCR.pdp.render({id:'nme',o:defO(W('nme'))})}</div>${SCR.pdp.after({id:'nme'})}`;d.querySelectorAll('img').forEach(i=>i.removeAttribute('src'));view.appendChild(d);void d.offsetHeight;d.remove();},{timeout:2500});}
function meteoritePush(){S.pushed=true;save();push({title:L('Navygraf Meteorite · 150 exemplaires','Navygraf Meteorite · 150 pieces'),body:L('Accès anticipé membres : cadran taillé dans une météorite.','Members’ early access: a dial cut from a meteorite.'),onTap:()=>{const n=S.notifs.find(x=>x.id==='n1');if(n)n.read=true;step(0);save();(S.sec.faceid?bioLock(L('Ouverture sécurisée','Secure opening')):Promise.resolve()).then(()=>{if(NAV.mode!=='tabs')enterTabs('home');go('pdp',{id:'nme',from:'push'});});}});}
A.toColl=b=>switchTab('collection',{tab:b.dataset.t});
A.essai=()=>startAR(recos()[0].w.id);
A.editPrefs=()=>go('prefs',{from:1});
A.toClub=()=>switchTab('club');
A.toCol=b=>{S.cat.col=b.dataset.k;S.cat.q='';save();switchTab('catalog',{});};

/* stories */
const STORIES=[
 {id:'nme',w:'nme',s:'1/150',bg:'radial-gradient(120% 70% at 50% 35%,#3A4B66,#0B1428 70%)',k:{fr:'Édition limitée',en:'Limited edition'},t:{fr:'Navygraf Meteorite CMM.10',en:'Navygraf Meteorite CMM.10'},x:{fr:'150 exemplaires numérotés. Chaque cadran est taillé dans la Muonionalusta, l’une des plus anciennes météorites connues.',en:'150 numbered pieces. Every dial is cut from Muonionalusta, one of the oldest known meteorites.'},cta:{fr:'Voir la pièce',en:'View the piece'},go:()=>go('pdp',{id:'nme'})},
 {id:'sbz',w:'sbz',s:'Bronze',bg:'radial-gradient(120% 70% at 50% 35%,#4B5A2E,#10170A 75%)',k:{fr:'Première série',en:'First batch'},t:{fr:'Superman Bronze CMM.10',en:'Superman Bronze CMM.10'},x:{fr:'Boîtier bronze de 38,5 mm. Première série de 50 montres par modèle, une par client.',en:'38.5 mm bronze case. First batch of 50 watches per model, one per customer.'},cta:{fr:'Découvrir',en:'Discover'},go:()=>go('pdp',{id:'sbz'})},
 {id:'ral',w:'ral',s:'Alpine',bg:'radial-gradient(120% 70% at 50% 35%,#1F5E96,#07162A 75%)',k:{fr:'Précommande',en:'Pre-order'},t:{fr:'Rallygraf Alpine Cup Series',en:'Rallygraf Alpine Cup Series'},x:{fr:'YEMA, chronométreur officiel de l’Alpine Elf Cup Series, signe un chronographe en hommage à l’esprit course d’Alpine.',en:'YEMA, Official Timekeeper of the Alpine Elf Cup Series, signs a chronograph in tribute to Alpine’s racing spirit.'},cta:{fr:'Précommander',en:'Pre-order'},go:()=>go('pdp',{id:'ral'})},
 {id:'club',w:'sh',i:2,s:'Club',bg:'radial-gradient(120% 70% at 50% 30%,#8A5A22,#1B1008 75%)',k:{fr:'Club VIP',en:'VIP Club'},t:{fr:'Exposition Héritage',en:'Heritage Exhibition'},x:{fr:'Une soirée réservée aux membres pour découvrir l’histoire de la Superman (événement fictif).',en:'A members-only evening on the history of the Superman (fictional event).'},cta:{fr:'Réserver',en:'Reserve'},go:()=>switchTab('club',{seg:'events'})}
];
function storiesRow(){return `<div class="stories hscroll" aria-label="Stories">${STORIES.map((st,i)=>`<button class="sto ${S.seenSt.includes(st.id)?'seen':''}" type="button" data-act="story" data-i="${i}" aria-label="Story : ${esc(tx(st.t))}"><span class="ring">${pic(W(st.w),st.i||0,{alt:false})}</span><small>${esc(tx(st.s))}</small></button>`).join('')}</div>`;}
A.story=b=>openStory(+b.dataset.i);
function openStory(i){
 const d=document.createElement('div');d.className='story';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');layer.appendChild(d);
 let cur=i,t0=0,paused=false,raf=0,down=0,y0=null,closed=false;const DU=5000;
 const draw=()=>{const st=STORIES[cur];if(!S.seenSt.includes(st.id)){S.seenSt.push(st.id);save();}d.style.background=st.bg;d.setAttribute('aria-label',tx(st.t));
  d.innerHTML=`<div class="sbars">${STORIES.map((_,j)=>`<i><b style="width:${j<cur?100:0}%"></b></i>`).join('')}</div><div class="shd"><span class="ai">Y</span><span><b>Yema Watch Club</b><small>${tx(st.k)}</small></span><button class="xbtn" type="button" data-s="x" aria-label="${L('Fermer','Close')}">${ic('close')}</button></div><button class="snav l" type="button" data-s="prev" aria-label="${L('Précédente','Previous')}"></button><button class="snav r" type="button" data-s="next" aria-label="${L('Suivante','Next')}"></button><div class="sbody">${pic(W(st.w),st.i||0,{full:true,eager:true})}<span class="lbl g">${tx(st.k)}</span><h2 class="h1">${tx(st.t)}</h2><p>${tx(st.x)}</p><button class="btn gold" type="button" data-s="go">${tx(st.cta)}${ic('arrow')}</button></div>`;markImgs(d);t0=performance.now();};
 const close=()=>{if(closed)return;closed=true;cancelAnimationFrame(raf);document.removeEventListener('keydown',kd,true);d.classList.add('out');setTimeout(()=>d.remove(),RM?0:230);const r=top().el&&$('.stories',top().el);if(r){const sl=r.scrollLeft;r.outerHTML=storiesRow();const n=$('.stories',top().el);if(n){n.scrollLeft=sl;markImgs(n);}}};
 const nav=k=>{if(k<0)k=0;if(k>=STORIES.length){close();return;}cur=k;draw();buzz(4);};
 const loop=t=>{if(closed)return;if(paused)t0+=16;const p=Math.min(1,(t-t0)/DU);const b=d.querySelectorAll('.sbars b')[cur];if(b)b.style.width=(p*100)+'%';if(p>=1)nav(cur+1);raf=requestAnimationFrame(loop);};
 const kd=e=>{if(e.key==='Escape'){e.stopPropagation();close();}else if(e.key==='ArrowRight')nav(cur+1);else if(e.key==='ArrowLeft')nav(cur-1);};
 document.addEventListener('keydown',kd,true);
 d.addEventListener('pointerdown',e=>{down=performance.now();y0=e.clientY;paused=true;});
 d.addEventListener('pointerup',e=>{paused=false;if(y0!=null&&e.clientY-y0>90)close();y0=null;});
 d.addEventListener('click',e=>{const b=e.target.closest('[data-s]');if(!b)return;const held=performance.now()-down>350;const k=b.dataset.s;if(k==='x')close();else if(k==='go'){const st=STORIES[cur];close();setTimeout(st.go,40);}else if(!held)nav(k==='prev'?cur-1:cur+1);});
 draw();raf=requestAnimationFrame(loop);
}

/* ================= catalogue ================= */
const SORTS=[['reco',{fr:'Recommandé',en:'Recommended'}],['asc',{fr:'Prix croissant',en:'Price: low to high'}],['desc',{fr:'Prix décroissant',en:'Price: high to low'}]];
const MVF=[['manu',{fr:'Manufacture (CMM)',en:'In-house (CMM)'}],['auto',{fr:'Automatique',en:'Automatic'}],['quartz',{fr:'Quartz & méca-quartz',en:'Quartz & meca-quartz'}]];
const SIZES=[38.5,39,39.5,40,41];
const hasSize=(w,s)=>opt(w,'size').v.some(v=>parseFloat(v[0])===s);
function filterW(c){const q=(c.q||'').trim().toLowerCase();let r=WATCHES.filter(w=>(!c.col||w.col===c.col)&&(!c.sizes.length||c.sizes.some(s=>hasSize(w,s)))&&(!c.mv.length||c.mv.includes(w.mv)));
 if(q)r=r.filter(w=>[w.n,w.col,w.cal||'',moveTxt(w),sizeTxt(w),w.st.join(' '),w.fr,w.en].join(' ').toLowerCase().includes(q));
 if(c.sort==='asc')r.sort((a,b)=>a.p-b.p);else if(c.sort==='desc')r.sort((a,b)=>b.p-a.p);else r.sort((a,b)=>score(b).s-score(a).s);return r;}
const nFilt=c=>c.sizes.length+c.mv.length+(c.sort!=='reco'?1:0);
function catGrid(){const r=filterW(S.cat);if(!r.length)return `<div class="empty">${emptyArt('search')}<h2 class="h2">${L('Aucun résultat','No results')}</h2><p>${S.cat.q?L(`Rien ne correspond à « ${esc(S.cat.q)} ».`,`Nothing matches “${esc(S.cat.q)}”.`):L('Aucune montre ne correspond à ces filtres.','No watch matches these filters.')}</p><button class="btn line sm" type="button" data-act="catReset">${L('Réinitialiser','Reset')}</button></div>`;return `<div class="grid2">${r.map(w=>wcard(w)).join('')}</div>`;}
const catCnt=()=>{const n=filterW(S.cat).length;return `<span><b>${n}</b> ${L('modèles','models')}</span><button class="link" type="button" data-act="catFilters">${ic('sliders')}${L('Filtrer & trier','Filter & sort')}${nFilt(S.cat)?` (${nFilt(S.cat)})`:''}</button>`;};
SCR.catalog={large:1,title:()=>L('Catalogue','Catalogue'),right:()=>bagBtn(),
 render:()=>`<label class="srch">${ic('search')}<input id="cq" type="search" value="${esc(S.cat.q)}" placeholder="${L('Modèle, calibre, taille…','Model, calibre, size…')}" aria-label="${L('Rechercher','Search')}" enterkeyhint="search" autocomplete="off"></label>
 <div class="seg" role="tablist" style="margin-top:12px">${[['',L('Tout','All')]].concat(COLS.map(c=>[c,c])).map(([k,l])=>`<button type="button" role="tab" aria-selected="${S.cat.col===k}" data-act="catCol" data-k="${k}">${l}</button>`).join('')}</div>
 ${OFF?`<span class="cache">${ic('wifioff')}${L('Catalogue en cache','Cached catalogue')}</span>`:''}<div class="cnt" id="catcnt">${catCnt()}</div><div id="catgrid">${catGrid()}</div>`,
 mount:el=>{const i=$('#cq',el);let t;i.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>{S.cat.q=i.value;save();top().ver=VER;reflow($('#catgrid',el));$('#catgrid',el).innerHTML=catGrid();$('#catcnt',el).innerHTML=catCnt();markImgs(el);},140);});i.addEventListener('keydown',e=>{if(e.key==='Enter')i.blur();});}};
A.catCol=b=>{S.cat.col=b.dataset.k;save();const el=top().el;$$('.seg button',el).forEach(x=>x.setAttribute('aria-selected',x===b));pills(el,top());reflow($('#catgrid',el));$('#catgrid',el).innerHTML=catGrid();$('#catcnt',el).innerHTML=catCnt();markImgs(el);top().ver=VER;buzz(4);};
A.catReset=()=>{S.cat={col:'',sort:'reco',sizes:[],mv:[],q:''};save();rerender();};
function filterHTML(t){const n=filterW(Object.assign({},t,{q:S.cat.q})).length;const ck=(on,a,k,l)=>`<button class="ckrow" type="button" role="checkbox" aria-checked="${on}" data-act="${a}" data-k="${k}">${l}<span class="ckb">${ic('check')}</span></button>`;
 return sheetHTML(L('Filtrer & trier','Filter & sort'),`<div class="fgrp"><span class="lbl">${L('Trier par','Sort by')}</span><div class="chips">${SORTS.map(([k,l])=>`<button class="chip" type="button" aria-pressed="${t.sort===k}" data-act="fSort" data-k="${k}">${tx(l)}</button>`).join('')}</div></div>
 <div class="fgrp"><span class="lbl">${L('Taille du boîtier','Case size')}</span><div class="chips">${SIZES.map(s=>`<button class="chip" type="button" aria-pressed="${t.sizes.includes(s)}" data-act="fSize" data-k="${s}">${String(s).replace('.',LANG==='fr'?',':'.')} mm</button>`).join('')}</div></div>
 <div class="fgrp"><span class="lbl">${L('Mouvement','Movement')}</span>${MVF.map(([k,l])=>ck(t.mv.includes(k),'fMv',k,tx(l))).join('')}</div>`,`<button class="btn ghost" type="button" data-act="fClear" style="flex:0 0 36%">${L('Effacer','Clear')}</button><button class="btn gold" type="button" data-act="fApply">${L('Voir','Show')} ${n} ${L('modèles','models')}</button>`);}
A.catFilters=()=>{const t=JSON.parse(JSON.stringify(S.cat));openSheet({label:L('Filtrer','Filter'),html:filterHTML(t),data:{t}});};
const fUpd=()=>{const o=topSheet();setSheet(o,filterHTML(o.data.t));buzz(4);};
A.fSort=b=>{topSheet().data.t.sort=b.dataset.k;fUpd();};
A.fSize=b=>{const t=topSheet().data.t,k=+b.dataset.k;t.sizes=t.sizes.includes(k)?t.sizes.filter(x=>x!==k):t.sizes.concat(k);fUpd();};
A.fMv=b=>{const t=topSheet().data.t,k=b.dataset.k;t.mv=t.mv.includes(k)?t.mv.filter(x=>x!==k):t.mv.concat(k);fUpd();};
A.fClear=()=>{topSheet().data.t={col:S.cat.col,sort:'reco',sizes:[],mv:[],q:S.cat.q};fUpd();};
A.fApply=()=>{const t=topSheet().data.t;S.cat=Object.assign(t,{q:S.cat.q});save();closeSheet();rerender();};

/* ================= product page ================= */
SCR.pdp={hero:1,tabs:false,bar:1,title:p=>W(p.id).n,short:p=>W(p.id).col,
 right:p=>`<button class="nbb" type="button" data-act="pdpHeart" aria-pressed="${S.wish.some(x=>x.wid===p.id)}" aria-label="${L('Liste d’envies','Wishlist')}">${ic(S.wish.some(x=>x.wid===p.id)?'heartf':'heart')}</button><button class="nbb" type="button" data-act="share" aria-label="${L('Partager','Share')}">${ic('share')}</button>${bagBtn()}`,
 render:p=>{const w=W(p.id);p.o=p.o||defO(w);const o=p.o,vs=views(w,o),pr=priceOf(w,o),t=tagOf(w);p.acc=p.acc||{};
 const acc=(k,ti,body)=>`<div class="acc ${p.acc[k]?'open':''}"><button type="button" data-act="acc" data-k="${k}" aria-expanded="${!!p.acc[k]}">${ti}${ic('plus')}</button><div class="ab"><div><div class="in">${body}</div></div></div></div>`;

 const vp=w.opts.filter(op=>op.v.length>1).map(op=>`<div class="vopt"><div class="lbl">${{size:L('Taille','Size'),strap:L('Bracelet','Strap'),cond:L('État','Condition')}[op.k]}<b>${esc(LANG==='en'?op.v[o[op.k]][1]:op.v[o[op.k]][0])}</b></div><div class="chips">${op.v.map((v,i)=>`<button class="chip" type="button" aria-pressed="${o[op.k]===i}" data-act="vSel" data-k="${op.k}" data-i="${i}">${esc(LANG==='en'?v[1]:v[0])}</button>`).join('')}</div></div>`).join('');
 return `<div class="gal" id="gal"><div class="track" id="track" tabindex="0" aria-label="${L('Photos du produit','Product photos')}">${vs.map((ix,j)=>`<div class="slide" aria-label="${tx(VIEWN[w.views[ix]])}" data-ix="${ix}">${j===0||p.slide?pic(w,ix,{full:true,eager:j===0,fp:j===0}):''}</div>`).join('')}</div><span class="vl" id="vl">${tx(VIEWN[w.views[vs[0]]])}</span><div class="dots">${vs.map((_,j)=>`<i class="${j?'':'on'}"></i>`).join('')}</div><span class="zoomhint">${ic('zin')}${L('Pincer ou double-toucher','Pinch or double-tap')}</span></div>
 <div class="pinfo"><div class="row" style="gap:8px"><span class="lbl">${esc(w.col)}</span>${t?`<span class="bdg">${esc(t)}</span>`:''}</div>
 <div class="ttl"><h1 class="h1">${esc(w.n)}</h1><span class="pr" data-tk="p${w.id}" data-v="${pr}">${eur(pr)}</span></div>
 <p class="p">${esc(tx(w))}</p>${vp}
 <button class="btn line" type="button" data-act="tryAR" style="margin-top:20px">${ic('ar')}${L('Essayer en réalité augmentée','Try on in AR')}</button>
 <div class="specs"><div class="spec">${ic('ruler')}<small>${L('Taille','Size')}</small><b>${esc(opt(w,'size').v[o.size][0])}</b></div><div class="spec">${ic('cog')}<small>${L('Mouvement','Movement')}</small><b>${esc(moveTxt(w))}</b></div><div class="spec">${ic(w.res?'clock':'shield')}<small>${w.res?L('Réserve','Reserve'):L('Garantie','Warranty')}</small><b>${w.res||L('2 ans','2 years')}</b></div></div>
 <div style="margin-top:20px">${acc('specs',L('Caractéristiques','Specifications'),`<div class="kv"><span>Collection</span><b>${esc(w.col)}</b></div><div class="kv"><span>${L('Taille(s)','Size(s)')}</span><b>${esc(sizeTxt(w))}</b></div><div class="kv"><span>${L('Mouvement','Movement')}</span><b>${esc(moveTxt(w))}</b></div><div class="kv"><span>Type</span><b>${esc(typeTxt(w))}</b></div>${w.res?`<div class="kv"><span>${L('Réserve de marche','Power reserve')}</span><b>${w.res}</b></div>`:''}${opt(w,'strap')?`<div class="kv"><span>${L('Bracelets','Straps')}</span><b>${esc(opt(w,'strap').v.map(v=>LANG==='en'?v[1]:v[0]).join(', '))}</b></div>`:''}<div class="kv"><span>${L('Garantie','Warranty')}</span><b>${L('2 ans internationale','2-year international')}</b></div><p class="small muted" style="margin:8px 0 0">${L('Seules les données publiées par YEMA sont reprises.','Only data published by YEMA is shown.')}</p>`)}
 ${acc('ship',L('Livraison & retours','Shipping & returns'),L('Livraison offerte et assurée, ou retrait en boutique. Retours sous 30 jours. (Conditions de démonstration.)','Free insured delivery or boutique pick-up. Returns within 30 days. (Demo terms.)'))}
 ${acc('vip',L('Avantages Club VIP','VIP Club benefits'),L('Accès anticipé aux éditions limitées, invitations aux événements et conseiller horloger dédié.','Early access to limited editions, event invitations and a dedicated watch advisor.'))}</div>
 <div class="list" style="margin-top:18px"><a class="li" href="${esc(w.url)}" target="_blank" rel="noopener" style="text-decoration:none">${ic('globe')}<span class="tx">${L('Voir sur yema.com','View on yema.com')}<small>${L('Fiche officielle du produit','Official product page')}</small></span>${ic('share','chev')}</a><button class="li" type="button" data-act="concierge">${ic('chat')}<span class="tx">${L('Conseil d’un expert','Ask an expert')}<small>${L('Conciergerie VIP · rendez-vous privé','VIP concierge · private appointment')}</small></span>${ic('chev','chev')}</button><button class="li" type="button" data-act="compare">${ic('compare')}<span class="tx">${L('Comparer','Compare')}</span>${ic('chev','chev')}</button><button class="li" type="button" data-act="stores">${ic('pin')}<span class="tx">${L('Trouver une boutique','Find a boutique')}</span>${ic('chev','chev')}</button></div></div>
 <div class="sec" id="simx" style="min-height:330px"></div>`;},
 after:p=>{const w=W(p.id),pr=priceOf(w,p.o||defO(w));return `<div class="cta"><div class="pl"><span>${w.pre?L('Précommande · expédition à la sortie','Pre-order · ships on release'):L('Livraison offerte · retours 30 jours','Free delivery · 30-day returns')}</span><b data-tk="c${w.id}" data-v="${pr}">${eur(pr)}</b></div><div class="bt"><button class="btn line" type="button" data-act="addCart">${ic('bagp')}${L('Ajouter au panier','Add to bag')}</button><button class="btn gold" type="button" data-act="buyNow">${w.pre?L('Précommander','Pre-order'):L('Acheter','Buy now')}</button></div></div>`;},
 mount:(el,p)=>{const w=W(p.id),tr=$('#track',el),gal=$('#gal',el),vs=views(w,p.o);const sc=$('.sc',el);
  el._th=Math.max(80,gal.offsetHeight-el.querySelector('.nb').offsetHeight-10);
  const dots=$$('.dots i',el);let raf;tr.addEventListener('scroll',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const i=Math.round(tr.scrollLeft/tr.clientWidth);dots.forEach((d,j)=>d.classList.toggle('on',i===j));$('#vl',el).textContent=tx(VIEWN[w.views[vs[i]||0]]);p.slide=i;});},{passive:true});
  if(p.slide)tr.scrollLeft=p.slide*tr.clientWidth;
  tr.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();tr.scrollBy({left:(e.key==='ArrowRight'?1:-1)*tr.clientWidth,behavior:RM?'auto':'smooth'});}});
  pinchZoom(tr);
  // warm the cache: the other photos of this product, then the similar products
  setTimeout(()=>{vs.slice(1).forEach(i=>{const im=new Image();im.decoding='async';im.src=src(w,i,true);});},400);
  const w2=W(p.id);setTimeout(()=>{$$('.slide:empty',el).forEach(sl=>{sl.innerHTML=pic(w2,+sl.dataset.ix,{full:true});});markImgs(el);const x=$('#simx',el);if(!x||x.childElementCount)return;const sim=WATCHES.filter(y=>y.id!==w2.id&&(y.col===w2.col||y.st.some(s=>w2.st.includes(s)))).slice(0,6);x.innerHTML=`<div class="sech"><h2 class="h2">${L('Vous aimerez aussi','You may also like')}</h2></div><div class="hscroll">${sim.map(y=>wcard(y)).join('')}</div>`;markImgs(x);},RM?0:DUR+120);
  LASTPDP=p.id;if(p.id==='nme')step(1);},
 unmount:el=>{if(el._ori)window.removeEventListener('deviceorientation',el._ori);}};
function reflow(g){if(!g||RM)return;g.classList.remove('reflow');void g.offsetWidth;g.classList.add('reflow');}
function pinchZoom(tr){let d0=0,img=null,sc=1;const reset=()=>{if(img){img.style.transition='transform .3s var(--ios)';img.style.transform='';const i=img;setTimeout(()=>{i.style.transition='';},320);}img=null;sc=1;};
 tr.addEventListener('touchstart',e=>{if(e.touches.length===2){const [a,b]=e.touches;d0=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);img=e.target.closest('.slide')&&e.target.closest('.slide').querySelector('img');if(img){const r=img.getBoundingClientRect();img.style.transformOrigin=`${(a.clientX+b.clientX)/2-r.left}px ${(a.clientY+b.clientY)/2-r.top}px`;img.style.transition='none';}}},{passive:true});
 tr.addEventListener('touchmove',e=>{if(e.touches.length===2&&img){e.preventDefault();const [a,b]=e.touches;sc=Math.max(1,Math.min(3,Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)/d0));img.style.transform=`scale(${sc})`;}},{passive:false});
 tr.addEventListener('touchend',e=>{if(e.touches.length<2&&img)reset();});
 tr.addEventListener('dblclick',e=>{const im=e.target.closest('.slide')&&e.target.closest('.slide').querySelector('img');if(!im)return;const z=im.dataset.z==='1';const r=im.getBoundingClientRect();im.style.transformOrigin=`${e.clientX-r.left}px ${e.clientY-r.top}px`;im.style.transform=z?'':'scale(2.2)';im.dataset.z=z?'':'1';buzz(5);});}
A.acc=b=>{const p=top().params,k=b.dataset.k;p.acc[k]=!p.acc[k];b.parentElement.classList.toggle('open',p.acc[k]);b.setAttribute('aria-expanded',!!p.acc[k]);};
A.vSel=b=>{const p=top().params;p.o=Object.assign({},p.o,{[b.dataset.k]:+b.dataset.i});p.slide=0;if(b.dataset.k==='strap')step(3);buzz(5);rerender();};
A.pdpHeart=()=>{const p=top().params;toggleWish(p.id,{o:p.o});};
A.share=async()=>{const w=W(top().params.id);const d={title:`YEMA ${w.n}`,text:L(`Je regarde la ${w.n} sur Yema Watch Club.`,`I’m looking at the ${w.n} on Yema Watch Club.`),url:w.url};try{if(navigator.share){await navigator.share(d);return;}}catch(e){if(e&&e.name==='AbortError')return;}try{await navigator.clipboard.writeText(`${d.text} ${d.url}`);toast(L('Lien copié','Link copied'),{icon:'share'});}catch(e){toast(L('Lien de la fiche prêt à partager','Product link ready to share'),{icon:'share'});}};
A.tryAR=()=>{const p=top().params;startAR(p.id,{o:p.o});};
A.stores=()=>go('stores');
A.concierge=()=>go('concierge');

/* compare (light, photos) */
function cmpHTML(d){const a=W(d.a),b=W(d.b);const rows=[['Collection',w=>w.col],[L('Taille','Size'),w=>sizeTxt(w)],[L('Mouvement','Movement'),w=>moveTxt(w)],['Type',w=>typeTxt(w)],[L('Prix','Price'),w=>eur(w.p)]];
 return sheetHTML(L('Comparer','Compare'),`<div class="seg" style="padding:0;margin:0 -20px;padding:0 20px">${WATCHES.filter(w=>w.id!==d.a).map(w=>`<button type="button" aria-selected="${w.id===d.b}" data-act="cmpPick" data-id="${w.id}">${esc(w.n)}</button>`).join('')}</div><div class="cmph">${[a,b].map(w=>`<div>${pic(w,0,{alt:false})}<b class="h3">${esc(w.n)}</b></div>`).join('')}</div>${rows.map(([l,f])=>{const va=f(a),vb=f(b);return `<div class="cmpr ${va!==vb?'diff':''}"><span>${esc(va)}</span><small>${l}</small><span>${esc(vb)}</span></div>`;}).join('')}`,`<button class="btn gold" type="button" data-act="cmpGo">${L('Voir la fiche','View product')}</button>`);}
A.compare=()=>{const a=W(top().params.id);const b=WATCHES.find(w=>w.id!==a.id&&w.col===a.col)||WATCHES.find(w=>w.id!==a.id);const d={a:a.id,b:b.id};openSheet({label:L('Comparer','Compare'),data:d,html:cmpHTML(d)});};
A.cmpPick=b=>{const o=topSheet();o.data.b=b.dataset.id;setSheet(o,cmpHTML(o.data));buzz(4);};
A.cmpGo=()=>{const d=topSheet().data;closeSheet();go('pdp',{id:d.b});};

/* ================= boutiques (geolocation with consent) ================= */
const STORES=[{id:'b1',n:{fr:'Boutique YEMA Paris',en:'YEMA Paris boutique'},t:{fr:'Boutique · conciergerie',en:'Boutique · concierge'},a:'12 rue du Faubourg-Saint-Honoré, 75008',h:'10:30–19:00',x:36,y:36},{id:'b2',n:{fr:'Horlogerie du Marais',en:'Horlogerie du Marais'},t:{fr:'Revendeur agréé',en:'Authorised dealer'},a:'5 rue des Archives, 75004',h:'11:00–19:30',x:66,y:57},{id:'b3',n:{fr:'Corner grand magasin',en:'Department store corner'},t:{fr:'Corner',en:'Corner'},a:'40 boulevard Haussmann, 75009',h:'10:00–20:30',x:52,y:30},{id:'b4',n:{fr:'Service après-vente',en:'After-sales service'},t:{fr:'Atelier',en:'Workshop'},a:'3 rue de Rivoli, 75001',h:'09:30–18:00',x:54,y:52}];
const ME={x:55,y:38};const km=s=>Math.hypot(s.x-ME.x,(s.y-ME.y)*.7)*.09;
SCR.stores={title:()=>L('Boutiques','Boutiques'),
 render:p=>{if(S.geo===null)return `<div class="pad"><div class="perm"><div class="pc" style="margin:10px 0 0"><div class="ico">${ic('pin')}</div><h1 class="h2">${L('Autoriser « Yema Club » à utiliser votre position ?','Allow “Yema Club” to use your location?')}</h1><p>${L('Uniquement pour trier les boutiques par distance. Rien n’est conservé.','Only to sort boutiques by distance. Nothing is stored.')}</p><button class="btn gold" type="button" data-act="geo" data-k="while">${L('Pendant l’utilisation','While using the app')}</button><button class="btn line" type="button" data-act="geo" data-k="once">${L('Une seule fois','Allow once')}</button><button class="btn" type="button" data-act="geo" data-k="no" style="margin-top:8px;color:#8A8F99">${L('Ne pas autoriser','Don’t allow')}</button></div></div></div>`;
 const on=S.geo!=='no';const list=STORES.slice().sort((a,b)=>on?km(a)-km(b):tx(a.n).localeCompare(tx(b.n)));p.sel=p.sel||list[0].id;
 return `<div class="map"><svg viewBox="0 0 100 70" preserveAspectRatio="none" aria-hidden="true"><rect width="100" height="70" fill="#15253E"/>${Array.from({length:12},(_,i)=>`<path d="M${i*9-4} 0 L${i*9+8} 70" stroke="#1F3252" stroke-width=".5"/><path d="M0 ${i*6} L100 ${i*6+4}" stroke="#1F3252" stroke-width=".5"/>`).join('')}<path d="M0 44 C 18 40, 28 50, 42 46 S 62 36, 74 42 S 92 52, 100 48" stroke="#2C5A86" stroke-width="3.2" fill="none"/><path d="M8 30 L92 26 M50 0 L54 70 M20 62 L80 10" stroke="#2A3E60" stroke-width="1.1"/></svg>${on?`<span class="me-dot" style="left:${ME.x}%;top:${ME.y/0.7}%"></span>`:''}${list.map((s,i)=>`<button class="pin ${p.sel===s.id?'on':''}" type="button" style="left:${s.x}%;top:${s.y/0.7}%" data-act="storeSel" data-id="${s.id}" aria-label="${esc(tx(s.n))}"><span>${i+1}</span></button>`).join('')}</div><p class="small muted pad" style="margin:8px 0 12px">${on?L('Position simulée · ','Simulated position · '):''}${L('adresses illustratives','illustrative addresses')}</p>
 <div class="pad">${list.map((s,i)=>`<div class="card store ${p.sel===s.id?'on':''}" id="st-${s.id}"><div class="row"><div class="sp"><span class="lbl">${i+1} · ${tx(s.t)}</span><h3 class="h3" style="margin-top:3px">${esc(tx(s.n))}</h3><small class="muted">${esc(s.a)} · ${s.h}</small></div>${on?`<b style="color:var(--gold2)">${km(s).toFixed(1).replace('.',LANG==='fr'?',':'.')} km</b>`:''}</div><div class="acts"><button class="btn ghost sm" type="button" data-act="route">${ic('nav')}${L('Itinéraire','Directions')}</button><button class="btn line sm" type="button" data-act="concierge">${ic('cal')}${L('Rendez-vous','Book')}</button></div></div>`).join('')}</div>`;}};
A.geo=b=>{S.geo=b.dataset.k;save();rerender();};
A.storeSel=b=>{top().params.sel=b.dataset.id;rerender();};
A.route=()=>toast(L('Ouverture de Plans (démo)','Opening Maps (demo)'),{icon:'nav'});
