
/* ================= commerce: bag, checkout (simulated payment), orders, registration ================= */
const ckey=(id,o)=>id+':'+[o.size||0,o.strap||0,o.cond||0].join('');
const subtotal=()=>S.cart.reduce((a,c)=>a+priceOf(W(c.wid),c.o)*c.qty,0);
const rndSerial=()=>'YM-'+(1000+Math.floor(Math.random()*8999))+'-'+'ABCDEFGHJKLMNPRSTUVWXYZ'.split('').sort(()=>Math.random()-.5).slice(0,3).join('');
function addToCart(id,o,quiet){const w=W(id);o=Object.assign(defO(w),o||{});const k=ckey(id,o);const it=S.cart.find(c=>c.k===k);
 if(it){if(it.qty>=maxQty(w)){if(!quiet)toast(L('Quantité maximale atteinte pour ce modèle','Maximum quantity reached for this model'),{icon:'info'});return false;}it.qty++;}else S.cart.push({k,wid:id,o:Object.assign({},o),qty:1});
 save();badges();buzz([8,30,8]);return true;}
function flyToBag(el){if(RM||NOSAVE)return;const img=el&&el.querySelector('.gal .slide img');const bag=top().el&&top().el.querySelector('[data-act="cart"]');if(!img||!bag)return;const ar=app.getBoundingClientRect(),a=img.getBoundingClientRect(),b=bag.getBoundingClientRect();const c=img.cloneNode();c.style.cssText=`position:absolute;z-index:99;left:${a.left-ar.left}px;top:${a.top-ar.top}px;width:${a.width}px;height:${a.height}px;object-fit:contain;pointer-events:none;opacity:1`;layer.appendChild(c);
 const dx=b.left+b.width/2-(a.left+a.width/2),dy=b.top+b.height/2-(a.top+a.height/2);const bump=()=>{c.remove();if(!bag.isConnected)return;bag.animate([{transform:'scale(1)'},{transform:'scale(1.35) rotate(-8deg)',offset:.35},{transform:'scale(.92)',offset:.7},{transform:'none'}],{duration:520,easing:'ease-out'});buzz([6,30,12]);};c.animate([{transform:'none',opacity:1},{transform:`translate(${dx*.5}px,${dy*.3-60}px) scale(.5)`,opacity:1,offset:.55},{transform:`translate(${dx}px,${dy}px) scale(.06)`,opacity:.3}],{duration:620,easing:'cubic-bezier(.5,0,.2,1)'}).finished.then(bump,()=>c.remove());}
A.addCart=()=>{const p=top().params;if(addToCart(p.id,p.o)){flyToBag(top().el);setTimeout(()=>toast(L('Ajouté au panier','Added to bag'),{icon:'bag',act:{label:L('Voir','View'),fn:openCart}}),RM?0:450);}};
A.buyNow=()=>{const p=top().params;const w=W(p.id);const o=Object.assign(defO(w),p.o||{});if(!S.cart.some(c=>c.k===ckey(p.id,o)))addToCart(p.id,o,true);openCheckout();};
function openCheckout(){if(!S.cart.length){openCart();return;}if(!needNet())return;closeAllSheets();go('checkout',{step:1,ship:'home',pay:null});}

/* bag sheet */
function cartHTML(){if(!S.cart.length)return sheetHTML(L('Panier','Bag'),`<div class="empty" style="padding-top:10px">${emptyArt('bag')}<h2 class="h2">${L('Votre panier est vide','Your bag is empty')}</h2><p>${L('Ajoutez une montre depuis sa fiche produit.','Add a watch from its product page.')}</p><button class="btn gold sm" type="button" data-act="goCat">${L('Explorer le catalogue','Explore the catalogue')}</button></div>`);
 const st=subtotal();
 return sheetHTML(L('Panier','Bag'),`${S.cart.map((c,i)=>{const w=W(c.wid);return `<div class="ci">${pic(w,frontI(w,c.o),{alt:false})}<div class="x"><span class="lbl">${esc(w.col)}${w.pre?' · '+L('Précommande','Pre-order'):''}</span><div class="h3">${esc(w.n)}</div><small>${esc(optLine(w,c.o))}</small><div class="row"><span class="qty"><button type="button" data-act="qty" data-i="${i}" data-d="-1" aria-label="${L('Retirer un','Remove one')}">${ic(c.qty>1?'minus':'trash')}</button><b>${c.qty}</b><button type="button" data-act="qty" data-i="${i}" data-d="1" aria-label="${L('Ajouter un','Add one')}" ${c.qty>=maxQty(w)?'disabled style="opacity:.35"':''}>${ic('plus')}</button></span><span class="sp"></span><b>${eur(priceOf(w,c.o)*c.qty)}</b></div></div></div>`;}).join('')}
 <div class="sum" style="margin-top:8px"><div class="kv"><span>${L('Sous-total','Subtotal')}</span><b>${eur(st)}</b></div><div class="kv"><span>${L('Livraison','Delivery')}</span><b style="color:var(--ok)">${L('Offerte','Free')}</b></div><div class="kv t"><span>Total</span><b data-tk="cart" data-v="${st}">${eur(st)}</b></div></div>
 <p class="small muted" style="margin:10px 0 0;display:flex;gap:6px;align-items:center">${ic('lock')}${L('Paiement simulé — aucun débit','Simulated payment — no charge')}</p>`,`<button class="btn gold" type="button" data-act="checkout">${L('Commander','Checkout')} · ${eur(st)}</button>`,`${cartN()} ${cartN()>1?L('articles','items'):L('article','item')}`);}
function openCart(){closeAllSheets();openSheet({label:L('Panier','Bag'),html:cartHTML()});}
A.cart=()=>openCart();
A.goCat=()=>{closeAllSheets();switchTab('catalog');};
A.qty=b=>{const i=+b.dataset.i,d=+b.dataset.d,c=S.cart[i];if(!c)return;if(d<0&&c.qty<=1){const old=S.cart.slice();S.cart.splice(i,1);save();badges();setSheet(topSheet(),cartHTML());toast(L('Retiré du panier','Removed from bag'),{icon:'trash',act:{label:L('Annuler','Undo'),fn:()=>{S.cart=old;save();badges();if(topSheet())setSheet(topSheet(),cartHTML());}}});return;}
 if(d>0&&c.qty>=maxQty(W(c.wid)))return;c.qty+=d;save();badges();buzz(5);setSheet(topSheet(),cartHTML());};
A.checkout=()=>openCheckout();

/* checkout: 3 short steps */
const STEPN=[{fr:'Livraison',en:'Delivery'},{fr:'Paiement',en:'Payment'},{fr:'Récapitulatif',en:'Review'}];
const addr=()=>S.addresses.find(a=>a.def)||S.addresses[0];
const shipTxt=p=>p.ship==='store'?L('Retrait en boutique YEMA Paris (illustratif)','Pick-up at YEMA Paris boutique (illustrative)'):`${addr().l}, ${addr().c}`;
const payTxt=p=>p.pay==='apple'?L('Apple Pay (démo)','Apple Pay (demo)'):L('Carte enregistrée •••• 4242 (démo)','Saved card •••• 4242 (demo)');
SCR.checkout={modal:1,tabs:false,solid:1,bar:1,title:p=>tx(STEPN[p.step-1]),closeLbl:()=>L('Annuler','Cancel'),
 render:p=>{const st=subtotal();const bars=`<div class="steps3" aria-label="${L('Étape','Step')} ${p.step}/3">${[1,2,3].map(i=>`<i class="${i<=p.step?'on':''}"></i>`).join('')}</div>`;
 const radio=(k,v,t,s,act)=>`<button class="opc" type="button" role="radio" aria-checked="${p[k]===v}" data-act="${act}" data-v="${v}"><span class="rd"></span><span style="flex:1">${t}<small>${s}</small></span></button>`;
 let b='';
 if(p.step===1)b=`<div class="pad"><h2 class="h2" style="margin-bottom:12px">${L('Comment souhaitez-vous la recevoir ?','How would you like to receive it?')}</h2>${radio('ship','home',`<b>${L('Livraison à domicile','Home delivery')}</b>`,`${L('Offerte et assurée · 2 à 3 jours ouvrés','Free and insured · 2–3 working days')}<br>${esc(addr().l)}, ${esc(addr().c)}`,'ckShip')}${radio('ship','store',`<b>${L('Retrait en boutique YEMA Paris','Pick-up at YEMA Paris boutique')}</b>`,L('Sous 48 h · essayage sur place · adresse illustrative','Within 48 h · try it on site · illustrative address'),'ckShip')}<p class="small muted">${L('Adresse préremplie depuis votre compte (fictive).','Address prefilled from your account (fictional).')}</p></div>`;
 else if(p.step===2)b=`<div class="pad"><div class="simu">${ic('shield')}${L('Paiement simulé — aucun débit, aucune donnée bancaire saisie.','Simulated payment — no charge, no card details entered.')}</div><h2 class="h2" style="margin-bottom:12px">${L('Moyen de paiement','Payment method')}</h2>${radio('pay','apple',`<b>Apple Pay ${L('(démo)','(demo)')}</b>`,L('Validation par Face ID simulée','Simulated Face ID approval'),'ckPay')}${radio('pay','card',`<b>${L('Carte enregistrée •••• 4242 (démo)','Saved card •••• 4242 (demo)')}</b>`,L('Carte fictive du compte démo','Fictional card from the demo account'),'ckPay')}</div>`;
 else b=`<div class="pad">${S.cart.map(c=>{const w=W(c.wid);return `<div class="ci">${pic(w,frontI(w,c.o),{alt:false})}<div class="x"><div class="h3">${esc(w.n)}</div><small>${esc(optLine(w,c.o))} · ${L('Qté','Qty')} ${c.qty}</small><b style="display:block;margin-top:6px">${eur(priceOf(w,c.o)*c.qty)}</b></div></div>`;}).join('')}
 <div class="card sum" style="padding:6px 14px;margin-top:10px"><div class="kv"><span>${L('Livraison','Delivery')}</span><b>${esc(shipTxt(p))}</b></div><div class="kv"><span>${L('Paiement','Payment')}</span><b>${esc(payTxt(p))}</b></div><div class="kv"><span>${L('Sous-total','Subtotal')}</span><b>${eur(st)}</b></div><div class="kv"><span>${L('Frais de port','Shipping')}</span><b style="color:var(--ok)">${L('Offerts','Free')}</b></div><div class="kv t"><span>Total</span><b>${eur(st)}</b></div></div>
 <div class="simu" style="margin-top:12px">${ic('shield')}${L('Paiement simulé — aucun débit','Simulated payment — no charge')}</div></div>`;
 return bars+b;},
 after:p=>{const st=subtotal();const lbl=p.step<3?L('Continuer','Continue'):L(`Payer ${eur(st)}`,`Pay ${eur(st)}`);return `<div class="cta"><div class="pl"><span>${tx(STEPN[p.step-1])} · ${p.step}/3</span><b data-tk="ck" data-v="${st}">${eur(st)}</b></div><div class="bt">${p.step>1?`<button class="btn ghost" type="button" data-act="ckPrev" style="flex:0 0 30%">${L('Retour','Back')}</button>`:''}<button class="btn ${p.step===3&&p.pay==='apple'?'black':'gold'}" type="button" data-act="ckNext" ${p.step===2&&!p.pay?'disabled':''} id="cknext">${p.step===3&&p.pay==='apple'?ic('apple'):''}${lbl}</button></div></div>`;},
 mount:el=>{const n=$('.nt',el);if(n)n.style.opacity=1;}};
A.ckShip=b=>{top().params.ship=b.dataset.v;buzz(5);rerender();};
A.ckPay=b=>{top().params.pay=b.dataset.v;buzz(5);rerender();};
A.ckPrev=()=>{const p=top().params;p.step=Math.max(1,p.step-1);rerender();};
A.ckNext=b=>{const p=top().params;if(p.step<3){if(p.step===2&&!p.pay)return;p.step++;buzz(5);rerender();return;}
 if(!needNet())return;b.classList.add('loading');b.disabled=true;
 (p.pay==='apple'?bioLock(L('Apple Pay · paiement simulé','Apple Pay · simulated payment')):wait(RM?100:1100)).then(()=>placeOrder(p));};
const STAT=o=>{const pick=o&&o.ship==='store';return[{t:L('Confirmée','Confirmed'),s:L('Paiement simulé accepté','Simulated payment accepted')},{t:L('Préparée à l’atelier','Prepared at the workshop'),s:L('Contrôle et emballage en Franche-Comté','Checked and packed in Franche-Comté')},{t:pick?L('Prête en boutique','Ready in boutique'):L('Expédiée','Shipped'),s:pick?L('Vous pouvez venir la retirer','You can collect it'):L('Transporteur assuré, suivi en temps réel','Insured carrier, live tracking')},{t:pick?L('Retirée','Collected'):L('Livrée','Delivered'),s:L('Enregistrez-la dans Ma Collection','Register it in My Collection')}];};
function placeOrder(p){const no='YW-'+String(new Date().getFullYear()).slice(2)+'-'+(4000+Math.floor(Math.random()*5999));
 const o={no,items:S.cart.map(c=>({wid:c.wid,o:c.o,qty:c.qty,price:priceOf(W(c.wid),c.o)})),total:subtotal(),ship:p.ship,addr:shipTxt(p),pay:p.pay,status:0,ts:[Date.now()],reg:[],done:false};
 S.orders.unshift(o);S.cart=[];S.notifs.unshift({id:'n'+Date.now(),k:'order',ts:Date.now(),read:false,to:['order',{no}],t:{fr:`Commande ${no} confirmée`,en:`Order ${no} confirmed`},b:{fr:'Merci ! Suivez sa préparation et sa livraison.',en:'Thank you! Follow its preparation and delivery.'}});
 save();buzz([12,40,24]);replace('order',{no,fresh:1});}

/* order tracking */
const orderOf=no=>S.orders.find(o=>o.no===no);
SCR.order={title:p=>p.no,short:()=>L('Commande','Order'),
 render:p=>{const o=orderOf(p.no);if(!o)return `<div class="empty"><h2 class="h2">${L('Commande introuvable','Order not found')}</h2></div>`;const ST=STAT(o);
 const eta=new Date(o.ts[0]+3*D);
 return `${p.fresh?`<div class="ok-hero"><div class="okmark"><svg viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21l7 7 15-16"/></svg></div><h1 class="h1">${L(`Merci, ${esc(S.user.first)}`,`Thank you, ${esc(S.user.first)}`)}</h1><p class="p">${L('Votre commande est confirmée. Paiement simulé : aucun débit.','Your order is confirmed. Simulated payment: no charge.')}</p></div>`:''}
 <div class="card pad" style="margin:16px 18px 0;padding:6px 14px"><div class="kv"><span>${L('N° de commande','Order no.')}</span><b>${o.no}</b></div><div class="kv"><span>Total</span><b>${eur(o.total)}</b></div><div class="kv"><span>${o.ship==='store'?L('Retrait','Pick-up'):L('Livraison','Delivery')}</span><b>${esc(o.addr)}</b></div><div class="kv"><span>${L('Estimation','Estimated')}</span><b>${fdate(eta,{weekday:'short',day:'numeric',month:'short'})}</b></div></div>
 <div class="sech" style="margin-top:22px"><h2 class="h2">${L('Suivi','Tracking')}</h2></div>
 <div class="tl">${ST.map((s,i)=>`<div class="st ${i<=o.status?'done':''} ${i===o.status?'cur':''}"><b>${s.t}</b><small>${i<=o.status?`${fdate(o.ts[i]||Date.now(),{day:'numeric',month:'short'})} · ${new Date(o.ts[i]||Date.now()).toTimeString().slice(0,5)} · `:''}${s.s}</small></div>`).join('')}</div>
 ${o.status<3?`<div class="pad"><button class="btn line" type="button" data-act="advance" data-no="${o.no}">${ic('arrow')}${L('Simuler l’étape suivante','Simulate next step')}</button><p class="small muted center" style="margin-top:8px">${L('Démo : fait avancer la commande sans attendre.','Demo: moves the order forward instantly.')}</p></div>`:''}
 <div class="sech" style="margin-top:22px"><h2 class="h2">${L('Articles','Items')}</h2></div><div class="pad">${o.items.map((it,i)=>{const w=W(it.wid);const oid=o.reg[i];return `<div class="card ci" style="padding:12px;margin-bottom:10px;border:0">${pic(w,frontI(w,it.o),{alt:false})}<div class="x"><div class="h3">${esc(w.n)}</div><small>${esc(optLine(w,it.o))}${it.qty>1?' · ×'+it.qty:''}</small>${o.status<3?`<small style="color:var(--gold3)">${L('Enregistrable à la livraison','Can be registered on delivery')}</small>`:oid?`<button class="btn ghost sm" type="button" data-act="watch" data-oid="${oid}" style="margin-top:8px">${ic('check')}${L('Dans Ma Collection','In My Collection')}</button>`:`<button class="btn gold sm" type="button" data-act="register" data-no="${o.no}" data-i="${i}" style="margin-top:8px">${ic('shield')}${L('Enregistrer dans Ma Collection','Register in My Collection')}</button>`}</div></div>`;}).join('')}
 <div class="list"><button class="li" type="button" data-act="orderInvoice" data-no="${o.no}">${ic('file')}<span class="tx">${L('Facture','Invoice')}<small>${L('Document illustratif','Illustrative document')}</small></span>${ic('chev','chev')}</button><button class="li" type="button" data-act="concierge">${ic('chat')}<span class="tx">${L('Une question ? Conciergerie','A question? Concierge')}</span>${ic('chev','chev')}</button></div></div>`;},
 mount:(el,p)=>{if(p.fresh&&!p.cf){p.cf=1;setTimeout(()=>confetti(.5,.22),250);}}};
A.order=b=>go('order',{no:b.dataset.no});
A.advance=b=>{const o=orderOf(b.dataset.no);if(!o||o.status>=3)return;o.status++;o.ts[o.status]=Date.now();const s=STAT(o)[o.status];
 S.notifs.unshift({id:'n'+Date.now(),k:'order',ts:Date.now(),read:false,to:['order',{no:o.no}],t:{fr:`${s.t} · ${o.no}`,en:`${s.t} · ${o.no}`},b:{fr:s.s,en:s.s}});save();buzz([10,30,10]);rerender();
 if(o.status===3){toast(L('Livrée ! Enregistrez-la dans Ma Collection','Delivered! Register it in My Collection'),{icon:'box'});setTimeout(()=>{const r=top().el&&top().el.querySelector('[data-act="register"]');if(r)r.scrollIntoView({block:'center',behavior:RM?'auto':'smooth'});},200);}else toast(s.t,{icon:'box'});};
function invoiceHTML(no,items,total,date){return `<div class="inv-doc"><div class="row" style="justify-content:space-between;align-items:flex-start"><div><h4>YEMA</h4><div style="font-size:10px;letter-spacing:.12em;color:#7A7F8A">${L('FACTURE ILLUSTRATIVE','ILLUSTRATIVE INVOICE')}</div></div><div style="text-align:right;font-size:11px"><b>${no}</b><br>${fdate(date)}</div></div><div style="margin-top:12px;font-size:11.5px"><b>${esc(S.user.first)} ${esc(S.user.last)}</b><br>${esc(S.user.email)}</div><table>${items.map(it=>{const w=W(it.wid);return `<tr><td>${esc(w.n)}<br><span style="color:#7A7F8A;font-size:10.5px">${esc(optLine(w,it.o))}${it.serial?' · N° '+it.serial:''}</span></td><td>${eur((it.price||w.p)*(it.qty||1))}</td></tr>`;}).join('')}<tr><td>${L('dont TVA 20 %','incl. VAT 20%')}</td><td>${eur(Math.round(total-total/1.2))}</td></tr><tr class="tot"><td>Total</td><td>${eur(total)}</td></tr></table><span class="stamp">${L('Paiement simulé · document de démonstration','Simulated payment · demo document')}</span></div>`;}
A.orderInvoice=b=>{const o=orderOf(b.dataset.no);openSheet({label:L('Facture','Invoice'),html:sheetHTML(L('Facture','Invoice'),invoiceHTML(o.no,o.items,o.total,o.ts[0]))});};

/* registration with authenticity check (after delivery, or a watch bought elsewhere) */
function regHTML(d){const w=W(d.wid);
 if(!d.run)return sheetHTML(L('Enregistrer une montre','Register a watch'),`<p class="p" style="margin-top:0">${L('Ajoutez un garde-temps YEMA : son authenticité est vérifiée auprès du registre de la maison.','Add a YEMA timepiece: its authenticity is checked against the house register.')}</p>
 <label class="fld"><span>${L('Modèle','Model')}</span><div class="inp"><select id="rgm">${WATCHES.map(x=>`<option value="${x.id}" ${x.id===d.wid?'selected':''}>${esc(x.n)}</option>`).join('')}</select></div></label>
 <label class="fld"><span>${L('Numéro de série','Serial number')}<button type="button" class="link" style="font-size:12px" data-act="rgDemo">${L('Numéro démo','Demo number')}</button></span><div class="inp" id="rgw"><input id="rgs" value="${esc(d.serial||'')}" placeholder="YM-1234-ABC" autocomplete="off" spellcheck="false" style="text-transform:uppercase"></div><small class="ferr" id="rge"></small></label>`,`<button class="btn gold" type="button" data-act="rgGo">${ic('shield')}${L('Vérifier l’authenticité','Verify authenticity')}</button>`);
 const items=[L('Numéro de série reconnu','Serial number recognised')+' · '+esc(d.serial),`${esc(w.n)} · ${esc(optLine(w,d.o))}`,L('Registre de production YEMA','YEMA production register'),L('Garantie internationale de 2 ans activée','2-year international warranty activated'),L('Facture ajoutée au coffre','Invoice added to the vault')];
 return sheetHTML(d.done?L('Authenticité vérifiée','Authenticity verified'):L('Vérification…','Verifying…'),`<div class="verif"><div class="rg2">${pic(w,frontI(w,d.o),{alt:false})}<svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="56" fill="none" stroke="rgba(255,255,255,.12)" stroke-width="3"/><circle class="arc" cx="60" cy="60" r="56" fill="none" stroke="var(--gold)" stroke-width="3" stroke-linecap="round" transform="rotate(-90 60 60)"/></svg></div><ol>${items.map((t,i)=>`<li class="${i<d.k?'on':''}${i===d.k-1?' nw':''}"><i>${i<d.k?ic('check'):''}</i>${t}</li>`).join('')}</ol></div>`,d.done?`<button class="btn gold" type="button" data-act="rgView">${L('Voir dans Ma Collection','View in My Collection')}</button>`:'');}
function openRegister(o){const d=Object.assign({wid:'sh',o:null,serial:'',run:false,k:0},o||{});d.o=d.o||defO(W(d.wid));const s=openSheet({label:L('Enregistrer','Register'),html:regHTML(d),data:d});if(d.run)runVerify(s);return s;}
A.register=b=>{const o=orderOf(b.dataset.no),i=+b.dataset.i,it=o.items[i];if(!needNet())return;openRegister({wid:it.wid,o:it.o,serial:rndSerial(),run:true,order:o.no,idx:i,price:it.price});};
A.addWatch=()=>openRegister({});
A.rgDemo=()=>{$('#rgs').value=rndSerial();};
A.rgGo=()=>{const s=topSheet(),d=s.data;const v=$('#rgs').value.trim().toUpperCase();d.wid=$('#rgm').value;d.o=defO(W(d.wid));if(!/^YM-\d{4}-[A-Z]{3}$/.test(v)){$('#rgw').classList.add('err');$('#rge').textContent=L('Format attendu : YM-1234-ABC','Expected format: YM-1234-ABC');buzz([20,40,20]);return;}if(!needNet())return;d.serial=v;d.run=true;runVerify(s);};
function runVerify(s){const d=s.data;d.k=0;d.done=false;setSheet(s,regHTML(d));const tick=()=>{if(!sheets.includes(s))return;d.k++;if(d.k>=5){d.done=true;commitReg(d);buzz([12,40,24]);setTimeout(()=>confetti(.5,.4),100);}setSheet(s,regHTML(d));if(!d.done)setTimeout(tick,RM?60:380);};setTimeout(tick,RM?60:450);}
function commitReg(d){const w=W(d.wid),today=new Date(),end=new Date(today);end.setFullYear(end.getFullYear()+2);const oid='o'+Date.now();
 S.owned.unshift({oid,wid:w.id,o:d.o,serial:d.serial,date:iso(today),dealer:d.order?{fr:`Commande ${d.order}`,en:`Order ${d.order}`}:{fr:'Enregistrée par le propriétaire',en:'Registered by the owner'},wEnd:iso(end),price:d.price||priceOf(w,d.o),order:d.order||null,
  hist:[{t:{fr:'Achat',en:'Purchase'},d:iso(today),x:d.order?{fr:`Commande ${d.order}, authenticité vérifiée. Garantie 2 ans activée.`,en:`Order ${d.order}, authenticity verified. 2-year warranty activated.`}:{fr:'Authenticité vérifiée auprès du registre YEMA.',en:'Authenticity verified with the YEMA register.'}}],notes:''});
 if(d.order){const o=orderOf(d.order);o.reg[d.idx]=oid;o.done=o.items.every((_,i)=>o.reg[i]);}
 d.oid=oid;save();step(5);if(top().name==='order'||top().name==='collection')setTimeout(()=>{if(!sheets.length||topSheet().data!==d)rerender();},10);}
A.rgView=()=>{const d=topSheet().data;closeSheet();setStack('collection',[['collection',{tab:'owned'}],['watch',{oid:d.oid}]]);};

/* orders list (Profil) */
SCR.orders={title:()=>L('Mes commandes','My orders'),short:()=>L('Commandes','Orders'),
 render:()=>S.orders.length?`<div class="pad">${S.orders.map(o=>{const w=W(o.items[0].wid);return `<button class="ordc" type="button" data-act="order" data-no="${o.no}">${pic(w,frontI(w,o.items[0].o),{alt:false})}<span style="flex:1;min-width:0"><b style="display:block">${o.no}</b><small class="muted">${fdate(o.ts[0],{day:'numeric',month:'short'})} · ${o.items.length} ${L('article(s)','item(s)')} · ${eur(o.total)}</small><span class="bdg" style="margin-top:6px">${STAT(o)[o.status].t}</span></span>${ic('chev','chev')}</button>`;}).join('')}</div>`:`<div class="empty">${emptyArt('bag')}<h2 class="h2">${L('Aucune commande','No orders yet')}</h2><p>${L('Vos achats et leur suivi apparaîtront ici.','Your purchases and their tracking will appear here.')}</p><button class="btn gold sm" type="button" data-act="goCat">${L('Explorer le catalogue','Explore the catalogue')}</button></div>`};
A.orders=()=>go('orders');
