
/* ================= AR try-on: camera permission (#10), try-on (#9), bracelet & size in AR (#20) ================= */
const CAM={stream:null,granted:false};
function startAR(id,o){o=(o&&o.o)||null;if(CAM.granted)go('ar',{id,live:true,o});else go('camera',{id,o,state:'ask'});}
function getCam(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)return Promise.reject({name:'NotSupportedError'});let late=false;const gp=navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});gp.then(s=>{if(late)s.getTracks().forEach(t=>t.stop());},()=>{});return Promise.race([gp,new Promise((_,rej)=>setTimeout(()=>{late=true;rej({name:'TimeoutError'});},20000))]);}
function stopCam(){if(CAM.stream){CAM.stream.getTracks().forEach(t=>t.stop());CAM.stream=null;}}
SCR.camera={modal:1,tabs:false,cls:'perm',title:()=>L('Essai en RA','AR try-on'),closeIc:'back',closeLbl:()=>L('Produit','Product'),
 render:p=>{const w=W(p.id);
 if(p.state==='denied'){const nf=p.err==='NotFoundError'||p.err==='OverconstrainedError',ns=p.err==='NotSupportedError';
  return `<div class="pc" role="alert"><div class="ico">${ic('camoff')}</div><h1 class="h2">${L('Accès refusé','Access denied')}</h1><p>${nf?L('Aucune caméra détectée sur cet appareil. Le mode démo affiche la montre sur un poignet illustré.','No camera found on this device. Demo mode shows the watch on an illustrated wrist.'):ns?L('Ce navigateur ne donne pas accès à la caméra. Essayez le mode démo.','This browser does not allow camera access. Try demo mode.'):L('Pour l’essai en réalité augmentée, autorisez la caméra dans les réglages de votre appareil.','For the AR try-on, allow camera access in your device settings.')}</p><button class="btn gold" type="button" data-act="openSettings">${ic('gear')}${L('Ouvrir les réglages','Open settings')}</button><button class="btn line" type="button" data-act="demoAR">${L('Mode démo','Demo mode')}</button></div>`;}
 return `<div class="pc"><div class="ico">${ic('camera')}</div><h1 class="h2">${L('Essayez-la à votre poignet','Try it on your wrist')}</h1><p>${L(`La caméra affiche la ${esc(w.n)} en réalité augmentée.`,`The camera shows the ${esc(w.n)} in augmented reality.`)}</p><ul><li>${ic('lock')}${L('L’image reste sur votre appareil.','The image stays on your device.')}</li><li>${ic('ruler')}${L(`Taille calibrée sur votre poignet (${S.prefs.cm} cm).`,`Size calibrated to your wrist (${S.prefs.cm} cm).`)}</li><li>${ic('hand')}${L('Glissez, pincez, faites pivoter.','Drag, pinch, rotate.')}</li></ul><button class="btn gold ${p.state==='wait'?'loading':''}" type="button" data-act="askCam">${ic('camera')}${L('Autoriser la caméra','Allow camera')}</button><button class="btn line" type="button" data-act="demoAR">${L('Mode démo (sans caméra)','Demo mode (no camera)')}</button></div>`;}};
A.askCam=()=>{const e=top(),p=e.params;p.state='wait';rerender();getCam().then(s=>{CAM.stream=s;CAM.granted=true;if(top()!==e){stopCam();return;}replace('ar',{id:p.id,live:true,o:p.o});}).catch(err=>{if(top()!==e)return;p.state='denied';p.err=err&&err.name;rerender();});};
A.openSettings=()=>toast(L('Réglages › Yema Club › Caméra (ou le cadenas de la barre d’adresse)','Settings › Yema Club › Camera (or the address-bar padlock)'),{icon:'gear',ms:4200});
A.demoAR=()=>{const p=top().params;replace('ar',{id:p.id,live:false,o:p.o});};

const AR={id:'nme',o:null,scale:1,rot:0,x:0,y:0};
const wristMm=()=>S.prefs.cm*10/3.3;
function arGeo(el){const r=(el||top().el).getBoundingClientRect();const k=Math.max(r.width/390,r.height/700);const arm=98*k;const cx=r.width/2,cy=r.height/2+(310-350)*k;return{W:r.width,H:r.height,k,arm,cx,cy};}
SCR.ar={raw:1,modal:1,tabs:false,cls:'ar',title:()=>L('Essai en réalité augmentée','AR try-on'),
 render:p=>{const w=W(p.id);return `<div class="sc"><div class="arst"><div class="bgl">${p.live?'<video playsinline muted autoplay></video>':wristScene()}</div><div class="frame"><span class="scanl"></span><i></i><i></i><i></i><i></i></div><div class="guide" id="guide">${L('Placez votre poignet dans le cadre','Place your wrist in the frame')}</div><div class="wov" id="wov" role="img" aria-label="${esc(w.n)}"><img alt="" decoding="async" draggable="false"></div></div>
 <div class="artop"><button class="nbb glass" type="button" data-act="back" aria-label="${L('Quitter','Exit')}">${ic('close')}</button><span class="rapill glass ${p.live?'live':''}"><i></i>${p.live?L('RA active','AR live'):L('RA · mode démo','AR · demo mode')}</span><button class="nbb glass" type="button" data-act="arInfo" aria-label="${L('Aide','Help')}">${ic('info')}</button></div>
 <div class="rail"><button class="nbb glass" type="button" data-act="arZoom" data-d="1" aria-label="${L('Agrandir','Enlarge')}">${ic('zin')}</button><button class="nbb glass" type="button" data-act="arZoom" data-d="-1" aria-label="${L('Réduire','Reduce')}">${ic('zout')}</button><button class="nbb glass" type="button" data-act="arRot" aria-label="${L('Pivoter','Rotate')}">${ic('rotate')}</button><button class="nbb glass" type="button" data-act="arWrist" aria-label="${L('Mon poignet','My wrist')}">${ic('ruler')}</button><button class="nbb glass" type="button" data-act="arModels" aria-label="${L('Changer de modèle','Change model')}">${ic('layers')}</button></div>
 <button class="varbtn" type="button" data-act="arVar">${ic('sliders')}${L('Bracelet & taille','Strap & size')}</button>
 <div class="arbot"><button class="q" type="button" data-act="back">${L('Quitter','Exit')}</button><button class="shutter" type="button" data-act="snap" aria-label="${L('Prendre une photo','Take a photo')}"></button><button class="thumb" type="button" data-act="arModels" aria-label="${L('Modèle','Model')}" id="arthumb"></button></div><div class="flash" id="flash"></div></div>`;},
 mount:(el,p,e)=>{const w=W(p.id);AR.id=p.id;AR.o=Object.assign(defO(w),p.o||{});AR.scale=1;AR.rot=0;AR.x=0;AR.y=0;
  arDraw(el);
  const v=$('video',el);if(p.live&&v){const at=s=>{v.srcObject=s;const pl=v.play();if(pl&&pl.catch)pl.catch(()=>{});};if(CAM.stream)at(CAM.stream);else getCam().then(s=>{if(top()!==e){s.getTracks().forEach(t=>t.stop());return;}CAM.stream=s;at(s);}).catch(()=>{if(top()!==e)return;toast(L('Caméra indisponible : mode démo','Camera unavailable: demo mode'),{icon:'camoff'});p.live=false;rerender();});}
  const g=$('#guide',el),fr=$('.frame',el),wov=$('#wov',el);
  setTimeout(()=>{if(top()!==e)return;fr.classList.add('lock');g.classList.add('ok');g.textContent=L('Poignet détecté','Wrist detected');wov.classList.add('show');buzz([12,40,24]);setTimeout(()=>{g.style.opacity=0;},2200);if(p.id==='nme'||S.steps[1])step(2);},RM?150:1200);
  const pts=new Map();let st=null;const snap=()=>{const a=[...pts.values()];if(a.length===1)return{x:a[0].x,y:a[0].y,ax:AR.x,ay:AR.y};const [p1,p2]=a;return{d:Math.hypot(p2.x-p1.x,p2.y-p1.y),an:Math.atan2(p2.y-p1.y,p2.x-p1.x),sc:AR.scale,rot:AR.rot};};
  wov.addEventListener('pointerdown',ev=>{wov.setPointerCapture(ev.pointerId);pts.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});st=snap();});
  wov.addEventListener('pointermove',ev=>{if(!pts.has(ev.pointerId))return;pts.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});const a=[...pts.values()];if(a.length===1&&st&&st.x!=null){AR.x=st.ax+a[0].x-st.x;AR.y=st.ay+a[0].y-st.y;}else if(a.length>=2&&st&&st.d){AR.scale=Math.min(1.8,Math.max(.6,st.sc*Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y)/st.d));AR.rot=st.rot+(Math.atan2(a[1].y-a[0].y,a[1].x-a[0].x)-st.an)*180/Math.PI;}arPos(el);});
  const end=ev=>{pts.delete(ev.pointerId);st=pts.size?snap():null;};wov.addEventListener('pointerup',end);wov.addEventListener('pointercancel',end);
  wov.addEventListener('wheel',ev=>{ev.preventDefault();AR.scale=Math.min(1.8,Math.max(.6,AR.scale*(ev.deltaY<0?1.06:.94)));arPos(el);},{passive:false});
  if(p.var)setTimeout(()=>{if(top()===e)A.arVar();},RM?50:800);},
 unmount:()=>stopCam()};
function arDraw(el){el=el||top().el;const w=W(AR.id),G=arGeo(el),wov=$('#wov',el);if(!wov)return;
 const sz=parseFloat(opt(w,'size').v[AR.o.size][0]);const casePx=G.arm*sz/wristMm();const imgW=casePx/.55,imgH=imgW*4/3,f=G.arm/2/imgH,c=.54;
 wov.style.width=imgW+'px';wov.style.top=G.cy+'px';wov.dataset.c=c;
 const m=`linear-gradient(to bottom,transparent ${((c-f-.02)*100).toFixed(1)}%,#000 ${((c-f+.08)*100).toFixed(1)}%,#000 ${((c+f-.08)*100).toFixed(1)}%,transparent ${((c+f+.02)*100).toFixed(1)}%)`;
 const im=wov.querySelector('img');const s=src(w,frontI(w,AR.o),true);if(im.getAttribute('src')!==s)im.src=s;im.style.webkitMaskImage=im.style.maskImage=m;
 const fr=$('.frame',el);if(fr){const b=Math.max(170,casePx*2.1);Object.assign(fr.style,{width:b+'px',height:b+'px',margin:`${-b/2}px 0 0 ${-b/2}px`,top:G.cy+'px'});}
 const g=$('#guide',el);if(g)g.style.top=(G.cy-Math.max(170,casePx*2.1)/2-46)+'px';
 const rl=$('.rail',el);if(rl)rl.style.top=(G.cy-128)+'px';
 const th=$('#arthumb',el);if(th)th.innerHTML=pic(w,frontI(w,AR.o),{alt:false});markImgs(el);arPos(el);}
function arPos(el){const wov=$('#wov',el||top().el);if(wov)wov.style.transform=`translate(calc(-50% + ${AR.x}px),calc(-54% + ${AR.y}px)) rotate(${AR.rot}deg) scale(${AR.scale})`;}
A.arZoom=b=>{AR.scale=Math.min(1.8,Math.max(.6,AR.scale+(+b.dataset.d)*.08));arPos();buzz(4);};
A.arRot=()=>{AR.rot=Math.round(AR.rot/15)*15+15;if(AR.rot>45)AR.rot=-45;arPos();buzz(4);};
A.arInfo=()=>openSheet({label:L('Aide','Help'),html:sheetHTML(L('Conseils','Tips'),`<div class="list">${[['move',L('Glissez la montre pour l’ajuster.','Drag the watch into place.')],['zin',L('Pincez ou utilisez +/− pour la taille.','Pinch or use +/− for size.')],['rotate',L('Deux doigts pour pivoter.','Two fingers to rotate.')],['ruler',L(`Poignet calibré : ${S.prefs.cm} cm.`,`Wrist calibrated: ${S.prefs.cm} cm.`)],['camera',top().params.live?L('Caméra active, image jamais envoyée.','Camera on, image never uploaded.'):L('Mode démo : poignet illustré.','Demo mode: illustrated wrist.')]].map(([i,t])=>`<div class="li">${ic(i)}<span class="tx" style="font-weight:500">${t}</span></div>`).join('')}</div>`)});
function arSheetOpen(o){const el=top().el;el.classList.add('cust');$('.arst',el).style.transform=`translateY(-${o.shift||14}%)`;return openSheet(Object.assign({clear:true},o,{onClose:()=>{if(top().name==='ar'){el.classList.remove('cust');const s=$('.arst',el);if(s)s.style.transform='';}o.onClose&&o.onClose();}}));}
function varHTML(){const w=W(AR.id),o=AR.o;return sheetHTML(esc(w.n),`${w.opts.filter(op=>op.v.length>1).map(op=>`<div class="vopt" style="margin-top:6px"><div class="lbl">${{size:L('Taille','Size'),strap:L('Bracelet','Strap'),cond:L('État','Condition')}[op.k]}<b>${esc(LANG==='en'?op.v[o[op.k]][1]:op.v[o[op.k]][0])}</b></div><div class="chips">${op.v.map((v,i)=>`<button class="chip" type="button" aria-pressed="${o[op.k]===i}" data-act="arSet" data-k="${op.k}" data-i="${i}">${esc(LANG==='en'?v[1]:v[0])}</button>`).join('')}</div></div>`).join('')}<div class="row" style="margin-top:14px;justify-content:space-between"><span class="lbl">${L('Prix','Price')}</span><b style="font-size:18px">${eur(priceOf(w,o))}</b></div>`,`<button class="btn ghost" type="button" data-act="arWish" style="flex:0 0 auto;width:auto">${ic('heart')}</button><button class="btn gold" type="button" data-act="arCart">${ic('bagp')}${L('Ajouter au panier','Add to bag')}</button>`,L('Configurez votre style','Configure your style'));}
A.arVar=()=>arSheetOpen({label:L('Bracelet et taille','Strap and size'),max:'52%',html:varHTML()});
A.arSet=b=>{AR.o=Object.assign({},AR.o,{[b.dataset.k]:+b.dataset.i});top().params.o=AR.o;arDraw();setSheet(topSheet(),varHTML());buzz(5);if(b.dataset.k==='strap')step(3);};
A.arCart=()=>{if(addToCart(AR.id,AR.o)){closeSheet();toast(L('Ajouté au panier','Added to bag'),{icon:'bag',act:{label:L('Voir','View'),fn:openCart}});}};
A.arWish=()=>{if(!S.wish.some(x=>x.wid===AR.id))S.wish.unshift({wid:AR.id,o:Object.assign({},AR.o),at:Date.now()});save();closeSheet();toast(L('Ajouté à vos envies','Added to wishlist'),{icon:'heartf'});buzz([8,30,8]);};
const cmTxt=()=>S.prefs.cm.toFixed(1).replace('.',LANG==='fr'?',':'.');
A.arWrist=()=>{const o=arSheetOpen({label:L('Mon poignet','My wrist'),max:'46%',html:sheetHTML(L('Mon poignet','My wrist'),`<p class="p" style="margin-top:0">${L('Tour de poignet mesuré au mètre ruban : la montre est redimensionnée en direct.','Wrist circumference measured with a tape: the watch resizes live.')}</p><div class="wrv"><b id="wcm">${cmTxt()}</b> cm</div><input class="rng" id="wrr" type="range" min="14" max="21" step="0.5" value="${S.prefs.cm}" aria-label="${L('Tour de poignet','Wrist size')}"><div class="scale"><span>14 cm</span><span>21 cm</span></div>`,`<button class="btn gold" type="button" data-act="closeSheet">${L('Valider','Done')}</button>`),onClose:()=>save()});
 const r=$('#wrr',o.sh);r.addEventListener('input',()=>{S.prefs.cm=+r.value;arDraw();$('#wcm',o.sh).textContent=cmTxt();});};
A.arModels=()=>arSheetOpen({label:L('Modèles','Models'),max:'46%',shift:10,html:sheetHTML(L('Changer de modèle','Change model'),`<div class="hscroll" style="margin:0 -20px">${WATCHES.map(w=>`<button class="colc" type="button" aria-pressed="${w.id===AR.id}" data-act="arPick" data-id="${w.id}"><span class="ck">${ic('check')}</span>${pic(w,0,{alt:false})}<b style="font-size:11px;letter-spacing:0">${esc(w.n)}</b></button>`).join('')}</div>`)});
A.arPick=b=>{const w=W(b.dataset.id);AR.id=w.id;AR.o=defO(w);top().params.id=w.id;top().params.o=null;closeSheet();arDraw();toast(w.n,{icon:'watch'});};
/* snapshot: camera frame (or illustrated wrist) + masked packshot, composited on a canvas */
function loadImg(u){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=u;});}
function cover(ctx,img,iw,ih,cw,ch){const s=Math.max(cw/iw,ch/ih);ctx.drawImage(img,(cw-iw*s)/2,(ch-ih*s)/2,iw*s,ih*s);}
async function compose(el){const G=arGeo(el),dpr=Math.min(2,window.devicePixelRatio||1),cw=Math.round(G.W*dpr),ch=Math.round(G.H*dpr);const cv=document.createElement('canvas');cv.width=cw;cv.height=ch;const x=cv.getContext('2d');
 const v=$('video',el);if(v&&v.videoWidth)cover(x,v,v.videoWidth,v.videoHeight,cw,ch);else{const bg=await loadImg('data:image/svg+xml;charset=utf-8,'+encodeURIComponent(wristScene().replace('<svg ','<svg width="780" height="1400" ')));cover(x,bg,780,1400,cw,ch);}
 const wov=$('#wov',el),iw=wov.offsetWidth,ih=iw*4/3,c=+wov.dataset.c,f=G.arm/2/ih;const im=await loadImg(src(W(AR.id),frontI(W(AR.id),AR.o),true));
 const oc=document.createElement('canvas');oc.width=Math.round(iw*dpr);oc.height=Math.round(ih*dpr);const o=oc.getContext('2d');o.drawImage(im,0,0,oc.width,oc.height);o.globalCompositeOperation='destination-in';const g=o.createLinearGradient(0,0,0,oc.height);[[c-f-.02,0],[c-f+.08,1],[c+f-.08,1],[c+f+.02,0]].forEach(([s,a])=>g.addColorStop(Math.min(1,Math.max(0,s)),`rgba(0,0,0,${a})`));o.fillStyle=g;o.fillRect(0,0,oc.width,oc.height);
 x.save();x.translate((G.cx+AR.x)*dpr,(G.cy+AR.y)*dpr);x.rotate(AR.rot*Math.PI/180);x.scale(AR.scale,AR.scale);x.shadowColor='rgba(0,0,0,.5)';x.shadowBlur=22*dpr;x.shadowOffsetY=12*dpr;x.drawImage(oc,-iw/2*dpr,-ih*c*dpr,iw*dpr,ih*dpr);x.restore();
 const gr=x.createLinearGradient(0,ch*.82,0,ch);gr.addColorStop(0,'rgba(8,14,24,0)');gr.addColorStop(1,'rgba(8,14,24,.85)');x.fillStyle=gr;x.fillRect(0,ch*.82,cw,ch*.18);
 x.fillStyle='#fff';x.textAlign='center';x.font=`500 ${22*dpr}px "Playfair Display",Georgia,serif`;x.fillText('Y E M A',cw/2,ch-56*dpr);x.fillStyle='#D4B36F';x.font=`700 ${10*dpr}px Manrope,Arial,sans-serif`;x.fillText((W(AR.id).n+' · '+L('essai virtuel','virtual try-on')).toUpperCase(),cw/2,ch-34*dpr);
 return cv.toDataURL('image/jpeg',.9);}
A.snap=async()=>{const el=top().el;const f=$('#flash',el);f.classList.remove('go');void f.offsetWidth;f.classList.add('go');buzz(10);let url;try{url=await compose(el);}catch(e){toast(L('Capture impossible ici','Snapshot unavailable here'),{icon:'camoff'});return;}
 await flyShot(el,url);
 openSheet({label:L('Photo','Photo'),data:{url,id:AR.id,o:Object.assign({},AR.o)},html:sheetHTML(L('Votre essai','Your try-on'),`<img src="${url}" alt="${L('Photo de l’essai','Try-on photo')}" style="display:block;width:100%;height:50vh;max-height:440px;object-fit:contain;background:#0A1321;border-radius:14px">`,`<button class="btn ghost sm" type="button" data-act="snapShare" style="flex:1">${ic('share')}${L('Partager','Share')}</button><button class="btn ghost sm" type="button" data-act="snapSave" style="flex:1">${ic('download')}${L('Enregistrer','Save')}</button><button class="btn gold sm" type="button" data-act="snapCart" style="flex:1.3">${ic('bagp')}${L('Panier','Bag')}</button>`)});};
A.snapSave=()=>{const d=topSheet().data;const a=document.createElement('a');a.href=d.url;a.download=`yema-essai-${d.id}.jpg`;document.body.appendChild(a);a.click();a.remove();toast(L('Photo enregistrée','Photo saved'),{icon:'download'});};
A.snapShare=async()=>{const d=topSheet().data;try{const b=await (await fetch(d.url)).blob();const f=new File([b],`yema-${d.id}.jpg`,{type:'image/jpeg'});if(navigator.canShare&&navigator.canShare({files:[f]})){await navigator.share({files:[f],title:'Yema Watch Club'});return;}}catch(e){if(e&&e.name==='AbortError')return;}A.snapSave();};
A.snapCart=()=>{const d=topSheet().data;closeSheet();if(addToCart(d.id,d.o))toast(L('Ajouté au panier','Added to bag'),{icon:'bag',act:{label:L('Voir','View'),fn:openCart}});};
