"""Build Gaïndé (FSF supporters' app concept) -> fsf-demo/index.html
usage: python3 tools/fsf/build.py [--min]
"""
import subprocess, sys, os, glob, json
D = os.path.dirname(os.path.abspath(__file__)) + '/'
OUT = D + '../../fsf-demo/'
rd = lambda f: open(D + f, encoding='utf-8').read()
CSS = ['c1-base.css', 'c2-components.css', 'c3-screens.css', 'c4-live.css', 'c5-support.css']
JS = ['j0-core.js', 'j1-data.js', 'j2-nav.js', 'j3-ui.js', 'j4-home.js', 'j5-match.js', 'j6-live.js',
      'j7-coulisses.js', 'j8-games.js', 'j9-team.js', 'j10-tickets.js', 'j11-shop.js', 'j12-me.js', 'j13-init.js']
head = rd('h-head.html'); body = rd('h-body.html')
css = '\n'.join(rd(f) for f in CSS)
js = '\n'.join(rd(f) for f in JS)
js = "(function(){'use strict';\n" + js + "\n})();"
# photo credits generated by tools/fsf/photos.py
cred = D + 'credits.json'
credits = json.load(open(cred, encoding='utf-8')) if os.path.exists(cred) else {}
js = js.replace('/*CREDITS*/{}', json.dumps(credits, ensure_ascii=False, separators=(',', ':')))
ES = ['npx', '-y', 'esbuild@0.23.0']
if '--min' in sys.argv:
    css = subprocess.run(ES + ['--loader=css', '--minify'], input=css, capture_output=True, text=True, check=True).stdout
    r = subprocess.run(ES + ['--loader=js', '--minify', '--target=es2020'], input=js, capture_output=True, text=True)
    if r.returncode: print(r.stderr); sys.exit(1)
    js = r.stdout
else:
    r = subprocess.run(ES + ['--loader=js', '--target=es2020'], input=js, capture_output=True, text=True)
    if r.returncode: print(r.stderr); sys.exit(1)
out = head.replace('/*CSS*/', css) + body + \
    '<script>\n/* Gaïndé — concept d’application pour les supporters du Sénégal · El Mokhtar Berrada · non officiel, non affilié à la FSF · sources lisibles : tools/fsf (build : python3 tools/fsf/build.py --min) */\n' + \
    js + '\n</script>\n</body>\n</html>\n'
os.makedirs(OUT, exist_ok=True)
open(OUT + 'index.html', 'w', encoding='utf-8').write(out)
open('/tmp/fsf-check.js', 'w').write(js)
img = sum(os.path.getsize(p) for p in glob.glob(OUT + 'img/**/*.*', recursive=True))
print('html', len(out.encode()), 'bytes · images', img, 'bytes')
