/* ================= Soutenir: ticketing (demo) → seat map → seats → simulated payment → e-ticket ================= */
const DEMO_MATCH=FIX.find(f=>f.id==='sen-sud');
let TK=null; // pending ticket order
SCR.tickets={title:()=>L('Billetterie','Tickets'),render:()=>{const f=nextLions();return `<div class="wrap">
 <p class="p" style="margin:6px 0 16px">${L('Vos billets pour les Lions, au stade comme dans votre poche.','Your Lions tickets, in the stadium and in your pocket.')}</p>
 ${f&&f.tk?`<div class="tk-card off st"><div class="tk-top"><span class="tchip t-A">${L('Lions','Lions')}</span><span class="real">${ic('check')}${L('Match réel','Real match')}</span></div><div class="tk-teams">${flag(f.h,40)}<b class="disp">${esc(nat(f.h))} – ${esc(nat(f.a))}</b>${flag(f.a,40)}</div><div class="tk-meta"><span>${ic('cal')}${esc(whenTxt(f))}</span><span>${ic('stadium')}${esc(vTxt(f))}</span></div><p class="small" style="margin:8px 0 12px">${esc(tx(f.info))}</p>${ext(f.tk,`${ic('ticket')}${L('Billetterie officielle du stade','Official stadium ticketing')}${ic('ext')}`,'btn y block')}</div>`:''}
 <div class="tk-card st" style="margin-top:12px"><div class="tk-top"><span class="tchip t-A">${L('Lions','Lions')}</span>${demoTag(L('Parcours démo','Demo flow'))}</div><div class="tk-teams">${flag('SEN',40)}<b class="disp">${nat('SEN')} – ${nat('SUD')}</b>${flag('SUD',40)}</div><div class="tk-meta"><span>${ic('trophy')}${esc(tx(DEMO_MATCH.comp))}</span><span>${ic('stadium')}Stade Abdoulaye Wade · Diamniadio</span></div>
  <div class="note" style="margin:10px 0 12px">${ic('info')}<span>${L('Date et stade pas encore annoncés par la FSF : ce parcours illustre une billetterie au stade Abdoulaye-Wade (50 000 places). Tarifs indicatifs, paiement simulé.','Date and venue not yet announced by the FSF: this flow illustrates ticketing at the Abdoulaye Wade Stadium (50,000 seats). Indicative prices, simulated payment.')}</span></div>
  <button class="btn y block" type="button" data-act="seatmap">${ic('ticket')}${L('Choisir mes places','Choose my seats')}</button></div>
 ${S.tickets.length?`<div class="sec-h" style="padding:0;margin:24px 0 10px"><h2 class="h3">${L('Mes billets','My tickets')}</h2></div><div class="col8">${S.tickets.map(t=>`<button class="row" type="button" data-act="eticket" data-no="${t.no}" style="border-radius:16px;background:var(--card);border:1px solid var(--line)"><span class="ri">${ic('ticket')}</span><span class="t"><b>${nat('SEN')} – ${nat('SUD')} · ${t.seats.length} ${L('place(s)','seat(s)')}</b><small>${esc(tx(ZONES.find(z=>z.id===t.zone).n))} · ${t.seats.join(', ')}</small></span>${ic('chev')}</button>`).join('')}</div>`:''}</div>`;}};
A.tickets=()=>go('tickets');
/* stadium seat map (top-down, own illustration) */
function stadiumSVG(sel){const ring='M150 18c74 0 128 30 128 92v200c0 62-54 92-128 92S22 372 22 310V110c0-62 54-92 128-92zM96 104c-10 0-18 8-18 18v176c0 10 8 18 18 18h108c10 0 18-8 18-18V122c0-10-8-18-18-18z';
 const clip={nord:'0,0 300,0 300,104 0,104',sud:'0,316 300,316 300,420 0,420',ouest:'0,104 150,104 150,316 0,316',est:'150,104 300,104 300,316 150,316',vip:'0,172 150,172 150,248 0,248'};
 const lab={nord:[150,62],sud:[150,370],ouest:[50,138],est:[250,210],vip:[50,210]};
 return `<svg class="stad" viewBox="0 0 300 420" role="img" aria-label="${L('Plan du stade Abdoulaye-Wade','Abdoulaye Wade Stadium map')}"><defs>${Object.entries(clip).map(([k,p])=>`<clipPath id="cz-${k}"><polygon points="${p}"/></clipPath>`).join('')}<pattern id="grass" width="20" height="20" patternUnits="userSpaceOnUse"><rect width="20" height="10" fill="#176037"/><rect y="10" width="20" height="10" fill="#14532F"/></pattern></defs>
 <path d="M150 8c80 0 138 33 138 100v204c0 67-58 100-138 100S12 379 12 312V108C12 41 70 8 150 8z" fill="#0B2416" stroke="rgba(255,255,255,.1)"/>
 ${['nord','sud','ouest','est','vip'].map(k=>{const z=ZONES.find(x=>x.id===k);return `<g class="zn ${sel===k?'sel':''}" data-act="zone" data-id="${k}" tabindex="0" role="button" aria-label="${esc(tx(z.n))} · ${fcfa(z.p)}"><g clip-path="url(#cz-${k})"><path d="${ring}" fill-rule="evenodd" fill="${z.c}"/></g></g>`;}).join('')}
 <path d="M0 104h300M0 316h300M150 104v212M0 172h150M0 248h150" stroke="#0B2416" stroke-width="5"/>
 <g pointer-events="none"><rect x="96" y="122" width="108" height="176" rx="4" fill="url(#grass)"/><g fill="none" stroke="rgba(255,255,255,.55)" stroke-width="1.2"><rect x="102" y="128" width="96" height="164"/><path d="M102 210h96"/><circle cx="150" cy="210" r="15"/><rect x="128" y="128" width="44" height="20"/><rect x="128" y="272" width="44" height="20"/></g></g>
 ${Object.entries(lab).map(([k,[x,y]])=>`<text x="${x}" y="${y}" class="zl">${esc(tx(ZONES.find(z=>z.id===k).n).replace('Tribune ','').replace(' stand','').toUpperCase())}</text>`).join('')}
 <text x="150" y="214" class="zl pitch-l">${L('TERRAIN','PITCH')}</text></svg>`;}
SCR.seatmap={title:()=>L('Choisir une tribune','Choose a stand'),short:()=>L('Tribunes','Stands'),bar:1,render:(p)=>{const z=ZONES.find(x=>x.id===p.z);return `<div class="wrap"><div class="sm-h"><b class="disp">${nat('SEN')} – ${nat('SUD')}</b>${demoTag()}</div><p class="small">Stade Abdoulaye Wade · Diamniadio · 50 000 ${L('places','seats')}</p>
 <div class="sm-map">${stadiumSVG(p.z)}</div>
 <div class="zlist">${ZONES.map(x=>`<button class="zr ${p.z===x.id?'sel':''}" type="button" data-act="zone" data-id="${x.id}"><i style="background:${x.c}"></i><span><b>${esc(tx(x.n))}</b><small>${x.id==='vip'?L('Places numérotées · accès salon','Numbered seats · lounge access'):x.id==='nord'||x.id==='sud'?L('Ambiance tambours · debout','Drums & standing'):L('Places numérotées','Numbered seats')}</small></span><b class="disp tn">${fcfa(x.p)}</b></button>`).join('')}</div>
 <p class="small" style="margin-top:10px">${L('Tarifs indicatifs pour la démonstration (≈','Indicative demo prices (≈')} ${eurOf(2000)}–${eurOf(30000)}).</p></div>`;},
 after:(p)=>`<div class="cta-bar"><button class="btn y block" type="button" data-act="toSeats" ${p.z?'':'disabled'}>${p.z?`${L('Places','Seats')} · ${esc(tx(ZONES.find(x=>x.id===p.z).n))}`:L('Touchez une tribune','Tap a stand')}${ic('arrow')}</button></div>`};
A.seatmap=()=>go('seatmap',{});
A.zone=t=>{const e=top();if(e.name!=='seatmap')return;e.params.z=t.dataset.id;const sc=$('.sc',e.el).scrollTop;build(e);$('.sc',e.el).scrollTop=sc;buzz(5);const g=$(`.zn[data-id="${t.dataset.id}"]`,e.el);if(g&&!RM)g.animate([{opacity:.5},{opacity:1}],{duration:300});};
A.toSeats=()=>{const e=top();if(!e.params.z)return;go('seats',{z:e.params.z,sel:[]});};
const ROWS='ABCDEFGH';
const taken=(z,r,n)=>{let h=0;const s=z+r+n;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h%100<(z==='vip'?30:z==='nord'||z==='sud'?62:45);};
SCR.seats={title:p=>tx(ZONES.find(x=>x.id===p.z).n),short:()=>L('Places','Seats'),bar:1,render:(p)=>{const z=ZONES.find(x=>x.id===p.z);const sel=p.sel||[];return `<div class="wrap"><div class="seat-h"><span class="lbl">${L('Sélectionnez jusqu’à 4 places','Select up to 4 seats')}</span><span class="legend"><i class="f"></i>${L('Libre','Free')}<i class="t"></i>${L('Pris','Taken')}<i class="s"></i>${L('Vous','You')}</span></div>
 <div class="seat-stage">${L('TERRAIN','PITCH')}</div>
 <div class="seat-grid" style="--zc:${z.c}">${[...ROWS].map(r=>`<div class="srow"><span class="rl">${r}</span>${Array.from({length:12},(_,i)=>{const n=i+1,id=r+n,tk=taken(z.id,r,n);return `<button type="button" class="seat ${tk?'tk':''} ${sel.includes(id)?'on':''}" data-act="seat" data-s="${id}" ${tk?'disabled aria-label="'+id+' '+L('pris','taken')+'"':`aria-label="${id}" aria-pressed="${sel.includes(id)}"`}></button>`;}).join('')}<span class="rl">${r}</span></div>`).join('')}</div>
 <div class="seat-sum"><div><span class="lbl">${L('Vos places','Your seats')}</span><b class="disp">${sel.length?sel.join(' · '):'—'}</b></div><div style="text-align:right"><span class="lbl">Total</span><b class="disp tn">${fcfa(sel.length*z.p)}</b><small class="mut">≈ ${eurOf(sel.length*z.p)}</small></div></div></div>`;},
 after:(p)=>`<div class="cta-bar"><button class="btn y block" type="button" data-act="seatsGo" ${(p.sel||[]).length?'':'disabled'}>${L('Continuer vers le paiement','Continue to payment')}${ic('arrow')}</button></div>`};
A.seat=t=>{const e=top();const s=t.dataset.s;const sel=e.params.sel||[];const i=sel.indexOf(s);if(i>=0)sel.splice(i,1);else{if(sel.length>=4){toast(L('4 places maximum par commande','4 seats max per order'),{icon:'info'});buzz([30]);return;}sel.push(s);}e.params.sel=sel;const sc=$('.sc',e.el).scrollTop;build(e);$('.sc',e.el).scrollTop=sc;buzz(4);const b=$(`[data-s="${s}"]`,e.el);if(b&&!RM)b.animate([{transform:'scale(.6)'},{transform:'scale(1.25)'},{transform:'none'}],{duration:340,easing:'ease-out'});};
A.seatsGo=()=>{const e=top();const z=ZONES.find(x=>x.id===e.params.z);TK={zone:z.id,seats:(e.params.sel||[]).slice().sort(),price:z.p};go('checkout',{kind:'ticket'});};

/* ---------- checkout (tickets & shop): simulated payment, no card or phone fields ---------- */
const PAY=[['wave','wave',{fr:'Wave',en:'Wave'},{fr:'Mobile money · démo',en:'Mobile money · demo'}],['om','mobile',{fr:'Orange Money',en:'Orange Money'},{fr:'Mobile money · démo',en:'Mobile money · demo'}],['card','cardpay',{fr:'Carte bancaire',en:'Bank card'},{fr:'Démo · aucune saisie',en:'Demo · nothing to enter'}]];
function checkoutItems(kind){if(kind==='ticket'&&TK){const z=ZONES.find(x=>x.id===TK.zone);return [{n:`${nat('SEN')} – ${nat('SUD')} · ${tx(z.n)}`,d:TK.seats.join(', '),q:TK.seats.length,p:TK.price}];}
 return S.cart.map(c=>{const it=SHOP.find(x=>x.id===c.id);return {n:tx(it.n),d:[c.size,c.name?`${c.name} ${c.no}`:''].filter(Boolean).join(' · '),q:c.qty,p:it.p+(c.name?3000:0)};});}
SCR.checkout={title:()=>L('Paiement','Payment'),bar:1,render:(p)=>{const items=checkoutItems(p.kind);const tot=items.reduce((a,i)=>a+i.q*i.p,0);const fee=p.kind==='ticket'?0:(tot>=50000?0:2500);
 return `<div class="wrap"><div class="ck-sum card pad">${items.map(i=>`<div class="ck-i"><span><b>${esc(i.n)}</b><small>${esc(i.d)}</small></span><span class="tn">${i.q} × ${fcfa(i.p)}</span></div>`).join('')}
 ${p.kind!=='ticket'?`<div class="kv"><span>${L('Livraison','Delivery')}</span><b>${fee?fcfa(fee):L('Offerte','Free')}</b></div>`:''}<div class="kv tot"><span>Total</span><b class="disp tn">${fcfa(tot+fee)}</b></div><small class="mut">≈ ${eurOf(tot+fee)}</small></div>
 <div class="lbl" style="margin:18px 0 8px">${L('Moyen de paiement','Payment method')}</div>
 <div class="opts">${PAY.map(([k,i,n,d])=>`<button class="opt pay-${k}" type="button" data-act="payPick" data-v="${k}" aria-pressed="${p.pay===k}"><span class="pay-i">${ic(i)}</span><span style="flex:1"><b>${tx(n)}</b><small>${tx(d)}</small></span><span class="rad"></span></button>`).join('')}</div>
 <div class="ck-safe">${ic('lock')}<span><b>${L('Paiement simulé — aucun débit','Simulated payment — no charge')}</b><small>${L('Prototype : aucun numéro de carte ni de téléphone n’est demandé ni collecté.','Prototype: no card or phone number is requested or collected.')}</small></span></div></div>`;},
 after:(p)=>{const items=checkoutItems(p.kind);const tot=items.reduce((a,i)=>a+i.q*i.p,0)+(p.kind==='ticket'?0:(items.reduce((a,i)=>a+i.q*i.p,0)>=50000?0:2500));return `<div class="cta-bar"><button class="btn y block" type="button" data-act="payGo" ${p.pay?'':'disabled'}>${ic('lock')}${L('Payer','Pay')} ${fcfa(tot)} · ${L('démo','demo')}</button></div>`;}};
A.payPick=t=>{const e=top();e.params.pay=t.dataset.v;const sc=$('.sc',e.el).scrollTop;build(e);$('.sc',e.el).scrollTop=sc;buzz(4);};
A.payGo=async t=>{const e=top();if(!e.params.pay)return;t.classList.add('busy');const kind=e.params.kind,pay=e.params.pay;
 const ov=document.createElement('div');ov.className='payov';ov.innerHTML=`<div class="po-in"><div class="po-ph">${ic(pay==='card'?'cardpay':'mobile')}<span class="po-ring"></span><span class="po-ok">${ic('check')}</span></div><b class="h3">${L('Paiement simulé…','Simulated payment…')}</b><small>${pay==='wave'?L('Confirmation dans l’app Wave (démo)','Confirming in the Wave app (demo)'):pay==='om'?L('Confirmation Orange Money (démo)','Orange Money confirmation (demo)'):L('Autorisation carte (démo)','Card authorisation (demo)')}</small></div>`;layer.appendChild(ov);
 await wait(RM?200:1500);ov.classList.add('ok');$('b',ov).textContent=L('Paiement validé · Jërëjëf !','Payment confirmed · Jërëjëf!');$('small',ov).textContent=L('Aucun débit réel','No real charge');buzz([10,40,20]);await wait(RM?200:900);ov.classList.add('out');setTimeout(()=>ov.remove(),400);
 if(kind==='ticket'){const no='TK-'+Math.random().toString(36).slice(2,8).toUpperCase();S.tickets.unshift({no,zone:TK.zone,seats:TK.seats,ts:Date.now(),pay});save();TK=null;
  const tkS=stk().find(x=>x.name==='tickets');if(tkS)tkS.ver=0;collapseTo(['seatmap','seats','checkout'],'eticket',{no,fresh:1});earn('ticket-'+no,150,{fr:'Billet Sénégal – Soudan',en:'Senegal – Sudan ticket'});step(2);}
 else{const no='GD-'+Math.random().toString(36).slice(2,7).toUpperCase();const items=checkoutItems('shop');S.orders.unshift({no,items,ts:Date.now(),pay});S.cart=[];save();
  collapseTo(['cart','checkout','product'],'order',{no});earn('order-'+no,80,{fr:'Commande boutique',en:'Shop order'});}};
/* e-ticket */
SCR.eticket={title:()=>L('Mon billet','My ticket'),render:(p)=>{const t=S.tickets.find(x=>x.no===p.no)||S.tickets[0];if(!t)return '';const z=ZONES.find(x=>x.id===t.zone);
 return `<div class="et-wrap"><div class="et ${p.fresh?'fresh':''}" id="etk"><div class="et-f">
  <div class="et-top"><span class="et-brand">${lionSVG()}${wordmark()}</span>${demoTag(L('Billet démo','Demo ticket'))}</div>
  <div class="et-teams">${flag('SEN',44)}<b class="disp">${nat('SEN')}<i>–</i>${nat('SUD')}</b>${flag('SUD',44)}</div>
  <div class="et-comp">${esc(tx(DEMO_MATCH.comp))}</div>
  <div class="et-grid"><div><small>${L('Tribune','Stand')}</small><b>${esc(tx(z.n))}</b></div><div><small>${L('Places','Seats')}</small><b class="tn">${t.seats.join(' · ')}</b></div><div><small>${L('Stade','Stadium')}</small><b>Abdoulaye Wade</b></div><div><small>${L('Date','Date')}</small><b>${L('À confirmer','TBC')}</b></div></div>
  <div class="et-cut"><i></i><i></i></div>
  <div class="et-qr">${qrSvg(DEMO_URL(t.no),168)}<div><small>${L('N° de billet','Ticket no.')}</small><b class="tn">${t.no}</b><small>${esc(S.user.first)} ${esc(S.user.last)}</small></div></div>
  <span class="et-holo"></span></div>
  <div class="et-b"><b class="h3">${L('Conditions (démo)','Terms (demo)')}</b><p class="small">${L('Billet nominatif de démonstration, sans valeur. Le QR code renvoie vers ce prototype. Une vraie billetterie FSF afficherait ici les conditions d’accès, l’ouverture des portes et le plan d’accès au stade de Diamniadio (TER, BRT, parkings).','Demo personal ticket with no value. The QR code links to this prototype. A real FSF ticketing would show access conditions, gate opening times and directions to Diamniadio (TER, BRT, parking).')}</p><p class="small">${L('Paiement simulé · aucun débit.','Simulated payment · no charge.')}</p></div></div>
 <div style="display:flex;gap:8px;margin-top:18px"><button class="ib" type="button" data-act="etFlip" style="width:50px;height:50px;border-radius:14px" aria-label="${L('Retourner le billet','Flip the ticket')}">${ic('rotate')}</button><button class="btn ghost" type="button" data-act="wallet" style="flex:1">${ic('wallet')}${L('Portefeuille','Wallet')}</button><button class="btn y" type="button" data-act="openCard" style="flex:1">${ic('card')}${L('Ma carte','My card')}</button></div>
 <p class="small" style="text-align:center;margin-top:12px">${L('Retrouvez vos billets dans Moi › Mes billets.','Find your tickets in Me › My tickets.')}</p></div>`;},
 mount:(el,p)=>{if(p.fresh){p.fresh=0;confetti(.5,.25,100);}}};
A.eticket=t=>go('eticket',{no:t.dataset.no});
A.etFlip=()=>{const t=$('#etk',top().el);if(!t)return;t.classList.toggle('flip');t.classList.remove('fresh');buzz(5);};
A.wallet=()=>toast(L('Ajouté au portefeuille (démo)','Added to wallet (demo)'),{icon:'wallet'});
