/* ================= Boutique: own concept designs (no kit-maker / sponsor marks), personalisation, cart ================= */
const SHIRT='M96 22 58 34 16 74l24 58 30-14v202q80 12 160 0V118l30 14 24-58-42-40-38-12q-54 30-108 0z';
function jerseySVG(id,o){o=o||{};const it=SHOP.find(x=>x.id===id);const [b,c1,c2,c3]=it.c;const home=id==='home';const back=o.back;const uid=id+(back?'b':'f')+(o.k||'');
 const nm=(o.name||'').toUpperCase().slice(0,12),no=o.no!=null&&o.no!==''?String(o.no):'';
 const ink=home?'#0B5E30':'#FDEF42',edge=home?'#FDEF42':'#06140C';
 return `<svg viewBox="0 0 300 340" class="jsy" role="img" aria-label="${esc(tx(it.n))}${back&&(nm||no)?' · '+esc(nm)+' '+esc(no):''}"><defs><clipPath id="cl-${uid}"><path d="${SHIRT}"/></clipPath>
 <pattern id="pt-${uid}" width="28" height="14" patternUnits="userSpaceOnUse"><path d="M0 7 7 0l7 7-7 7zM14 7l7-7 7 7-7 7z" fill="none" stroke="${home?'#0B5E30':'#FDEF42'}" stroke-width="1.2"/></pattern>
 <linearGradient id="sh-${uid}" x1="0" x2="1"><stop offset="0" stop-color="#000" stop-opacity=".22"/><stop offset=".3" stop-color="#000" stop-opacity="0"/><stop offset=".7" stop-color="#fff" stop-opacity=".06"/><stop offset="1" stop-color="#000" stop-opacity=".25"/></linearGradient></defs>
 <g clip-path="url(#cl-${uid})"><rect width="300" height="340" fill="${b}"/>
 <rect width="300" height="340" fill="url(#pt-${uid})" opacity="${home?.07:.16}"/>
 ${!back&&home?`<path d="M70 92 150 168 230 92v22l-80 76-80-76z" fill="${c1}"/><path d="M70 116l80 76 80-76v14l-80 76-80-76z" fill="${c2}"/><path d="M70 132l80 76 80-76v10l-80 76-80-76z" fill="${c3}"/>`:''}
 ${!back&&!home?`<rect y="236" width="300" height="44" fill="${c1}" opacity=".9"/><rect y="236" width="300" height="44" fill="url(#pt-${uid})" opacity=".6"/><rect y="230" width="300" height="5" fill="${c3}"/><rect y="281" width="300" height="5" fill="${c3}"/>`:''}
 ${back&&home?`<rect y="300" width="300" height="40" fill="${c1}"/><rect y="296" width="300" height="4" fill="${c2}"/>`:''}
 ${back&&!home?`<rect y="300" width="300" height="40" fill="${c3}" opacity=".9"/>`:''}
 <path d="M16 74 40 132l30-14-16-50z" fill="${home?c1:c3}" opacity=".95"/><path d="M284 74l-24 58-30-14 16-50z" fill="${home?c1:c3}" opacity=".95"/>
 <path d="M28 104l24 12M272 104l-24 12" stroke="${c2}" stroke-width="5"/>
 <rect width="300" height="340" fill="url(#sh-${uid})"/></g>
 <path d="M96 22q54 30 108 0" fill="none" stroke="${home?c1:c2}" stroke-width="9" stroke-linecap="round"/><path d="M110 29q40 18 80 0" fill="none" stroke="${home?c3:c3}" stroke-width="2.5" opacity=".9"/>
 ${!back?`<g transform="translate(184 66) scale(.34)">${lionSVG().replace(/<\/?svg[^>]*>/g,'')}</g><g transform="translate(86 76)"><rect width="34" height="22" rx="3" fill="${home?'#06140C':'#FDEF42'}" opacity=".9"/><text x="17" y="15.5" text-anchor="middle" font-family="Big Shoulders Display,Impact" font-weight="900" font-size="12" fill="${home?'#FDEF42':'#06140C'}">SEN</text></g>`:
 `<text x="150" y="104" text-anchor="middle" class="jn" font-family="Big Shoulders Display,Impact,sans-serif" font-weight="900" font-size="${nm.length>9?26:32}" letter-spacing="2" fill="${ink}" stroke="${edge}" stroke-width="1.2" paint-order="stroke">${esc(nm)}</text>
  <text x="150" y="232" text-anchor="middle" class="jno" font-family="Big Shoulders Display,Impact,sans-serif" font-weight="900" font-size="132" fill="${ink}" stroke="${edge}" stroke-width="3" paint-order="stroke">${esc(no)}</text>`}
 <path d="${SHIRT}" fill="none" stroke="rgba(0,0,0,.35)" stroke-width="2"/></svg>`;}
function scarfSVG(){return `<svg viewBox="0 0 300 340" class="jsy" role="img" aria-label="${L('Écharpe','Scarf')}"><defs><pattern id="scp" width="24" height="12" patternUnits="userSpaceOnUse"><path d="M0 6 6 0l6 6-6 6zM12 6l6-6 6 6-6 6z" fill="none" stroke="#FDEF42" stroke-width="1.4"/></pattern></defs>
 <g transform="rotate(-24 150 170)"><rect x="40" y="130" width="240" height="70" rx="6" fill="#00853F"/><rect x="40" y="130" width="240" height="70" fill="url(#scp)" opacity=".5"/><rect x="40" y="148" width="240" height="8" fill="#FDEF42"/><rect x="40" y="174" width="240" height="8" fill="#E31B23"/><text x="160" y="171" text-anchor="middle" font-family="Big Shoulders Display,Impact" font-weight="900" font-size="22" fill="#F3F1E4" letter-spacing="4">GAÏNDÉ</text>${Array.from({length:9},(_,i)=>`<path d="M${44+i*4} 200v26M${276-i*4} 130v-26" stroke="${['#00853F','#FDEF42','#E31B23'][i%3]}" stroke-width="3"/>`).join('')}</g></svg>`;}
function bobSVG(){return `<svg viewBox="0 0 300 340" class="jsy" role="img" aria-label="${L('Bob','Bucket hat')}"><defs><pattern id="bbp" width="24" height="12" patternUnits="userSpaceOnUse"><path d="M0 6 6 0l6 6-6 6zM12 6l6-6 6 6-6 6z" fill="none" stroke="#06140C" stroke-width="1.3"/></pattern></defs>
 <path d="M30 230q120-40 240 0l-14 22q-106-30-212 0z" fill="#0B5E30"/><path d="M78 226q4-96 72-100 68 4 72 100-72-22-144 0z" fill="#FDEF42"/><path d="M78 226q4-96 72-100 68 4 72 100-72-22-144 0z" fill="url(#bbp)" opacity=".25"/><path d="M80 210q70-20 140 0v14q-70-20-140 0z" fill="#E31B23"/><path d="M80 196q70-20 140 0v12q-70-20-140 0z" fill="#00853F"/>
 <g transform="translate(128 140) scale(.44)">${lionSVG().replace(/<\/?svg[^>]*>/g,'')}</g></svg>`;}
function productArt(id,o){const it=SHOP.find(x=>x.id===id);return it.k==='jersey'?jerseySVG(id,o):it.k==='scarf'?scarfSVG():bobSVG();}

SCR.shop={title:()=>L('Boutique','Shop'),right:()=>bagBtn(),render:()=>`<div class="shop-hero"><span class="kick">${L('Collection concept · 2026','Concept collection · 2026')}</span><b class="h1">${L('Portez la Teranga','Wear the Teranga')}</b><p class="p">${L('Maillots et accessoires dessinés pour Gaïndé, aux couleurs du drapeau. Créations originales non officielles : aucun logo d’équipementier ni de sponsor.','Jerseys and accessories designed for Gaïndé in the flag’s colours. Original unofficial designs: no kit-maker or sponsor logos.')}</p></div>
 <div class="shop-g wrap stg">${SHOP.map(it=>`<button class="pc" type="button" data-act="product" data-id="${it.id}"><span class="pc-art">${productArt(it.id,{k:'l'})}</span>${it.perso?`<span class="pc-tag">${L('Floquable','Personalise')}</span>`:''}<span class="pc-t"><b>${esc(tx(it.n))}</b><span class="disp tn">${fcfa(it.p)}</span></span></button>`).join('')}</div>
 <div class="note">${ic('info')}<span>${L('Boutique de démonstration : commande et paiement simulés, rien n’est expédié.','Demo shop: order and payment are simulated, nothing ships.')}</span></div>`};
A.shop=()=>go('shop');
A.shopFor=t=>{const p=P(t.dataset.id);go('product',{id:'home',name:shortN(p.n).split(' ').pop().toUpperCase().slice(0,12),no:p.no||'',back:1});};
SCR.product={title:p=>tx(SHOP.find(x=>x.id===p.id).n),short:()=>L('Article','Item'),right:()=>bagBtn(),bar:1,render:(p)=>{const it=SHOP.find(x=>x.id===p.id);p.size=p.size||'M';p.qty=p.qty||1;if(p.name==null)p.name='';if(p.no==null)p.no='';
 return `<div class="pd-art ${it.perso?'flippable':''}"><div class="pd-flip ${p.back?'back':''}" id="pdFlip"><div class="pd-f">${productArt(it.id,{k:'pf'})}</div>${it.perso?`<div class="pd-b">${jerseySVG(it.id,{back:1,name:p.name||'',no:p.no,k:'pb'})}</div>`:''}</div>${it.perso?`<button class="pd-rot btn dark sm" type="button" data-act="pdRot">${ic('rotate')}${p.back?L('Face','Front'):L('Dos','Back')}</button>`:''}</div>
 <div class="wrap"><div class="pd-h"><div><span class="kick">${L('Création concept','Concept design')}</span><h1 class="h2" style="margin-top:4px">${esc(tx(it.n))}</h1></div><div style="text-align:right"><b class="disp tn pd-p">${fcfa(it.p+(it.perso&&(p.name||p.no)?3000:0))}</b><small class="mut">≈ ${eurOf(it.p+(it.perso&&(p.name||p.no)?3000:0))}</small></div></div>
 <p class="p">${esc(tx(it.d))}</p>
 ${it.k!=='cap'&&it.k!=='scarf'?`<div class="lbl" style="margin:16px 0 8px">${L('Taille','Size')}</div><div class="chips" style="padding:0">${['S','M','L','XL','XXL'].map(s=>`<button class="chip" type="button" data-act="pdSize" data-v="${s}" aria-pressed="${p.size===s}">${s}</button>`).join('')}</div>`:''}
 ${it.perso?`<div class="lbl" style="margin:18px 0 8px">${L('Flocage','Personalisation')} <span class="mut">(+${fcfa(3000)})</span></div><div class="perso"><label class="fld"><span>${L('Nom','Name')}</span><input id="pdName" type="text" inputmode="text" autocomplete="off" autocapitalize="characters" maxlength="12" value="${esc(p.name)}" placeholder="${L('VOTRE NOM','YOUR NAME')}"></label><label class="fld no"><span>N°</span><input id="pdNo" type="text" inputmode="numeric" autocomplete="off" maxlength="2" value="${esc(p.no)}" placeholder="12"></label></div>
 <div class="pd-q">${['koulibaly','isarr','jackson','pgueye'].map(id=>{const pl=P(id);const nm=shortN(pl.n).split(' ').pop().toUpperCase();return `<button class="chip" type="button" data-act="pdQuick" data-n="${esc(nm)}" data-no="${pl.no}">${esc(nm)} ${pl.no}</button>`;}).join('')}<button class="chip" type="button" data-act="pdQuick" data-n="${esc(S.user.first.toUpperCase())}" data-no="12">${esc(S.user.first.toUpperCase())} 12</button></div>`:''}
 <div class="lbl" style="margin:18px 0 8px">${L('Quantité','Quantity')}</div><div class="qty"><button class="ib" type="button" data-act="pdQty" data-d="-1" aria-label="-">${ic('minus')}</button><b class="disp tn">${p.qty}</b><button class="ib" type="button" data-act="pdQty" data-d="1" aria-label="+">${ic('plus')}</button></div></div>`;},
 after:()=>`<div class="cta-bar"><button class="btn y block" type="button" data-act="addCart">${ic('bag')}${L('Ajouter au panier','Add to bag')}</button></div>`,
 mount:(el,p)=>{const n=$('#pdName',el),no=$('#pdNo',el);if(!n)return;const upd=()=>{p.name=n.value.toUpperCase().replace(/[^A-ZÀ-ÖØ-Ý' -]/g,'').slice(0,12);if(n.value!==p.name)n.value=p.name;p.no=no.value.replace(/\D/g,'').slice(0,2);if(no.value!==p.no)no.value=p.no;
  const b=$('.pd-b',el);if(b)b.innerHTML=jerseySVG(p.id,{back:1,name:p.name,no:p.no,k:'pb'});const f=$('#pdFlip',el);if(f&&!f.classList.contains('back')){f.classList.add('back');p.back=1;const r=$('.pd-rot',el);if(r)r.innerHTML=ic('rotate')+L('Face','Front');}
  const pr=$('.pd-p',el);if(pr)pr.textContent=fcfa(SHOP.find(x=>x.id===p.id).p+((p.name||p.no)?3000:0));};
  n.addEventListener('input',upd);no.addEventListener('input',upd);}};
A.product=t=>go('product',{id:t.dataset.id});
A.pdRot=t=>{const e=top();e.params.back=!e.params.back;$('#pdFlip',e.el).classList.toggle('back',!!e.params.back);t.innerHTML=ic('rotate')+(e.params.back?L('Face','Front'):L('Dos','Back'));buzz(5);};
A.pdSize=t=>{const e=top();e.params.size=t.dataset.v;$$('[data-act="pdSize"]',e.el).forEach(b=>b.setAttribute('aria-pressed',b===t));buzz(4);};
A.pdQty=t=>{const e=top();e.params.qty=clamp((e.params.qty||1)+ +t.dataset.d,1,5);$('.qty b',e.el).textContent=e.params.qty;buzz(4);};
A.pdQuick=t=>{const e=top();const n=$('#pdName',e.el),no=$('#pdNo',e.el);n.value=t.dataset.n;no.value=t.dataset.no;n.dispatchEvent(new Event('input'));buzz(5);};
A.addCart=t=>{const e=top();const p=e.params;const it=SHOP.find(x=>x.id===p.id);const item={id:it.id,size:it.k==='jersey'?p.size:'',name:it.perso?(p.name||''):'',no:it.perso?(p.no||''):'',qty:p.qty||1};
 const same=S.cart.find(c=>c.id===item.id&&c.size===item.size&&c.name===item.name&&c.no===item.no);if(same)same.qty+=item.qty;else S.cart.push(item);save();
 const art=$('.pd-art svg',e.el),bag=$('.nb [data-act="cart"]',e.el);if(art&&bag&&!RM){const a=app.getBoundingClientRect(),r0=art.getBoundingClientRect(),r1=bag.getBoundingClientRect();const c=art.cloneNode(true);c.classList.add('fly');c.style.cssText=`position:absolute;z-index:120;left:${r0.left-a.left}px;top:${r0.top-a.top}px;width:${r0.width}px;height:${r0.height}px;pointer-events:none`;layer.appendChild(c);
  c.animate([{transform:'none',opacity:1},{transform:`translate(${r1.left-r0.left+r1.width/2-r0.width/2}px,${r1.top-r0.top+r1.height/2-r0.height/2}px) scale(.08)`,opacity:.6}],{duration:620,easing:'cubic-bezier(.5,-.2,.7,1)'}).finished.then(()=>{c.remove();badges();});}else badges();
 buzz([6,30,6]);toast(L('Ajouté au panier','Added to bag'),{icon:'bag',act:{label:L('Voir','View'),fn:()=>A.cart()}});};
A.cart=()=>{if(top()&&top().name==='cart')return;go('cart');};
SCR.cart={title:()=>L('Panier','Bag'),bar:1,render:()=>{if(!S.cart.length)return `<div class="empty">${ic('bag')}<b class="h3">${L('Panier vide','Your bag is empty')}</b><p>${L('Maillots floqués, écharpes, bobs : préparez-vous pour le prochain match.','Personalised jerseys, scarves, bucket hats: get ready for the next match.')}</p><button class="btn y" type="button" data-act="shop">${L('Voir la boutique','Go to the shop')}</button></div>`;
 const tot=S.cart.reduce((a,c)=>a+c.qty*(SHOP.find(x=>x.id===c.id).p+(c.name||c.no?3000:0)),0);
 return `<div class="wrap col8">${S.cart.map((c,i)=>{const it=SHOP.find(x=>x.id===c.id);return `<div class="ci"><span class="ci-art">${it.perso&&(c.name||c.no)?jerseySVG(it.id,{back:1,name:c.name,no:c.no,k:'c'+i}):productArt(it.id,{k:'c'+i})}</span><span class="ci-t"><b>${esc(tx(it.n))}</b><small>${[c.size,c.name||c.no?`${L('Flocage','Name')} ${esc(c.name)} ${esc(c.no)}`:''].filter(Boolean).join(' · ')}</small><span class="disp tn">${fcfa(it.p+(c.name||c.no?3000:0))}</span></span><span class="ci-q"><button class="ib" type="button" data-act="ciQty" data-i="${i}" data-d="1" aria-label="+">${ic('plus')}</button><b class="tn">${c.qty}</b><button class="ib" type="button" data-act="ciQty" data-i="${i}" data-d="-1" aria-label="-">${ic(c.qty>1?'minus':'close')}</button></span></div>`;}).join('')}
 <div class="card pad" style="margin-top:6px"><div class="kv"><span>${L('Sous-total','Subtotal')}</span><b class="tn">${fcfa(tot)}</b></div><div class="kv"><span>${L('Livraison (Dakar, diaspora)','Delivery (Dakar, abroad)')}</span><b>${tot>=50000?L('Offerte','Free'):fcfa(2500)}</b></div></div></div>`;},
 after:()=>S.cart.length?`<div class="cta-bar"><button class="btn y block" type="button" data-act="toCheckout">${L('Commander','Checkout')}${ic('arrow')}</button></div>`:''};
A.ciQty=t=>{const i=+t.dataset.i;S.cart[i].qty+= +t.dataset.d;if(S.cart[i].qty<=0)S.cart.splice(i,1);save();build(top());badges();buzz(4);};
A.toCheckout=()=>go('checkout',{kind:'shop'});
SCR.order={title:()=>L('Commande','Order'),render:(p)=>{const o=S.orders.find(x=>x.no===p.no)||S.orders[0];if(!o)return '';return `<div class="wrap ord"><div class="ord-ok"><span class="ord-c">${ic('check')}</span><h1 class="h1">Jërëjëf !</h1><p class="p">${L('Commande','Order')} <b class="tn">${o.no}</b> ${L('confirmée (démo).','confirmed (demo).')}</p></div>
 <div class="ord-tl"><div class="on"><i></i><b>${L('Confirmée','Confirmed')}</b></div><div><i></i><b>${L('Préparation','Preparing')}</b></div><div><i></i><b>${L('Expédiée','Shipped')}</b></div><div><i></i><b>${L('Livrée','Delivered')}</b></div><span class="ord-truck">${ic('truck')}</span></div>
 <div class="card pad">${o.items.map(i=>`<div class="ck-i"><span><b>${esc(i.n)}</b><small>${esc(i.d)}</small></span><span class="tn">${i.q} × ${fcfa(i.p)}</span></div>`).join('')}</div>
 <p class="small" style="margin-top:12px;text-align:center">${L('Paiement simulé · aucun débit · rien n’est expédié.','Simulated payment · no charge · nothing ships.')}</p>
 <button class="btn ghost block" type="button" data-act="shop" style="margin-top:12px">${L('Continuer mes achats','Keep shopping')}</button></div>`;},mount:()=>{confetti(.5,.22,90);buzz([10,40,20]);}};
