/* ================= Moi: supporter card (demo), tickets, orders, alerts, settings, credits, about ================= */
function cardHTML(big){const p=ptsTotal(),lv=levelOf(p),nx=LEVELS[lv+1];const pr=nx?(p-LEVELS[lv].min)/(nx.min-LEVELS[lv].min):1;
 return `<div class="mcard ${big?'big':''} lv${lv}" ${big?'id="mcard"':''}><div class="mc-in"><span class="mc-pat"></span><span class="mc-holo"></span>
 <div class="mc-top"><span class="mc-brand">${lionSVG()}${wordmark()}</span><span class="mc-lv">${esc(tx(LEVELS[lv].n))}</span></div>
 <div class="mc-mid"><div><small>${L('Carte supporter','Supporter card')}</small><b class="disp">${esc(S.user.first)} ${esc(S.user.last)}</b><span class="tn">${S.user.no} · ${L('depuis','since')} ${S.user.since}</span></div>${big?`<span class="mc-qr">${qrSvg(DEMO_URL(S.user.no),92)}</span>`:''}</div>
 <div class="mc-bot"><div class="mc-pts"><b class="disp tn" ${big?'data-cnt="'+p+'"':''}>${p}</b><small>pts</small></div><div class="mc-bar"><i style="--p:${Math.round(pr*100)}%"></i><small>${nx?`${nx.min-p} pts ${L('avant','to')} ${esc(tx(nx.n))}`:L('Niveau maximum','Top level')}</small></div></div>
 <span class="mc-demo">${L('DÉMO · non officielle','DEMO · unofficial')}</span></div></div>`;}
SCR.moi={large:1,title:()=>L('Moi','Me'),render:()=>{const p=ptsTotal();return `<p class="lt-s">${L('Supporter','Supporter')} · ${esc(S.user.city)} · ${S.home==='diaspora'?L('diaspora','diaspora'):L('Sénégal','Senegal')}</p>
 <div class="wrap" style="margin-top:16px"><button class="mc-btn" type="button" data-act="openCard" aria-label="${L('Ouvrir ma carte supporter','Open my supporter card')}">${cardHTML(false)}</button></div>
 <div class="me-stats wrap"><div><b class="disp tn">${S.tickets.length}</b><small>${L('billets','tickets')}</small></div><div><b class="disp tn">${Object.keys(S.pronos).length}</b><small>pronos</small></div><div><b class="disp tn">${S.quiz.best!=null?S.quiz.best+'/10':'–'}</b><small>quiz</small></div><div><b class="disp tn">${S.orders.length}</b><small>${L('commandes','orders')}</small></div></div>
 <div class="sec-h" style="margin-top:22px"><h2 class="h3">${L('Mon espace','My space')}</h2></div>
 <div class="list">
  <button class="row" type="button" data-act="tickets"><span class="ri">${ic('ticket')}</span><span class="t"><b>${L('Mes billets','My tickets')}</b><small>${S.tickets.length?`${S.tickets.length} ${L('billet(s)','ticket(s)')}`:L('Billetterie démo','Demo ticketing')}</small></span>${ic('chev')}</button>
  <button class="row" type="button" data-act="shop"><span class="ri">${ic('jersey')}</span><span class="t"><b>${L('Boutique & commandes','Shop & orders')}</b><small>${S.orders.length?`${S.orders.length} ${L('commande(s)','order(s)')}`:L('Maillots concept floqués','Personalised concept jerseys')}</small></span>${ic('chev')}</button>
  <button class="row" type="button" data-act="pronos"><span class="ri">${ic('target')}</span><span class="t"><b>${L('Mes pronos','My predictions')}</b><small>${L('Classement des amis','Friends leaderboard')}</small></span>${ic('chev')}</button>
  <button class="row" type="button" data-act="alerts"><span class="ri">${ic('bell')}</span><span class="t"><b>${L('Alertes matchs','Match alerts')}</b><small>${Object.values(S.alerts).filter(Boolean).length} ${L('match(s) suivis','match(es) followed')}</small></span>${ic('chev')}</button>
 </div>
 <div class="sec-h" style="margin-top:22px"><h2 class="h3">${L('Réglages','Settings')}</h2></div>
 <div class="list">
  <div class="row"><span class="ri">${ic('lang')}</span><span class="t"><b>${L('Langue','Language')}</b><small>${LANG==='fr'?'Français':'English'}</small></span><div class="seg mini" role="tablist" style="margin:0"><button type="button" role="tab" data-act="setLang" data-v="fr" aria-selected="${LANG==='fr'}">FR</button><button type="button" role="tab" data-act="setLang" data-v="en" aria-selected="${LANG==='en'}">EN</button></div></div>
  <button class="row" type="button" data-act="social"><span class="ri">${ic('globe')}</span><span class="t"><b>${L('Canaux officiels','Official channels')}</b><small>Instagram, YouTube, TikTok, X…</small></span>${ic('chev')}</button>
  <button class="row" type="button" data-act="credits"><span class="ri">${ic('image')}</span><span class="t"><b>${L('Crédits photos','Photo credits')}</b><small>${Object.keys(CREDITS).length} photos · Wikimedia Commons</small></span>${ic('chev')}</button>
  <button class="row" type="button" data-act="about"><span class="ri">${ic('info')}</span><span class="t"><b>${L('À propos de Gaïndé','About Gaïndé')}</b><small>${L('Concept non officiel','Unofficial concept')}</small></span>${ic('chev')}</button>
  <button class="row" type="button" data-act="resetDemo"><span class="ri">${ic('reset')}</span><span class="t"><b>${L('Réinitialiser la démo','Reset the demo')}</b><small>${L('Efface billets, pronos, panier','Clears tickets, predictions, bag')}</small></span></button>
  <a class="row" href="${LANG==='en'?'../en/#projets':'../#projets'}"><span class="ri">${ic('back')}</span><span class="t"><b>${L('Retour au CV','Back to CV')}</b><small>El Mokhtar Berrada</small></span>${ic('chev')}</a>
 </div>
 <p class="foot-note">${lionSVG()}<span>${L('Concept d’application imaginé par El Mokhtar Berrada · non officiel · non affilié à la FSF.','App concept imagined by El Mokhtar Berrada · unofficial · not affiliated with the FSF.')}</span></p>`;}};
SCR.card={modal:1,title:()=>L('Carte supporter','Supporter card'),render:()=>{const done=k=>S.pts.some(p=>p.k===k||p.k.startsWith(k));
 const ways=[['ticket',ic('ticket'),L('Acheter un billet','Buy a ticket'),150,'tickets'],['prono',ic('target'),L('Faire un prono','Make a prediction'),20,'pronos'],['quiz',ic('quiz'),L('Quiz Lions (10 pts/bonne réponse)','Lions quiz (10 pts/right answer)'),100,'quiz'],['vote',ic('vote'),L('Voter Homme du match','Vote Man of the Match'),10,'vote'],['live',ic('play'),L('Revivre un match en direct','Relive a match live'),40,'replay'],['order',ic('bag'),L('Commander en boutique','Order from the shop'),80,'shop']];
 return `<div class="wrap"><div class="mc-stage">${cardHTML(true)}</div><p class="small" style="text-align:center;margin-top:10px">${L('Inclinez votre téléphone ou survolez la carte','Tilt your phone or hover the card')}</p>
 <div class="lv-row">${LEVELS.map((l,i)=>`<div class="${levelOf(ptsTotal())>=i?'on':''}"><i></i><b>${esc(tx(l.n))}</b><small class="tn">${l.min}</small></div>`).join('')}</div>
 <div class="sec-h" style="padding:0;margin:20px 0 10px"><h2 class="h3">${L('Gagner des points','Earn points')}</h2>${demoTag()}</div>
 <div class="list" style="margin:0">${ways.map(([k,i,l,p,a])=>`<button class="row" type="button" data-act="${a}"><span class="ri ${done(k)?'ok':''}">${done(k)?ic('check'):i}</span><span class="t"><b>${l}</b><small>+${p} pts</small></span>${ic('chev')}</button>`).join('')}</div>
 <div class="sec-h" style="padding:0;margin:20px 0 10px"><h2 class="h3">${L('Historique','History')}</h2></div>
 <div class="hist">${S.pts.slice().reverse().map(p=>`<div><span>${esc(tx(p.l))}<small>${ago(p.ts)}</small></span><b class="disp tn">+${p.p}</b></div>`).join('')}</div>
 <div class="note" style="margin:16px 0 0">${ic('info')}<span>${L('Carte de fidélité de démonstration : elle illustre comment récompenser la présence au stade et l’engagement des supporters. Elle ne remplace aucune carte officielle de supporter.','Demo loyalty card: it shows how stadium attendance and fan engagement could be rewarded. It does not replace any official supporter card.')}</span></div></div>`;},
 mount:(el)=>{const c=$('#mcard',el);if(!c)return;step(5);tilt(c);const n=$('[data-cnt]',c);if(n&&!RM){const to=+n.dataset.cnt;const t0=performance.now();const f=t=>{const p=clamp((t-t0)/900,0,1);n.textContent=Math.round(to*(1-Math.pow(1-p,3)));if(p<1&&n.isConnected)requestAnimationFrame(f);};requestAnimationFrame(f);}}};
function tilt(c){if(RM)return;let tx_=0,ty_=0,cx=0,cy=0,raf=0,run=false;const inn=$('.mc-in',c);
 const loop=()=>{cx+=(tx_-cx)*.1;cy+=(ty_-cy)*.1;inn.style.transform=`rotateY(${cx*14}deg) rotateX(${-cy*12}deg)`;c.style.setProperty('--mx',(50+cx*40)+'%');c.style.setProperty('--my',(50+cy*40)+'%');if(Math.abs(tx_-cx)+Math.abs(ty_-cy)>.002&&c.isConnected)raf=requestAnimationFrame(loop);else run=false;};
 const kick=()=>{if(!run){run=true;raf=requestAnimationFrame(loop);}};
 c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect();tx_=((e.clientX-r.left)/r.width-.5)*2;ty_=((e.clientY-r.top)/r.height-.5)*2;kick();});
 c.addEventListener('pointerleave',()=>{tx_=ty_=0;kick();});
 const ori=e=>{if(e.gamma==null||!c.isConnected){window.removeEventListener('deviceorientation',ori);return;}tx_=clamp(e.gamma/25,-1,1);ty_=clamp((e.beta-45)/25,-1,1);kick();};window.addEventListener('deviceorientation',ori);
 let a=0;const idle=()=>{if(!c.isConnected)return;if(!run){a+=.02;tx_=Math.sin(a)*.35;ty_=Math.cos(a*.8)*.2;kick();}setTimeout(idle,60);};setTimeout(idle,900);}
A.openCard=()=>{if(top()&&top().name==='card')return;go('card');};
A.alerts=()=>{openSheet({label:L('Alertes','Alerts'),html:sheetHTML(L('Alertes matchs','Match alerts'),`<p class="p" style="margin-bottom:12px">${L('Recevez compos, coup d’envoi et buts pour chaque match suivi.','Get line-ups, kick-off and goals for each followed match.')}</p><div class="list" style="margin:0">${upcoming().map(f=>`<div class="row"><span class="ri">${flag(f.a||f.h,24)}</span><span class="t"><b>${esc(nat(f.h))}${f.a?' – '+esc(nat(f.a)):''}</b><small>${esc(tx(TEAM(f.t).n))} · ${esc(whenTxt(f,true))}</small></span><button class="tog" type="button" role="switch" data-act="togAlert" data-id="${f.id}" aria-checked="${!!S.alerts[f.id]}" aria-label="${L('Alerte','Alert')}"></button></div>`).join('')}</div>`)});};
A.togAlert=t=>{const id=t.dataset.id;S.alerts[id]=!S.alerts[id];save();t.setAttribute('aria-checked',!!S.alerts[id]);buzz(5);};
A.setLang=t=>setLang(t.dataset.v);
A.credits=()=>go('credits');A.about=()=>go('about');
A.resetDemo=async()=>{if(!await confirmDlg({title:L('Réinitialiser ?','Reset?'),text:L('Billets, pronos, votes, panier et points de démo seront effacés.','Demo tickets, predictions, votes, bag and points will be cleared.'),ok:L('Réinitialiser','Reset'),danger:1}))return;const lg=LANG;S=defState();S.lang=lg;S.onboarded=true;save();liveReset();renderSteps&&renderSteps();enterTabs('moi');toast(L('Démo réinitialisée','Demo reset'),{icon:'reset'});};
SCR.credits={title:()=>L('Crédits photos','Photo credits'),render:()=>`<div class="wrap"><p class="p" style="margin:6px 0 14px">${L('Toutes les photos proviennent de Wikimedia Commons, sous licences libres. Merci à leurs auteurs.','All photos come from Wikimedia Commons under free licences. Thanks to their authors.')}</p><div class="col8">${Object.entries(CREDITS).map(([id,c])=>`<div class="cr">${pic(id,{cls:'cr-ph'})}<span class="t"><b>${esc(tx(c.alt))}</b><small>${esc(c.a)} · ${c.lu?`<a href="${esc(c.lu)}" target="_blank" rel="noopener noreferrer">${esc(c.l)}</a>`:esc(c.l)}</small><a class="lnk" href="${esc(c.u)}" target="_blank" rel="noopener noreferrer">${L('Fichier sur Commons','File on Commons')}${ic('ext')}</a></span></div>`).join('')}</div>
 <p class="small" style="margin-top:14px">${L('Les joueurs sans photo libre vérifiée sont représentés par leurs initiales. Aucun logo officiel (FSF, équipementier, sponsors) n’est reproduit dans l’identité de l’application.','Players without a verified free photo are shown with their initials. No official logo (FSF, kit maker, sponsors) is reproduced in the app’s identity.')}</p></div>`};
SCR.about={title:()=>L('À propos','About'),render:()=>`<div class="wrap about"><div class="ab-mark">${lionSVG()}${wordmark()}</div>
 <p class="p" style="text-align:center"><b>${L('Concept d’application imaginé par El Mokhtar Berrada · non officiel · non affilié à la FSF','App concept imagined by El Mokhtar Berrada · unofficial · not affiliated with the FSF')}</b></p>
 <div class="card pad" style="margin-top:16px"><b class="h3">${L('La vision','The vision')}</b><p class="p" style="margin-top:6px">${L('Gaïndé (« lion » en wolof) est le compagnon de match de chaque supporter sénégalais, au stade, à la maison ou dans la diaspora. Trois missions, rien de plus : <b>suivre</b> les Lions en direct, <b>vivre</b> les coulisses, <b>soutenir</b> l’équipe (billets, maillots, carte supporter).','Gaïndé (“lion” in Wolof) is the matchday companion of every Senegalese fan, in the stadium, at home or abroad. Three jobs, nothing else: <b>follow</b> the Lions live, <b>live</b> the behind-the-scenes, <b>support</b> the team (tickets, jerseys, supporter card).')}</p></div>
 <div class="card pad" style="margin-top:10px"><b class="h3">${L('Réel ou démo ?','Real or demo?')}</b>
  <div class="kv"><span>${L('Calendrier, résultats, classement','Fixtures, results, table')}</span><b class="g">${L('Réels (FSF, FIFA)','Real (FSF, FIFA)')}</b></div>
  <div class="kv"><span>${L('Liste des Lions, clubs, staff','Lions squad, clubs, staff')}</span><b class="g">${L('Réels (fsfoot.sn)','Real (fsfoot.sn)')}</b></div>
  <div class="kv"><span>${L('Mode direct Sénégal 5-0 Irak','Live mode Senegal 5-0 Iraq')}</span><b class="g">${L('Rapport FIFA réel','Real FIFA report')}</b></div>
  <div class="kv"><span>${L('Vidéos FSF TV, réseaux officiels','FSF TV videos, official socials')}</span><b class="g">${L('Réels, vérifiés','Real, verified')}</b></div>
  <div class="kv"><span>${L('Quiz','Quiz')}</span><b class="g">${L('Faits sourcés','Sourced facts')}</b></div>
  <div class="kv"><span>${L('Billetterie, boutique, paiements','Ticketing, shop, payments')}</span><b class="y">${L('Démo, simulés','Demo, simulated')}</b></div>
  <div class="kv"><span>${L('Votes, classement pronos, fan zones, carte','Votes, prediction board, fan zones, card')}</span><b class="y">${L('Démo','Demo')}</b></div></div>
 <div class="card pad" style="margin-top:10px"><b class="h3">${L('Identité visuelle','Visual identity')}</b><p class="p" style="margin-top:6px">${L('Identité originale : lion géométrique, étoile verte, vert #00853F, or #FDEF42, rouge #E31B23 et un motif inspiré des pagnes tissés. L’écusson officiel de la FSF, les logos d’équipementier et de sponsors ne sont volontairement pas reproduits ; l’écusson pourrait être intégré avec l’accord de la Fédération.','Original identity: geometric lion, green star, green #00853F, gold #FDEF42, red #E31B23 and a motif inspired by woven cloth. The official FSF crest, kit-maker and sponsor logos are deliberately not reproduced; the crest could be added with the Federation’s approval.')}</p></div>
 <p class="small" style="text-align:center;margin-top:14px">${L('Données au 2 octobre 2026 · sources détaillées dans le dépôt (tools/fsf/sources.md).','Data as of 2 October 2026 · detailed sources in the repository (tools/fsf/sources.md).')}</p></div>`};
