/* ================= Équipe: squad, player profile (shared element), staff, Lionnes, social hub ================= */
SCR.equipe={large:1,title:()=>L('Équipe','Squad'),right:()=>`<button class="nbb" type="button" data-act="social" aria-label="${L('Canaux officiels','Official channels')}">${ic('globe')}</button>`,
 render:(p)=>{const seg=p.seg||'A';const segs=[['A',L('Lions','Lions')],['F',L('Lionnes','Lionesses')],['staff','Staff']];let body='';
 if(seg==='A')body=Object.keys(POS).map(k=>`<div class="sec-h" style="margin-top:20px"><h2 class="h3">${esc(tx(POS[k]))}</h2><span class="lbl">${SQ.filter(x=>x.p===k).length}</span></div><div class="sq wrap">${SQ.filter(x=>x.p===k).map(plCard).join('')}</div>`).join('')+
  `<div class="note">${ic('info')}<span>${L('Liste et clubs tels que publiés sur fsfoot.sn (2 octobre 2026). Numéros, sélections et buts : liste FIFA du Mondial 2026 (11 juin 2026).','Squad and clubs as published on fsfoot.sn (2 October 2026). Numbers, caps and goals: FIFA 2026 World Cup list (11 June 2026).')} ${ext('https://fsfoot.sn/lions-du-senegal/','fsfoot.sn')}</span></div>`;
 else if(seg==='F'){const fx=FIX.filter(f=>f.t==='F');body=`<div class="wrap"><div class="lio"><div class="lio-bg">${pic('fans-4',{big:1,alt:''})}</div><div class="lio-in"><span class="kick">${L('Équipe A féminine','Senior women')}</span><b class="h1">${L('Les Lionnes','The Lionesses')}</b><p class="p">${L('Nouveau sélectionneur : <b>Alioune Abitalib Fall</b> (ex-U-20 féminines). Stage à Thiès, stade Lat Dior, du 25 septembre au 4 octobre.','New head coach: <b>Alioune Abitalib Fall</b> (ex U-20 women). Camp in Thiès, Lat Dior stadium, 25 Sept – 4 Oct.')}</p></div></div>
  <div class="col8" style="margin-top:12px">${fx.map(fixCard).join('')}</div>
  <div class="note" style="margin:12px 0 0">${ic('info')}<span>${L('24 joueuses du championnat local sont en stage ; la liste définitive, élargie aux joueuses de l’étranger, sera publiée après le 4 octobre. Nous n’affichons pas de noms avant l’annonce officielle.','24 home-based players are in camp; the final list, including players abroad, will be published after 4 October. No names are shown before the official announcement.')} ${ext('https://dsports.sn/eliminatoires-jo-2028-abatalib-fall-convoque-24-joueuses/','dsports.sn')}</span></div>
  <a class="row soc-row" href="https://www.instagram.com/gaindeyifeminine/" target="_blank" rel="noopener noreferrer" style="margin-top:12px;border-radius:16px;background:var(--card);border:1px solid var(--line)"><span class="ri ig">${ic('p_ig')}</span><span class="t"><b>@gaindeyifeminine</b><small>${L('Instagram officiel des équipes nationales féminines','Official Instagram of the women’s national teams')}</small></span>${ic('ext')}</a></div>`;}
 else body=`<div class="wrap col8 stg">${STAFF.map(s=>`<div class="stf">${hasPh(s.ph)?pic(s.ph,{cls:'stf-ph'}):`<span class="stf-ph initials"><b style="font-size:22px">${esc(initials(s.n))}</b></span>`}<span class="t"><b>${esc(s.n)}</b><small>${esc(tx(s.r))}</small>${s.so?`<span class="so-row">${socLinks(s.so)}</span>`:''}</span></div>`).join('')}</div>
  <p class="small wrap" style="margin-top:12px">${L('Sources : fsfoot.sn et FSF TV (septembre 2026).','Sources: fsfoot.sn and FSF TV (September 2026).')}</p>`;
 return `<p class="lt-s">${L('Les sélections nationales du Sénégal','Senegal’s national teams')}</p><div class="seg" role="tablist" style="margin-top:14px">${segs.map(([k,l])=>`<button type="button" role="tab" data-act="tSeg" data-v="${k}" aria-selected="${seg===k}">${l}</button>`).join('')}</div>
 <section class="sec" style="margin-top:16px"><div class="hscroll">${SOCIAL.slice(1,5).map(socTile).join('')}<button class="soc more-soc" type="button" data-act="social"><span class="soc-i">${ic('plus')}</span><b>${L('Tous les canaux','All channels')}</b><small>${L('Site, X, TikTok, Facebook','Website, X, TikTok, Facebook')}</small></button></div></section>${body}`;}};
A.tSeg=t=>{const e=top();e.params.seg=t.dataset.v;e.scroll=0;build(e);buzz(4);};
function plCard(p){return `<button class="plc st" type="button" data-act="player" data-id="${p.id}">${face(p,{size:40,cls:'plc-ph'})}<span class="plc-g"></span>${p.no?`<span class="plc-no disp">${p.no}</span>`:''}${p.cap?`<span class="plc-c">C</span>`:''}${p.nw?`<span class="plc-new">${L('Nouveau','New')}</span>`:''}<span class="plc-t"><b>${esc(shortN(p.n))}</b><small>${esc(p.cl)}</small></span></button>`;}
const SOCN={ig:['p_ig','Instagram','https://www.instagram.com/'],x:['p_x','X','https://x.com/']};
function socLinks(so){return Object.entries(so).map(([k,h])=>`<a class="so-l ${k}" href="${SOCN[k][2]}${encodeURIComponent(h)}/" target="_blank" rel="noopener noreferrer" aria-label="${SOCN[k][1]} @${esc(h)}">${ic(SOCN[k][0])}<span>@${esc(h)}</span></a>`).join('');}
SCR.player={hero:1,title:p=>P(p.id).n,short:p=>shortN(P(p.id).n),
 render:(p)=>{const pl=P(p.id);const age=ageOf(pl.dob);const cr=CREDITS[pl.ph];const vids=VIDEOS.filter(v=>(v.pl||[]).includes(pl.id));
 return `<div class="pl-hero"><div class="pl-bg" data-par>${hasPh(pl.ph)?pic(pl.ph,{big:1,eager:1,fp:1,alt:pl.n}):initialsTile(pl,'pl-ini',110)}</div>${pl.no?`<span class="pl-no disp" aria-hidden="true">${pl.no}</span>`:''}
  <div class="pl-in" data-fade><span class="kick">${esc(tx(pl.r))}${pl.cap?` · ${L('Capitaine','Captain')}`:''}</span><h1 class="pl-n disp">${esc(pl.n.split(' ').slice(0,-1).join(' '))}<b>${esc(pl.n.split(' ').slice(-1)[0])}</b></h1><span class="pl-club">${ic('jersey')}${esc(pl.cl)}</span></div></div>
 <div class="pl-stats stg">${pl.no?`<div><b class="disp tn">${pl.no}</b><small>${L('N° au Mondial','World Cup no.')}</small></div>`:''}${age?`<div><b class="disp tn">${age}</b><small>${L('ans','years')}</small></div>`:''}${pl.cp!=null?`<div><b class="disp tn">${pl.cp}</b><small>${L('sélections*','caps*')}</small></div><div><b class="disp tn">${pl.gl}</b><small>${L('buts*','goals*')}</small></div>`:''}${pl.wc?`<div class="hl"><b class="disp tn">${pl.wc}</b><small>${L('buts au Mondial 2026','2026 World Cup goals')}</small></div>`:''}</div>
 ${pl.cp!=null?`<p class="small wrap">* ${L('au 11 juin 2026, liste officielle FIFA du Mondial.','as of 11 June 2026, official FIFA World Cup list.')}</p>`:''}
 ${pl.rec?`<div class="note">${ic('trophy')}<span>${esc(tx(pl.rec))} · 136 ${L('sélections','caps')}</span></div>`:''}
 ${pl.nw?`<div class="note">${ic('sparkle')}<span>${L('Éligibilité confirmée par la FIFA le 23 septembre 2026.','Eligibility confirmed by FIFA on 23 September 2026.')} ${ext('https://fsfoot.sn/actualites/equipe-nationale-du-senegal-la-fifa-confirme-leligibilite-de-rassoul-ndiaye-malang-sarr-et-lamine-sy/','fsfoot.sn')}</span></div>`:''}
 <section class="sec"><div class="sec-h"><h2 class="h3">${L('Réseaux officiels','Official socials')}</h2></div><div class="wrap">${pl.so?`<div class="so-big">${Object.entries(pl.so).map(([k,h])=>`<a class="row" href="${SOCN[k][2]}${encodeURIComponent(h)}/" target="_blank" rel="noopener noreferrer"><span class="ri ${k}">${ic(SOCN[k][0])}</span><span class="t"><b>@${esc(h)}</b><small>${SOCN[k][1]} · ${L('compte vérifié / référencé','verified / referenced account')}</small></span>${ic('ext')}</a>`).join('')}</div>`:`<p class="small">${L('Aucun compte officiel vérifiable à ce jour : nous préférons ne rien afficher plutôt qu’un faux compte. Suivez les Lions sur','No verifiable official account to date: we’d rather show nothing than a fake account. Follow the Lions on')} ${ext('https://www.instagram.com/gaindeyi/','@gaindeyi')}.</p>`}</div></section>
 ${vids.length?`<section class="sec"><div class="sec-h"><h2 class="h3">FSF TV</h2></div><div class="hscroll">${vids.map(v=>videoCard(v)).join('')}</div></section>`:''}
 ${pl.no?`<section class="sec"><div class="wrap"><button class="row" type="button" data-act="shopFor" data-id="${pl.id}" style="border-radius:16px;background:var(--card);border:1px solid var(--line)"><span class="ri">${ic('jersey')}</span><span class="t"><b>${L('Floquer un maillot','Personalise a jersey')} ${esc(shortN(pl.n).toUpperCase())} ${pl.no}</b><small>${L('Création concept · démo','Concept design · demo')}</small></span>${ic('chev')}</button></div></section>`:''}
 ${cr?`<p class="small wrap credit">${ic('image')} ${L('Photo','Photo')} : ${esc(cr.a)} · ${esc(cr.l)} · ${ext(cr.u,'Wikimedia Commons')}</p>`:''}`;},
 mount:(el)=>{el._th=330;}};
A.player=t=>{const id=t.dataset.id;if(!P(id))return;const e=top();if(e&&e.name==='player'&&e.params.id===id)return;go('player',{id});};
SCR.social={title:()=>L('Canaux officiels','Official channels'),render:()=>`<div class="wrap"><p class="p" style="margin:6px 0 14px">${L('Les comptes officiels de la Fédération et des équipes nationales, vérifiés un par un.','The official accounts of the Federation and the national teams, checked one by one.')}</p><div class="socg stg">${SOCIAL.map(socTile).join('')}</div>
 <div class="note" style="margin:16px 0 0">${ic('check')}<span>${L('Vérification au 2 octobre 2026 : lien depuis le site fsfoot.sn ou le compte Instagram certifié @fsfofficielle, badge de vérification ou citation constante par les médias. Les comptes non vérifiables sont exclus.','Checked on 2 October 2026: linked from fsfoot.sn or the verified @fsfofficielle Instagram, verification badge or consistent media citation. Unverifiable accounts are excluded.')}</span></div></div>`};
A.social=()=>go('social');
